/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Beta Workspace API
 * API documentation for Beta - an integrated workspace platform that helps teams work more efficiently through a unified ecosystem: team chat, collaborative documents, email, task management, and workflow automation.
 * OpenAPI spec version: 1.0.0
 */
import { useInfiniteQuery, useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  GetAuthRoomCircleId200,
  GetAuthRoomCircleIdParams,
  PatchAuthRoomRoomId200,
  PostAuthRoom200,
  PostAuthRoom201,
  RequestRoomRequest,
} from '../generated.schemas';

import postAuthRoomMutator from '../../config/axios';
import getAuthRoomCircleIdMutator from '../../config/axios';
import patchAuthRoomRoomIdMutator from '../../config/axios';

/**
 * API lấy thông tin room nếu room đã tồn tại, ngược lại nếu chưa tồn tại sẽ tạo room mới
 * @summary Lấy thông tin hoặc tạo room
 */
export const postAuthRoom = (requestRoomRequest: RequestRoomRequest, signal?: AbortSignal) => {
  return postAuthRoomMutator<PostAuthRoom200 | PostAuthRoom201>({
    url: `/auth/room/`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: requestRoomRequest,
    signal,
  });
};

export const getPostAuthRoomMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthRoom>>,
    TError,
    { data: RequestRoomRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postAuthRoom>>,
  TError,
  { data: RequestRoomRequest },
  TContext
> => {
  const mutationKey = ['postAuthRoom'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postAuthRoom>>,
    { data: RequestRoomRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postAuthRoom(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostAuthRoomMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthRoom>>>;
export type PostAuthRoomMutationBody = RequestRoomRequest;
export type PostAuthRoomMutationError = unknown;

/**
 * @summary Lấy thông tin hoặc tạo room
 */
export const usePostAuthRoom = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postAuthRoom>>,
      TError,
      { data: RequestRoomRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postAuthRoom>>,
  TError,
  { data: RequestRoomRequest },
  TContext
> => {
  const mutationOptions = getPostAuthRoomMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * API lấy danh sách room
 * @summary Lấy danh sách room
 */
export const getAuthRoomCircleId = (
  circleId: string,
  params: GetAuthRoomCircleIdParams,
  signal?: AbortSignal,
) => {
  return getAuthRoomCircleIdMutator<GetAuthRoomCircleId200>({
    url: `/auth/room/${circleId}`,
    method: 'GET',
    params,
    signal,
  });
};

export const getGetAuthRoomCircleIdQueryKey = (
  circleId?: string,
  params?: GetAuthRoomCircleIdParams,
) => {
  return [`/auth/room/${circleId}`, ...(params ? [params] : [])] as const;
};

export const getGetAuthRoomCircleIdInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthRoomCircleId>>>,
  TError = unknown,
>(
  circleId: string,
  params: GetAuthRoomCircleIdParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAuthRoomCircleId>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAuthRoomCircleIdQueryKey(circleId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthRoomCircleId>>> = ({ signal }) =>
    getAuthRoomCircleId(circleId, params, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!circleId,
    staleTime: 10000,
    ...queryOptions,
  } as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAuthRoomCircleId>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetAuthRoomCircleIdInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAuthRoomCircleId>>
>;
export type GetAuthRoomCircleIdInfiniteQueryError = unknown;

export function useGetAuthRoomCircleIdInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthRoomCircleId>>>,
  TError = unknown,
>(
  circleId: string,
  params: GetAuthRoomCircleIdParams,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAuthRoomCircleId>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthRoomCircleId>>,
          TError,
          Awaited<ReturnType<typeof getAuthRoomCircleId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthRoomCircleIdInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthRoomCircleId>>>,
  TError = unknown,
>(
  circleId: string,
  params: GetAuthRoomCircleIdParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAuthRoomCircleId>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthRoomCircleId>>,
          TError,
          Awaited<ReturnType<typeof getAuthRoomCircleId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthRoomCircleIdInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthRoomCircleId>>>,
  TError = unknown,
>(
  circleId: string,
  params: GetAuthRoomCircleIdParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAuthRoomCircleId>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Lấy danh sách room
 */

export function useGetAuthRoomCircleIdInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthRoomCircleId>>>,
  TError = unknown,
>(
  circleId: string,
  params: GetAuthRoomCircleIdParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAuthRoomCircleId>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAuthRoomCircleIdInfiniteQueryOptions(circleId, params, options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetAuthRoomCircleIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getAuthRoomCircleId>>,
  TError = unknown,
>(
  circleId: string,
  params: GetAuthRoomCircleIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthRoomCircleId>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAuthRoomCircleIdQueryKey(circleId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthRoomCircleId>>> = ({ signal }) =>
    getAuthRoomCircleId(circleId, params, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!circleId,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getAuthRoomCircleId>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetAuthRoomCircleIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAuthRoomCircleId>>
>;
export type GetAuthRoomCircleIdQueryError = unknown;

export function useGetAuthRoomCircleId<
  TData = Awaited<ReturnType<typeof getAuthRoomCircleId>>,
  TError = unknown,
>(
  circleId: string,
  params: GetAuthRoomCircleIdParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthRoomCircleId>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthRoomCircleId>>,
          TError,
          Awaited<ReturnType<typeof getAuthRoomCircleId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthRoomCircleId<
  TData = Awaited<ReturnType<typeof getAuthRoomCircleId>>,
  TError = unknown,
>(
  circleId: string,
  params: GetAuthRoomCircleIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthRoomCircleId>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthRoomCircleId>>,
          TError,
          Awaited<ReturnType<typeof getAuthRoomCircleId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthRoomCircleId<
  TData = Awaited<ReturnType<typeof getAuthRoomCircleId>>,
  TError = unknown,
>(
  circleId: string,
  params: GetAuthRoomCircleIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthRoomCircleId>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Lấy danh sách room
 */

export function useGetAuthRoomCircleId<
  TData = Awaited<ReturnType<typeof getAuthRoomCircleId>>,
  TError = unknown,
>(
  circleId: string,
  params: GetAuthRoomCircleIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthRoomCircleId>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAuthRoomCircleIdQueryOptions(circleId, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * API delete direct room
 * @summary Delete Direct Room
 */
export const patchAuthRoomRoomId = (roomId: string) => {
  return patchAuthRoomRoomIdMutator<PatchAuthRoomRoomId200>({
    url: `/auth/room/${roomId}`,
    method: 'PATCH',
  });
};

export const getPatchAuthRoomRoomIdMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof patchAuthRoomRoomId>>,
    TError,
    { roomId: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof patchAuthRoomRoomId>>,
  TError,
  { roomId: string },
  TContext
> => {
  const mutationKey = ['patchAuthRoomRoomId'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof patchAuthRoomRoomId>>,
    { roomId: string }
  > = (props) => {
    const { roomId } = props ?? {};

    return patchAuthRoomRoomId(roomId);
  };

  return { mutationFn, ...mutationOptions };
};

export type PatchAuthRoomRoomIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof patchAuthRoomRoomId>>
>;

export type PatchAuthRoomRoomIdMutationError = unknown;

/**
 * @summary Delete Direct Room
 */
export const usePatchAuthRoomRoomId = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof patchAuthRoomRoomId>>,
      TError,
      { roomId: string },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof patchAuthRoomRoomId>>,
  TError,
  { roomId: string },
  TContext
> => {
  const mutationOptions = getPatchAuthRoomRoomIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
