/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Beta Workspace API
 * API documentation for Beta - an integrated workspace platform that helps teams work more efficiently through a unified ecosystem: team chat, collaborative documents, email, task management, and workflow automation.
 * OpenAPI spec version: 1.0.0
 */
import { useInfiniteQuery, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { ModelsAssetLinks, ModelsConfig } from '../generated.schemas';

import getWellKnownAppleAppSiteAssociationMutator from '../../config/axios';
import getWellKnownAssetlinksJsonMutator from '../../config/axios';
import getPublicKeyMutator from '../../config/axios';

/**
 * lấy thông tin file apple-app-site-association
 * @summary get file apple-app-site-association
 */
export const getWellKnownAppleAppSiteAssociation = (signal?: AbortSignal) => {
  return getWellKnownAppleAppSiteAssociationMutator<ModelsConfig>({
    url: `/.well-known/apple-app-site-association`,
    method: 'GET',
    signal,
  });
};

export const getGetWellKnownAppleAppSiteAssociationQueryKey = () => {
  return [`/.well-known/apple-app-site-association`] as const;
};

export const getGetWellKnownAppleAppSiteAssociationInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof getWellKnownAppleAppSiteAssociation>>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseInfiniteQueryOptions<
      Awaited<ReturnType<typeof getWellKnownAppleAppSiteAssociation>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetWellKnownAppleAppSiteAssociationQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getWellKnownAppleAppSiteAssociation>>> = ({
    signal,
  }) => getWellKnownAppleAppSiteAssociation(signal);

  return { queryKey, queryFn, staleTime: 10000, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getWellKnownAppleAppSiteAssociation>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetWellKnownAppleAppSiteAssociationInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getWellKnownAppleAppSiteAssociation>>
>;
export type GetWellKnownAppleAppSiteAssociationInfiniteQueryError = unknown;

export function useGetWellKnownAppleAppSiteAssociationInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getWellKnownAppleAppSiteAssociation>>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getWellKnownAppleAppSiteAssociation>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWellKnownAppleAppSiteAssociation>>,
          TError,
          Awaited<ReturnType<typeof getWellKnownAppleAppSiteAssociation>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetWellKnownAppleAppSiteAssociationInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getWellKnownAppleAppSiteAssociation>>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getWellKnownAppleAppSiteAssociation>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWellKnownAppleAppSiteAssociation>>,
          TError,
          Awaited<ReturnType<typeof getWellKnownAppleAppSiteAssociation>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetWellKnownAppleAppSiteAssociationInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getWellKnownAppleAppSiteAssociation>>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getWellKnownAppleAppSiteAssociation>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary get file apple-app-site-association
 */

export function useGetWellKnownAppleAppSiteAssociationInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getWellKnownAppleAppSiteAssociation>>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getWellKnownAppleAppSiteAssociation>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetWellKnownAppleAppSiteAssociationInfiniteQueryOptions(options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetWellKnownAppleAppSiteAssociationQueryOptions = <
  TData = Awaited<ReturnType<typeof getWellKnownAppleAppSiteAssociation>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getWellKnownAppleAppSiteAssociation>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetWellKnownAppleAppSiteAssociationQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getWellKnownAppleAppSiteAssociation>>> = ({
    signal,
  }) => getWellKnownAppleAppSiteAssociation(signal);

  return { queryKey, queryFn, staleTime: 10000, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getWellKnownAppleAppSiteAssociation>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetWellKnownAppleAppSiteAssociationQueryResult = NonNullable<
  Awaited<ReturnType<typeof getWellKnownAppleAppSiteAssociation>>
>;
export type GetWellKnownAppleAppSiteAssociationQueryError = unknown;

export function useGetWellKnownAppleAppSiteAssociation<
  TData = Awaited<ReturnType<typeof getWellKnownAppleAppSiteAssociation>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getWellKnownAppleAppSiteAssociation>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWellKnownAppleAppSiteAssociation>>,
          TError,
          Awaited<ReturnType<typeof getWellKnownAppleAppSiteAssociation>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetWellKnownAppleAppSiteAssociation<
  TData = Awaited<ReturnType<typeof getWellKnownAppleAppSiteAssociation>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getWellKnownAppleAppSiteAssociation>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWellKnownAppleAppSiteAssociation>>,
          TError,
          Awaited<ReturnType<typeof getWellKnownAppleAppSiteAssociation>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetWellKnownAppleAppSiteAssociation<
  TData = Awaited<ReturnType<typeof getWellKnownAppleAppSiteAssociation>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getWellKnownAppleAppSiteAssociation>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary get file apple-app-site-association
 */

export function useGetWellKnownAppleAppSiteAssociation<
  TData = Awaited<ReturnType<typeof getWellKnownAppleAppSiteAssociation>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getWellKnownAppleAppSiteAssociation>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetWellKnownAppleAppSiteAssociationQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * lấy thông tin file assetlinks.json
 * @summary get file assetlinks.json
 */
export const getWellKnownAssetlinksJson = (signal?: AbortSignal) => {
  return getWellKnownAssetlinksJsonMutator<ModelsAssetLinks[]>({
    url: `/.well-known/assetlinks.json`,
    method: 'GET',
    signal,
  });
};

export const getGetWellKnownAssetlinksJsonQueryKey = () => {
  return [`/.well-known/assetlinks.json`] as const;
};

export const getGetWellKnownAssetlinksJsonInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof getWellKnownAssetlinksJson>>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseInfiniteQueryOptions<Awaited<ReturnType<typeof getWellKnownAssetlinksJson>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetWellKnownAssetlinksJsonQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getWellKnownAssetlinksJson>>> = ({
    signal,
  }) => getWellKnownAssetlinksJson(signal);

  return { queryKey, queryFn, staleTime: 10000, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getWellKnownAssetlinksJson>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetWellKnownAssetlinksJsonInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getWellKnownAssetlinksJson>>
>;
export type GetWellKnownAssetlinksJsonInfiniteQueryError = unknown;

export function useGetWellKnownAssetlinksJsonInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getWellKnownAssetlinksJson>>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getWellKnownAssetlinksJson>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWellKnownAssetlinksJson>>,
          TError,
          Awaited<ReturnType<typeof getWellKnownAssetlinksJson>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetWellKnownAssetlinksJsonInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getWellKnownAssetlinksJson>>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getWellKnownAssetlinksJson>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWellKnownAssetlinksJson>>,
          TError,
          Awaited<ReturnType<typeof getWellKnownAssetlinksJson>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetWellKnownAssetlinksJsonInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getWellKnownAssetlinksJson>>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getWellKnownAssetlinksJson>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary get file assetlinks.json
 */

export function useGetWellKnownAssetlinksJsonInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getWellKnownAssetlinksJson>>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getWellKnownAssetlinksJson>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetWellKnownAssetlinksJsonInfiniteQueryOptions(options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetWellKnownAssetlinksJsonQueryOptions = <
  TData = Awaited<ReturnType<typeof getWellKnownAssetlinksJson>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getWellKnownAssetlinksJson>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetWellKnownAssetlinksJsonQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getWellKnownAssetlinksJson>>> = ({
    signal,
  }) => getWellKnownAssetlinksJson(signal);

  return { queryKey, queryFn, staleTime: 10000, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getWellKnownAssetlinksJson>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetWellKnownAssetlinksJsonQueryResult = NonNullable<
  Awaited<ReturnType<typeof getWellKnownAssetlinksJson>>
>;
export type GetWellKnownAssetlinksJsonQueryError = unknown;

export function useGetWellKnownAssetlinksJson<
  TData = Awaited<ReturnType<typeof getWellKnownAssetlinksJson>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getWellKnownAssetlinksJson>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWellKnownAssetlinksJson>>,
          TError,
          Awaited<ReturnType<typeof getWellKnownAssetlinksJson>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetWellKnownAssetlinksJson<
  TData = Awaited<ReturnType<typeof getWellKnownAssetlinksJson>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getWellKnownAssetlinksJson>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getWellKnownAssetlinksJson>>,
          TError,
          Awaited<ReturnType<typeof getWellKnownAssetlinksJson>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetWellKnownAssetlinksJson<
  TData = Awaited<ReturnType<typeof getWellKnownAssetlinksJson>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getWellKnownAssetlinksJson>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary get file assetlinks.json
 */

export function useGetWellKnownAssetlinksJson<
  TData = Awaited<ReturnType<typeof getWellKnownAssetlinksJson>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getWellKnownAssetlinksJson>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetWellKnownAssetlinksJsonQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * API lấy public key RSA để client có thể mã hóa dữ liệu
 * @summary Lấy public key để mã hóa RSA
 */
export const getPublicKey = (signal?: AbortSignal) => {
  return getPublicKeyMutator<string>({ url: `/public_key`, method: 'GET', signal });
};

export const getGetPublicKeyQueryKey = () => {
  return [`/public_key`] as const;
};

export const getGetPublicKeyInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof getPublicKey>>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getPublicKey>>, TError, TData>>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetPublicKeyQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPublicKey>>> = ({ signal }) =>
    getPublicKey(signal);

  return { queryKey, queryFn, staleTime: 10000, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getPublicKey>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetPublicKeyInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getPublicKey>>>;
export type GetPublicKeyInfiniteQueryError = unknown;

export function useGetPublicKeyInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getPublicKey>>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getPublicKey>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPublicKey>>,
          TError,
          Awaited<ReturnType<typeof getPublicKey>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetPublicKeyInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getPublicKey>>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getPublicKey>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPublicKey>>,
          TError,
          Awaited<ReturnType<typeof getPublicKey>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetPublicKeyInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getPublicKey>>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getPublicKey>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Lấy public key để mã hóa RSA
 */

export function useGetPublicKeyInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getPublicKey>>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getPublicKey>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetPublicKeyInfiniteQueryOptions(options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetPublicKeyQueryOptions = <
  TData = Awaited<ReturnType<typeof getPublicKey>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublicKey>>, TError, TData>>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetPublicKeyQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getPublicKey>>> = ({ signal }) =>
    getPublicKey(signal);

  return { queryKey, queryFn, staleTime: 10000, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getPublicKey>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetPublicKeyQueryResult = NonNullable<Awaited<ReturnType<typeof getPublicKey>>>;
export type GetPublicKeyQueryError = unknown;

export function useGetPublicKey<TData = Awaited<ReturnType<typeof getPublicKey>>, TError = unknown>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublicKey>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPublicKey>>,
          TError,
          Awaited<ReturnType<typeof getPublicKey>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetPublicKey<TData = Awaited<ReturnType<typeof getPublicKey>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublicKey>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPublicKey>>,
          TError,
          Awaited<ReturnType<typeof getPublicKey>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetPublicKey<TData = Awaited<ReturnType<typeof getPublicKey>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublicKey>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Lấy public key để mã hóa RSA
 */

export function useGetPublicKey<TData = Awaited<ReturnType<typeof getPublicKey>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getPublicKey>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetPublicKeyQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
