/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Beta Workspace API
 * API documentation for Beta - an integrated workspace platform that helps teams work more efficiently through a unified ecosystem: team chat, collaborative documents, email, task management, and workflow automation.
 * OpenAPI spec version: 1.0.0
 */
import { useInfiniteQuery, useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  GetChatRoomId200,
  GetChatRoomIdParams,
  RequestCreateMessageRequest,
  ResponseResponse,
} from '../generated.schemas';

import getChatRoomIdMutator from '../../../config/axios';
import postChatRoomIdMutator from '../../../config/axios';

/**
 * API lấy danh sách tin nhắn dựa trong phòng chat, có phân trang
 * @summary Lấy danh sách tin nhắn
 */
export const getChatRoomId = (
  roomId: string,
  params: GetChatRoomIdParams,
  signal?: AbortSignal,
) => {
  return getChatRoomIdMutator<GetChatRoomId200>({
    url: `/chat/${roomId}`,
    method: 'GET',
    params,
    signal,
  });
};

export const getGetChatRoomIdQueryKey = (roomId?: string, params?: GetChatRoomIdParams) => {
  return [`/chat/${roomId}`, ...(params ? [params] : [])] as const;
};

export const getGetChatRoomIdInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof getChatRoomId>>>,
  TError = unknown,
>(
  roomId: string,
  params: GetChatRoomIdParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getChatRoomId>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetChatRoomIdQueryKey(roomId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getChatRoomId>>> = ({ signal }) =>
    getChatRoomId(roomId, params, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!roomId,
    staleTime: 10000,
    ...queryOptions,
  } as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getChatRoomId>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetChatRoomIdInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getChatRoomId>>
>;
export type GetChatRoomIdInfiniteQueryError = unknown;

export function useGetChatRoomIdInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getChatRoomId>>>,
  TError = unknown,
>(
  roomId: string,
  params: GetChatRoomIdParams,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getChatRoomId>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChatRoomId>>,
          TError,
          Awaited<ReturnType<typeof getChatRoomId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetChatRoomIdInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getChatRoomId>>>,
  TError = unknown,
>(
  roomId: string,
  params: GetChatRoomIdParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getChatRoomId>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChatRoomId>>,
          TError,
          Awaited<ReturnType<typeof getChatRoomId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetChatRoomIdInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getChatRoomId>>>,
  TError = unknown,
>(
  roomId: string,
  params: GetChatRoomIdParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getChatRoomId>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Lấy danh sách tin nhắn
 */

export function useGetChatRoomIdInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getChatRoomId>>>,
  TError = unknown,
>(
  roomId: string,
  params: GetChatRoomIdParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getChatRoomId>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetChatRoomIdInfiniteQueryOptions(roomId, params, options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetChatRoomIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getChatRoomId>>,
  TError = unknown,
>(
  roomId: string,
  params: GetChatRoomIdParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getChatRoomId>>, TError, TData>>;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetChatRoomIdQueryKey(roomId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getChatRoomId>>> = ({ signal }) =>
    getChatRoomId(roomId, params, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!roomId,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getChatRoomId>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetChatRoomIdQueryResult = NonNullable<Awaited<ReturnType<typeof getChatRoomId>>>;
export type GetChatRoomIdQueryError = unknown;

export function useGetChatRoomId<
  TData = Awaited<ReturnType<typeof getChatRoomId>>,
  TError = unknown,
>(
  roomId: string,
  params: GetChatRoomIdParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getChatRoomId>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChatRoomId>>,
          TError,
          Awaited<ReturnType<typeof getChatRoomId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetChatRoomId<
  TData = Awaited<ReturnType<typeof getChatRoomId>>,
  TError = unknown,
>(
  roomId: string,
  params: GetChatRoomIdParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getChatRoomId>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getChatRoomId>>,
          TError,
          Awaited<ReturnType<typeof getChatRoomId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetChatRoomId<
  TData = Awaited<ReturnType<typeof getChatRoomId>>,
  TError = unknown,
>(
  roomId: string,
  params: GetChatRoomIdParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getChatRoomId>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Lấy danh sách tin nhắn
 */

export function useGetChatRoomId<
  TData = Awaited<ReturnType<typeof getChatRoomId>>,
  TError = unknown,
>(
  roomId: string,
  params: GetChatRoomIdParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getChatRoomId>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetChatRoomIdQueryOptions(roomId, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * API khởi tạo tin nhắn và gửi đi thông qua websocket
 * @summary Tạo và gửi tin nhắn
 */
export const postChatRoomId = (
  roomId: string,
  requestCreateMessageRequest: RequestCreateMessageRequest,
  signal?: AbortSignal,
) => {
  return postChatRoomIdMutator<ResponseResponse>({
    url: `/chat/${roomId}`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: requestCreateMessageRequest,
    signal,
  });
};

export const getPostChatRoomIdMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postChatRoomId>>,
    TError,
    { roomId: string; data: RequestCreateMessageRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postChatRoomId>>,
  TError,
  { roomId: string; data: RequestCreateMessageRequest },
  TContext
> => {
  const mutationKey = ['postChatRoomId'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postChatRoomId>>,
    { roomId: string; data: RequestCreateMessageRequest }
  > = (props) => {
    const { roomId, data } = props ?? {};

    return postChatRoomId(roomId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostChatRoomIdMutationResult = NonNullable<Awaited<ReturnType<typeof postChatRoomId>>>;
export type PostChatRoomIdMutationBody = RequestCreateMessageRequest;
export type PostChatRoomIdMutationError = unknown;

/**
 * @summary Tạo và gửi tin nhắn
 */
export const usePostChatRoomId = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postChatRoomId>>,
      TError,
      { roomId: string; data: RequestCreateMessageRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postChatRoomId>>,
  TError,
  { roomId: string; data: RequestCreateMessageRequest },
  TContext
> => {
  const mutationOptions = getPostChatRoomIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
