/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Beta Workspace API
 * API documentation for Beta - an integrated workspace platform that helps teams work more efficiently through a unified ecosystem: team chat, collaborative documents, email, task management, and workflow automation.
 * OpenAPI spec version: 1.0.0
 */
import { useInfiniteQuery, useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  GetAuthLabelsTemplates200,
  GetAuthProjectsProjectIdLabels200,
  PatchAuthLabels200,
  PostAuthLabels200,
  RequestCreateLabelRequest,
  RequestDeleteLabelRequest,
  RequestUpdateLabelRequest,
  ResponseResponse,
} from '../generated.schemas';

import deleteAuthLabelsMutator from '../../../config/axios';
import patchAuthLabelsMutator from '../../../config/axios';
import postAuthLabelsMutator from '../../../config/axios';
import getAuthLabelsTemplatesMutator from '../../../config/axios';
import getAuthProjectsProjectIdLabelsMutator from '../../../config/axios';

/**
 * API xóa label khỏi dự án (sẽ xóa khỏi tất cả tasks)
 * @summary Xóa label
 */
export const deleteAuthLabels = (requestDeleteLabelRequest: RequestDeleteLabelRequest) => {
  return deleteAuthLabelsMutator<ResponseResponse>({
    url: `/auth/labels`,
    method: 'DELETE',
    headers: { 'Content-Type': 'application/json' },
    data: requestDeleteLabelRequest,
  });
};

export const getDeleteAuthLabelsMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteAuthLabels>>,
    TError,
    { data: RequestDeleteLabelRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteAuthLabels>>,
  TError,
  { data: RequestDeleteLabelRequest },
  TContext
> => {
  const mutationKey = ['deleteAuthLabels'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteAuthLabels>>,
    { data: RequestDeleteLabelRequest }
  > = (props) => {
    const { data } = props ?? {};

    return deleteAuthLabels(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteAuthLabelsMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteAuthLabels>>
>;
export type DeleteAuthLabelsMutationBody = RequestDeleteLabelRequest;
export type DeleteAuthLabelsMutationError = unknown;

/**
 * @summary Xóa label
 */
export const useDeleteAuthLabels = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteAuthLabels>>,
      TError,
      { data: RequestDeleteLabelRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteAuthLabels>>,
  TError,
  { data: RequestDeleteLabelRequest },
  TContext
> => {
  const mutationOptions = getDeleteAuthLabelsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * API cập nhật thông tin label
 * @summary Cập nhật label
 */
export const patchAuthLabels = (requestUpdateLabelRequest: RequestUpdateLabelRequest) => {
  return patchAuthLabelsMutator<PatchAuthLabels200>({
    url: `/auth/labels`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    data: requestUpdateLabelRequest,
  });
};

export const getPatchAuthLabelsMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof patchAuthLabels>>,
    TError,
    { data: RequestUpdateLabelRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof patchAuthLabels>>,
  TError,
  { data: RequestUpdateLabelRequest },
  TContext
> => {
  const mutationKey = ['patchAuthLabels'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof patchAuthLabels>>,
    { data: RequestUpdateLabelRequest }
  > = (props) => {
    const { data } = props ?? {};

    return patchAuthLabels(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PatchAuthLabelsMutationResult = NonNullable<
  Awaited<ReturnType<typeof patchAuthLabels>>
>;
export type PatchAuthLabelsMutationBody = RequestUpdateLabelRequest;
export type PatchAuthLabelsMutationError = unknown;

/**
 * @summary Cập nhật label
 */
export const usePatchAuthLabels = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof patchAuthLabels>>,
      TError,
      { data: RequestUpdateLabelRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof patchAuthLabels>>,
  TError,
  { data: RequestUpdateLabelRequest },
  TContext
> => {
  const mutationOptions = getPatchAuthLabelsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * API tạo label mới trong dự án
 * @summary Tạo label mới
 */
export const postAuthLabels = (
  requestCreateLabelRequest: RequestCreateLabelRequest,
  signal?: AbortSignal,
) => {
  return postAuthLabelsMutator<PostAuthLabels200>({
    url: `/auth/labels`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: requestCreateLabelRequest,
    signal,
  });
};

export const getPostAuthLabelsMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthLabels>>,
    TError,
    { data: RequestCreateLabelRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postAuthLabels>>,
  TError,
  { data: RequestCreateLabelRequest },
  TContext
> => {
  const mutationKey = ['postAuthLabels'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postAuthLabels>>,
    { data: RequestCreateLabelRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postAuthLabels(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostAuthLabelsMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthLabels>>>;
export type PostAuthLabelsMutationBody = RequestCreateLabelRequest;
export type PostAuthLabelsMutationError = unknown;

/**
 * @summary Tạo label mới
 */
export const usePostAuthLabels = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postAuthLabels>>,
      TError,
      { data: RequestCreateLabelRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postAuthLabels>>,
  TError,
  { data: RequestCreateLabelRequest },
  TContext
> => {
  const mutationOptions = getPostAuthLabelsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * API lấy danh sách các mẫu labels mặc định có thể được tạo khi khởi tạo project
 * @summary Lấy danh sách mẫu labels mặc định
 */
export const getAuthLabelsTemplates = (signal?: AbortSignal) => {
  return getAuthLabelsTemplatesMutator<GetAuthLabelsTemplates200>({
    url: `/auth/labels/templates`,
    method: 'GET',
    signal,
  });
};

export const getGetAuthLabelsTemplatesQueryKey = () => {
  return [`/auth/labels/templates`] as const;
};

export const getGetAuthLabelsTemplatesInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthLabelsTemplates>>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAuthLabelsTemplates>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAuthLabelsTemplatesQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthLabelsTemplates>>> = ({ signal }) =>
    getAuthLabelsTemplates(signal);

  return { queryKey, queryFn, staleTime: 10000, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getAuthLabelsTemplates>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAuthLabelsTemplatesInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAuthLabelsTemplates>>
>;
export type GetAuthLabelsTemplatesInfiniteQueryError = unknown;

export function useGetAuthLabelsTemplatesInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthLabelsTemplates>>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAuthLabelsTemplates>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthLabelsTemplates>>,
          TError,
          Awaited<ReturnType<typeof getAuthLabelsTemplates>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthLabelsTemplatesInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthLabelsTemplates>>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAuthLabelsTemplates>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthLabelsTemplates>>,
          TError,
          Awaited<ReturnType<typeof getAuthLabelsTemplates>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthLabelsTemplatesInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthLabelsTemplates>>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAuthLabelsTemplates>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Lấy danh sách mẫu labels mặc định
 */

export function useGetAuthLabelsTemplatesInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthLabelsTemplates>>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAuthLabelsTemplates>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAuthLabelsTemplatesInfiniteQueryOptions(options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetAuthLabelsTemplatesQueryOptions = <
  TData = Awaited<ReturnType<typeof getAuthLabelsTemplates>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof getAuthLabelsTemplates>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAuthLabelsTemplatesQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthLabelsTemplates>>> = ({ signal }) =>
    getAuthLabelsTemplates(signal);

  return { queryKey, queryFn, staleTime: 10000, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAuthLabelsTemplates>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAuthLabelsTemplatesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAuthLabelsTemplates>>
>;
export type GetAuthLabelsTemplatesQueryError = unknown;

export function useGetAuthLabelsTemplates<
  TData = Awaited<ReturnType<typeof getAuthLabelsTemplates>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthLabelsTemplates>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthLabelsTemplates>>,
          TError,
          Awaited<ReturnType<typeof getAuthLabelsTemplates>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthLabelsTemplates<
  TData = Awaited<ReturnType<typeof getAuthLabelsTemplates>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthLabelsTemplates>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthLabelsTemplates>>,
          TError,
          Awaited<ReturnType<typeof getAuthLabelsTemplates>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthLabelsTemplates<
  TData = Awaited<ReturnType<typeof getAuthLabelsTemplates>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthLabelsTemplates>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Lấy danh sách mẫu labels mặc định
 */

export function useGetAuthLabelsTemplates<
  TData = Awaited<ReturnType<typeof getAuthLabelsTemplates>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthLabelsTemplates>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAuthLabelsTemplatesQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * API lấy tất cả labels trong dự án
 * @summary Lấy danh sách labels trong dự án
 */
export const getAuthProjectsProjectIdLabels = (projectId: string, signal?: AbortSignal) => {
  return getAuthProjectsProjectIdLabelsMutator<GetAuthProjectsProjectIdLabels200>({
    url: `/auth/projects/${projectId}/labels`,
    method: 'GET',
    signal,
  });
};

export const getGetAuthProjectsProjectIdLabelsQueryKey = (projectId?: string) => {
  return [`/auth/projects/${projectId}/labels`] as const;
};

export const getGetAuthProjectsProjectIdLabelsInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthProjectsProjectIdLabels>>>,
  TError = unknown,
>(
  projectId: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getAuthProjectsProjectIdLabels>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAuthProjectsProjectIdLabelsQueryKey(projectId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthProjectsProjectIdLabels>>> = ({
    signal,
  }) => getAuthProjectsProjectIdLabels(projectId, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!projectId,
    staleTime: 10000,
    ...queryOptions,
  } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getAuthProjectsProjectIdLabels>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAuthProjectsProjectIdLabelsInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAuthProjectsProjectIdLabels>>
>;
export type GetAuthProjectsProjectIdLabelsInfiniteQueryError = unknown;

export function useGetAuthProjectsProjectIdLabelsInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthProjectsProjectIdLabels>>>,
  TError = unknown,
>(
  projectId: string,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getAuthProjectsProjectIdLabels>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthProjectsProjectIdLabels>>,
          TError,
          Awaited<ReturnType<typeof getAuthProjectsProjectIdLabels>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthProjectsProjectIdLabelsInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthProjectsProjectIdLabels>>>,
  TError = unknown,
>(
  projectId: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getAuthProjectsProjectIdLabels>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthProjectsProjectIdLabels>>,
          TError,
          Awaited<ReturnType<typeof getAuthProjectsProjectIdLabels>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthProjectsProjectIdLabelsInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthProjectsProjectIdLabels>>>,
  TError = unknown,
>(
  projectId: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getAuthProjectsProjectIdLabels>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Lấy danh sách labels trong dự án
 */

export function useGetAuthProjectsProjectIdLabelsInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthProjectsProjectIdLabels>>>,
  TError = unknown,
>(
  projectId: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getAuthProjectsProjectIdLabels>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAuthProjectsProjectIdLabelsInfiniteQueryOptions(projectId, options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetAuthProjectsProjectIdLabelsQueryOptions = <
  TData = Awaited<ReturnType<typeof getAuthProjectsProjectIdLabels>>,
  TError = unknown,
>(
  projectId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthProjectsProjectIdLabels>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAuthProjectsProjectIdLabelsQueryKey(projectId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthProjectsProjectIdLabels>>> = ({
    signal,
  }) => getAuthProjectsProjectIdLabels(projectId, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!projectId,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getAuthProjectsProjectIdLabels>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAuthProjectsProjectIdLabelsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAuthProjectsProjectIdLabels>>
>;
export type GetAuthProjectsProjectIdLabelsQueryError = unknown;

export function useGetAuthProjectsProjectIdLabels<
  TData = Awaited<ReturnType<typeof getAuthProjectsProjectIdLabels>>,
  TError = unknown,
>(
  projectId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthProjectsProjectIdLabels>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthProjectsProjectIdLabels>>,
          TError,
          Awaited<ReturnType<typeof getAuthProjectsProjectIdLabels>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthProjectsProjectIdLabels<
  TData = Awaited<ReturnType<typeof getAuthProjectsProjectIdLabels>>,
  TError = unknown,
>(
  projectId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthProjectsProjectIdLabels>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthProjectsProjectIdLabels>>,
          TError,
          Awaited<ReturnType<typeof getAuthProjectsProjectIdLabels>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthProjectsProjectIdLabels<
  TData = Awaited<ReturnType<typeof getAuthProjectsProjectIdLabels>>,
  TError = unknown,
>(
  projectId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthProjectsProjectIdLabels>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Lấy danh sách labels trong dự án
 */

export function useGetAuthProjectsProjectIdLabels<
  TData = Awaited<ReturnType<typeof getAuthProjectsProjectIdLabels>>,
  TError = unknown,
>(
  projectId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthProjectsProjectIdLabels>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAuthProjectsProjectIdLabelsQueryOptions(projectId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
