/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Beta Workspace API
 * API documentation for Beta - an integrated workspace platform that helps teams work more efficiently through a unified ecosystem: team chat, collaborative documents, email, task management, and workflow automation.
 * OpenAPI spec version: 1.0.0
 */
export interface ModelsAppLinks {
  apps?: string[];
  details?: ModelsDetail[];
}

export interface ModelsAssetLinks {
  relation?: string[];
  target?: ModelsTarget;
}

export interface ModelsBasicOrganization {
  avatar?: string;
  created_at?: string;
  description?: string;
  id?: string;
  industry?: string;
  name?: string;
  region?: string;
  size?: number;
  updated_at?: string;
}

export interface ModelsComponent {
  '#'?: string;
  comment?: string;
  exclude?: boolean;
}

export interface ModelsConfig {
  applinks?: ModelsAppLinks;
  webcredentials?: ModelsWebCredentials;
}

export interface ModelsDetail {
  appID?: string;
  components?: ModelsComponent[];
  paths?: string[];
}

export interface ModelsDueReminder {
  custom_days?: number;
  enabled?: boolean;
  /** "1day", "3days", "1week" */
  reminder_type?: string;
}

export interface ModelsLabel {
  color?: string;
  created_at?: string;
  created_by?: string;
  description?: string;
  id?: string;
  name: string;
  project_id?: string;
  updated_at?: string;
}

export interface ModelsLabelBasic {
  color?: string;
  description?: string;
  id?: string;
  name: string;
}

export interface ModelsMessage {
  content?: string;
  created_at?: string;
  id?: string;
  image_url?: string;
  room_id?: string;
  type_content?: number;
  updated_at?: string;
  user_id?: string;
}

export interface ModelsMetaData {
  organization?: ModelsBasicOrganization;
  organization_id?: string;
  project?: ModelsProject;
  project_id?: string;
}

export type ModelsOrganizationInvitationStatus =
  (typeof ModelsOrganizationInvitationStatus)[keyof typeof ModelsOrganizationInvitationStatus];

export const ModelsOrganizationInvitationStatus = {
  OrgInvitationStatusPending: 'pending',
  OrgInvitationStatusAccepted: 'accepted',
  OrgInvitationStatusExpired: 'expired',
  OrgInvitationStatusCancelled: 'cancelled',
} as const;

export interface ModelsProject {
  avatar?: string;
  created_at?: string;
  created_by?: string;
  description?: string;
  id?: string;
  is_team?: boolean;
  /** "business" for business-related initiatives,
"service_management" for managing services or operations. */
  lead?: string;
  name: string;
  organization_id?: string;
  project_type?: string;
  settings?: ModelsProjectSettings;
  status?: string;
  template_id?: string;
  updated_at?: string;
}

export type ModelsProjectMemberRole =
  (typeof ModelsProjectMemberRole)[keyof typeof ModelsProjectMemberRole];

export const ModelsProjectMemberRole = {
  ProjectMemberRoleAdmin: 'admin',
  ProjectMemberRoleSubAdmin: 'sub_admin',
  ProjectMemberRoleMember: 'member',
  ProjectMemberRoleViewer: 'viewer',
} as const;

export interface ModelsProjectSettings {
  allow_guests?: boolean;
  enable_due_dates?: boolean;
  enable_notifications?: boolean;
  enable_time_tracking?: boolean;
}

export interface ModelsS3Object {
  created_at?: string;
  id?: string;
  key: string;
  mime: string;
  updated_at?: string;
  url: string;
  user_id: string;
}

export interface ModelsSprint {
  begin_at: string;
  created_at?: string;
  created_by?: string;
  end_at: string;
  id?: string;
  is_active?: boolean;
  project_id: string;
  sprint_goal?: string;
  sprint_name: string;
  updated_at?: string;
  updated_by?: string;
}

export interface ModelsSprintBasic {
  begin_at: string;
  end_at: string;
  id?: string;
  is_active?: boolean;
  name: string;
  project_id: string;
}

export interface ModelsTarget {
  namespace?: string;
  package_name?: string;
  sha256_cert_fingerprints?: string[];
}

export interface ModelsTask {
  assignee?: string;
  board_position?: number;
  checkpoint?: number;
  completed?: boolean;
  completed_at?: string;
  created_at?: string;
  created_by?: string;
  /** days */
  cycle_time?: number;
  description?: string;
  due_date?: string;
  due_reminder?: ModelsDueReminder;
  id?: string;
  labels?: string[];
  /** days */
  lead_time?: number;
  list_id?: string;
  parent_task_id?: string;
  position?: number;
  priority?: ModelsTaskPriority;
  project_id?: string;
  reporter?: string;
  sprint_id?: string;
  start_date?: string;
  started_at?: string;
  swimlane_priority?: number;
  title: string;
  updated_at?: string;
}

export interface ModelsTaskListBasic {
  color?: string;
  id?: string;
  name: string;
  position?: number;
}

export type ModelsTaskPriority = (typeof ModelsTaskPriority)[keyof typeof ModelsTaskPriority];

export const ModelsTaskPriority = {
  TaskPriorityHigh: 'high',
  TaskPriorityMedium: 'medium',
  TaskPriorityLow: 'low',
} as const;

export interface ModelsUser {
  address?: string;
  colour?: string;
  created_at?: string;
  date_of_birth?: string;
  email: string;
  email_verified?: string;
  full_name?: string;
  gender?: number;
  id?: string;
  meta_data?: ModelsMetaData;
  phone_number: string;
  profile_image?: string;
  role?: ModelsUserRole;
  token_device?: string;
  updated_at?: string;
}

export type ModelsUserRole = (typeof ModelsUserRole)[keyof typeof ModelsUserRole];

export const ModelsUserRole = {
  UserRoleUser: 'user',
  UserRoleAdmin: 'admin',
} as const;

export interface ModelsWebCredentials {
  apps?: string[];
}

export interface RequestActiveNextSprintRequest {
  project_id: string;
  sprint_id: string;
}

export type RequestAddProjectMemberRequestRole =
  (typeof RequestAddProjectMemberRequestRole)[keyof typeof RequestAddProjectMemberRequestRole];

export const RequestAddProjectMemberRequestRole = {
  member: 'member',
  viewer: 'viewer',
} as const;

export interface RequestAddProjectMemberRequest {
  project_id: string;
  role: RequestAddProjectMemberRequestRole;
  user_id: string;
}

export interface RequestChangePasswordRequest {
  new_password?: string;
  old_password?: string;
}

export interface RequestCreateLabelDataToCreate {
  color?: string;
  description?: string;
  name: string;
}

export interface RequestCreateLabelRequest {
  color?: string;
  description?: string;
  name: string;
  project_id: string;
}

export interface RequestCreateMessageRequest {
  /** Maximum 2000 characters */
  content: number[];
  image_url?: string;
  type_content: number;
}

export interface RequestCreateOrganizationRequest {
  avatar?: string;
  description?: string;
  industry?: string;
  name: string;
  region?: string;
  size?: number;
}

export interface RequestCreateProjectRequest {
  avatar?: string;
  description?: string;
  is_team?: boolean;
  labels?: RequestCreateLabelDataToCreate[];
  lead?: string;
  members?: string[];
  name: string;
  org_id: string;
  project_type?: string;
  settings?: RequestProjectSettingsRequest;
  sprints: RequestCreateSprintRequest[];
  task_list: RequestTaskListDataToCreate[];
  template_id?: string;
}

export interface RequestCreateSprintRequest {
  begin_at: string;
  end_at: string;
  goal?: string;
  is_active?: boolean;
  name: string;
  project_id?: string;
}

export interface RequestCreateTaskCommentRequest {
  content: string;
  mentions?: string[];
  parent_id?: string;
  project_id: string;
  task_id: string;
}

export interface RequestCreateTaskListRequest {
  color?: string;
  description?: string;
  name: string;
  position?: number;
  project_id: string;
}

export type RequestCreateTaskRequestPriority =
  (typeof RequestCreateTaskRequestPriority)[keyof typeof RequestCreateTaskRequestPriority];

export const RequestCreateTaskRequestPriority = {
  low: 'low',
  medium: 'medium',
  high: 'high',
} as const;

export interface RequestCreateTaskRequest {
  assignee?: string;
  checkpoint?: number;
  completed_at?: string;
  description?: string;
  due_date?: string;
  due_reminder?: RequestDueReminderRequest;
  labels?: string[];
  list_id: string;
  parent_task_id?: string;
  priority?: RequestCreateTaskRequestPriority;
  project_id: string;
  sprint_id: string;
  start_date?: string;
  title: string;
}

export interface RequestDeleteLabelRequest {
  label_id: string;
  project_id?: string;
}

export interface RequestDeleteMemberInOrgRequest {
  member_id: string;
  org_id: string;
}

export interface RequestDeleteMultipleTasksRequest {
  task_ids: string[];
}

export interface RequestDeleteSprintRequest {
  project_id: string;
  sprint_id: string;
}

export interface RequestDeleteTaskCommentRequest {
  comment_id: string;
  project_id: string;
  task_id: string;
}

export interface RequestDeleteTaskListRequest {
  project_id?: string;
  task_list_id: string;
}

export interface RequestDueReminderRequest {
  custom_days?: number;
  enabled?: boolean;
  /** "1day", "3days", "1week", "custom" */
  reminder_type?: string;
}

export interface RequestForgotPasswordRequest {
  email?: string;
  new_password?: string;
  step?: number;
  verify_code?: string;
}

export interface RequestInviteMemberRequest {
  email: string;
  org_id: string;
}

export interface RequestJoinOrganizationRequest {
  invite_code: string;
}

export interface RequestLaunchOrganizationRequest {
  org_id: string;
}

export interface RequestLaunchProjectRequest {
  org_id: string;
  project_id: string;
}

export interface RequestLoginRequest {
  email: string;
  password: string;
}

export interface RequestMoveTaskRequest {
  target_list_id: string;
  target_position: number;
}

export interface RequestProjectSettingsRequest {
  allow_guests?: boolean;
  enable_due_dates?: boolean;
  enable_notifications?: boolean;
  enable_time_tracking?: boolean;
}

export interface RequestRegisterDeviceRequest {
  token_device?: string;
}

export interface RequestRegisterRequest {
  email: string;
  full_name?: string;
  password?: string;
  /**
   * @minimum 1
   * @maximum 3
   */
  step: number;
  verify_code?: string;
}

export interface RequestRoomRequest {
  members?: string[];
  name?: string;
  organization_id?: string;
  type_of_room?: number;
}

export interface RequestSubscribeTaskRequest {
  project_id: string;
  task_id: string;
}

export interface RequestTaskListDataToCreate {
  color?: string;
  description?: string;
  is_default?: boolean;
  name: string;
  position?: number;
}

export interface RequestUnSubscribeTaskRequest {
  project_id: string;
  task_id: string;
}

export interface RequestUpdateLabelRequest {
  color?: string;
  description?: string;
  label_id: string;
  name?: string;
  project_id: string;
}

export type RequestUpdateMemberRoleRequestRole =
  (typeof RequestUpdateMemberRoleRequestRole)[keyof typeof RequestUpdateMemberRoleRequestRole];

export const RequestUpdateMemberRoleRequestRole = {
  admin: 'admin',
  sub_admin: 'sub_admin',
  member: 'member',
} as const;

export interface RequestUpdateMemberRoleRequest {
  org_id: string;
  role: RequestUpdateMemberRoleRequestRole;
  user_id: string;
}

export interface RequestUpdateOrganizationRequest {
  avatar?: string;
  description?: string;
  industry?: string;
  name?: string;
  org_id?: string;
  region?: string;
  size?: number;
}

export interface RequestUpdateProfileRequest {
  address?: string;
  colour?: string;
  date_of_birth?: string;
  full_name?: string;
  gender?: number;
  phone_number?: string;
  profile_image?: string;
}

export type RequestUpdateProjectMemberRoleRequestRole =
  (typeof RequestUpdateProjectMemberRoleRequestRole)[keyof typeof RequestUpdateProjectMemberRoleRequestRole];

export const RequestUpdateProjectMemberRoleRequestRole = {
  member: 'member',
  viewer: 'viewer',
  sub_admin: 'sub_admin',
} as const;

export interface RequestUpdateProjectMemberRoleRequest {
  project_id: string;
  role: RequestUpdateProjectMemberRoleRequestRole;
  user_id: string;
}

export interface RequestUpdateProjectRequest {
  avatar?: string;
  description?: string;
  lead?: string;
  name?: string;
  project_id?: string;
  project_type?: string;
  settings?: RequestProjectSettingsRequest;
  status?: string;
}

export interface RequestUpdateSprintRequest {
  begin_at?: string;
  end_at?: string;
  project_id: string;
  sprint_goal?: string;
  sprint_id: string;
  sprint_name?: string;
}

export interface RequestUpdateTaskListRequest {
  color?: string;
  description?: string;
  is_default?: boolean;
  name?: string;
  position?: number;
  project_id: string;
  task_list_id: string;
}

export type RequestUpdateTaskRequestPriority =
  (typeof RequestUpdateTaskRequestPriority)[keyof typeof RequestUpdateTaskRequestPriority];

export const RequestUpdateTaskRequestPriority = {
  low: 'low',
  medium: 'medium',
  high: 'high',
} as const;

export interface RequestUpdateTaskRequest {
  assignee?: string;
  /** @minimum 0 */
  checkpoint?: number;
  completed_at?: string;
  description?: string;
  due_date?: string;
  due_reminder?: ModelsDueReminder;
  labels?: string[];
  list_id?: string;
  /** @minimum 1 */
  position?: number;
  priority?: RequestUpdateTaskRequestPriority;
  project_id: string;
  sprint_id: string;
  start_date?: string;
  task_id: string;
  title?: string;
}

export type ResponseActivityLogResponseDetails = { [key: string]: unknown };

export interface ResponseActivityLogResponse {
  action?: string;
  created_at?: string;
  details?: ResponseActivityLogResponseDetails;
  id?: string;
  project_id?: string;
  target_id?: string;
  target_type?: string;
  user?: ResponseUserBasicInfo;
}

export interface ResponseDeleteMultipleTasksResponse {
  deleted_task_ids?: string[];
  failed_task_ids?: string[];
  total_deleted?: number;
  total_failed?: number;
  total_requested?: number;
}

export interface ResponseDirectMessageAndRoomResponse {
  message?: ResponseMessageResponse[];
  room?: ResponseRoomResponse;
}

export interface ResponseDueReminderResponse {
  custom_days?: number;
  enabled?: boolean;
  reminder_type?: string;
}

export interface ResponseGetMembersInOrgResponse {
  members?: ResponseOrgMember[];
  total?: number;
}

export interface ResponseGetProjectMembersResponse {
  members?: ResponseMembersWithProjectMemberRole[];
  total?: number;
}

export interface ResponseGetUserInfoResponse {
  colour?: string;
  created_at?: string;
  email?: string;
  full_name?: string;
  meta_data?: ModelsMetaData;
  phone_number?: string;
  profile_image?: string;
  updated_at?: string;
  id?: string;
}

export interface ResponseGetUserOrgsResponse {
  /** ✅ Changed */
  organizations?: ResponseUserOrgMembership[];
  total?: number;
}

export interface ResponseGetUserProjectsResponse {
  projects?: ResponseProjectsWithProjectMemberRole[];
  total?: number;
}

export interface ResponseKanbanBoardResponse {
  labels?: string[];
  lists?: ResponseTaskListWithTasksResponse[];
  members?: ResponseProjectMemberResponse[];
  priorities?: string[];
  project?: ResponseProjectResponse;
}

export interface ResponseLabelResponse {
  data?: ModelsLabel[];
  total?: number;
}

export interface ResponseLabelShort {
  color?: string;
  id?: string;
  name?: string;
}

export interface ResponseLoginResponse {
  token?: string;
  user?: ModelsUser;
}

export interface ResponseMembersWithProjectMemberRole {
  member?: ModelsUser;
  role?: ModelsProjectMemberRole;
}

export interface ResponseMessageResponse {
  content?: string;
  created_at?: string;
  id?: string;
  image_url?: string;
  type_content?: number;
  updated_at?: string;
  user?: ResponseUserResponse;
}

export interface ResponseOrgMember {
  address?: string;
  colour?: string;
  created_at?: string;
  date_of_birth?: string;
  email: string;
  email_verified?: string;
  full_name?: string;
  gender?: number;
  id?: string;
  meta_data?: ModelsMetaData;
  phone_number: string;
  profile_image?: string;
  role?: ModelsUserRole;
  roles?: string[];
  token_device?: string;
  updated_at?: string;
}

export interface ResponseOrganizationInvitationResponse {
  created_at?: string;
  email?: string;
  expires_at?: string;
  id?: string;
  invite_code?: string;
  organization_id?: string;
  status?: ModelsOrganizationInvitationStatus;
}

export interface ResponseOrganizationMemberResponse {
  id?: string;
  invited_by?: string;
  joined_at?: string;
  organization_id?: string;
  role?: string[];
  user_avatar?: string;
  user_email?: string;
  user_id?: string;
  user_name?: string;
}

export interface ResponseOrganizationResponse {
  admin_count?: number;
  avatar?: string;
  created_at?: string;
  description?: string;
  id?: string;
  industry?: string;
  member_count?: number;
  name?: string;
  region?: string;
  size?: number;
  sub_admin_count?: number;
  updated_at?: string;
}

export interface ResponseProjectBasicWithLeader {
  avatar?: string;
  created_at?: string;
  created_by?: string;
  description?: string;
  id?: string;
  lead?: ResponseUserBasicInfo;
  name: string;
  organization_id?: string;
  project_type?: string;
  status?: string;
  updated_at?: string;
}

export interface ResponseProjectDashboardResponse {
  project?: ResponseProjectResponse;
  recent_activity?: ResponseActivityLogResponse[];
  tasks_summary?: ResponseTasksSummaryResponse;
  team_activity?: ResponseTeamActivityResponse[];
  upcoming_deadlines?: ResponseTaskResponse[];
}

export interface ResponseProjectMemberResponse {
  created_by?: ResponseUserBasicInfo;
  id?: string;
  joined_at?: string;
  project_id?: string;
  role?: ModelsProjectMemberRole;
  user?: ResponseUserBasicInfo;
}

export interface ResponseProjectResponse {
  avatar?: string;
  created_at?: string;
  created_by?: string;
  description?: string;
  id?: string;
  is_team?: boolean;
  lead?: string;
  name?: string;
  organization_id?: string;
  project_type?: string;
  settings?: ResponseProjectSettingsResponse;
  status?: string;
  template_id?: string;
  updated_at?: string;
}

export interface ResponseProjectSettingsResponse {
  allow_guests?: boolean;
  enable_due_dates?: boolean;
  enable_notifications?: boolean;
  enable_time_tracking?: boolean;
}

export interface ResponseProjectStatisticBasic {
  completed_tasks?: number;
  created_at?: string;
  id?: string;
  overdue_tasks?: number;
  project_id?: string;
  total_members?: number;
  total_tasks?: number;
  updated_at?: string;
}

export interface ResponseProjectWithColLabelAndSprint {
  columns?: ModelsTaskListBasic[];
  labels?: ModelsLabelBasic[];
  lead?: ResponseUserBasicInfo;
  project?: ModelsProject;
  sprint_active?: ModelsSprintBasic;
}

export interface ResponseProjectsWithProjectMemberRole {
  project?: ResponseProjectBasicWithLeader;
  role?: ModelsProjectMemberRole;
  statistic?: ResponseProjectStatisticBasic;
}

export interface ResponseResponse {
  code?: string;
  data?: unknown;
  message?: string;
}

export interface ResponseRoomResponse {
  created_at?: string;
  has_notification?: boolean;
  id?: string;
  latest_messages?: ModelsMessage;
  members?: ModelsUser[];
  name?: string;
  type_of_room?: number;
  updated_at?: string;
}

export interface ResponseTaskAndSubTasks {
  sub_tasks?: ResponseTaskWithRelations[];
  task?: ResponseTaskWithRelations;
}

export interface ResponseTaskCommentResponse {
  author?: ResponseUserBasicInfo;
  comment_task_id?: string;
  content?: string;
  created_at?: string;
  id?: string;
  mentions?: string[];
  parent_id?: string;
  updated_at?: string;
}

export interface ResponseTaskListResponse {
  color?: string;
  created_at?: string;
  created_by?: string;
  description?: string;
  id?: string;
  is_default?: boolean;
  name?: string;
  position?: number;
  project_id?: string;
  tasks_count?: number;
  updated_at?: string;
}

export interface ResponseTaskListWithTasksResponse {
  list?: ResponseTaskListResponse;
  tasks?: ResponseTaskResponse[];
}

export interface ResponseTaskParentShort {
  completed?: boolean;
  id?: string;
  priority?: ModelsTaskPriority;
  title?: string;
}

export interface ResponseTaskResponse {
  assignee?: ResponseUserBasicInfo;
  attachments_count?: number;
  board_position?: number;
  comments_count?: number;
  completed?: boolean;
  completed_at?: string;
  created_at?: string;
  created_by?: ResponseUserBasicInfo;
  cycle_time?: number;
  description?: string;
  due_date?: string;
  due_reminder?: ResponseDueReminderResponse;
  id?: string;
  labels?: string[];
  lead_time?: number;
  list_id?: string;
  parent_task_id?: string;
  position?: number;
  priority?: string;
  project_id?: string;
  reporter?: ResponseUserBasicInfo;
  start_date?: string;
  started_at?: string;
  status?: string;
  subscribers_count?: number;
  swimlane_priority?: number;
  title?: string;
  updated_at?: string;
}

export interface ResponseTaskSearchResponse {
  page?: number;
  page_size?: number;
  tasks?: ResponseTaskResponse[];
  total?: number;
  total_pages?: number;
}

export interface ResponseTaskWithRelations {
  assignee?: ResponseUserBasicInfo;
  board_position?: number;
  completed?: boolean;
  completed_at?: string;
  created_at?: string;
  created_by?: ResponseUserBasicInfo;
  cycle_time?: number;
  description?: string;
  due_date?: string;
  due_reminder?: unknown;
  id?: string;
  labels?: ResponseLabelShort[];
  lead_time?: number;
  list_id?: string;
  parent_task?: ResponseTaskParentShort;
  position?: number;
  priority?: string;
  project_id?: string;
  reporter?: ResponseUserBasicInfo;
  start_date?: string;
  swimlane_priority?: number;
  title?: string;
  updated_at?: string;
}

export interface ResponseTasksSummaryResponse {
  completed?: number;
  in_progress?: number;
  overdue?: number;
  pending?: number;
  total?: number;
}

export interface ResponseTeamActivityResponse {
  last_activity?: string;
  tasks_completed?: number;
  tasks_created?: number;
  user?: ResponseUserBasicInfo;
}

export interface ResponseUserBasicInfo {
  colour?: string;
  email?: string;
  full_name?: string;
  id?: string;
  profile_image?: string;
}

export interface ResponseUserOrgMembership {
  joined_at?: string;
  organization?: ModelsBasicOrganization;
  roles?: string[];
}

export interface ResponseUserResponse {
  colour?: string;
  email?: string;
  full_name?: string;
  id?: string;
  profile_image?: string;
}

export type GetAuthDownloadParams = {
  /**
   * Object S3 ID
   */
  object_id?: string;
  /**
   * Object S3 key
   */
  object_key?: string;
};

export type PostAuthFileUploadBody = {
  /**  File data  */
  file: Blob;
};

export type PostAuthFileUpload201AllOf = {
  data?: ModelsS3Object;
};

export type PostAuthFileUpload201 = ResponseResponse & PostAuthFileUpload201AllOf;

export type GetAuthGoogleCallbackParams = {
  /**
   * OAuth authorization code
   */
  code: string;
  /**
   * OAuth state parameter
   */
  state?: string;
};

export type GetAuthGoogleCallback200AllOf = {
  data?: ResponseLoginResponse;
};

export type GetAuthGoogleCallback200 = ResponseResponse & GetAuthGoogleCallback200AllOf;

export type PatchAuthLabels200AllOf = {
  data?: ResponseLabelResponse;
};

export type PatchAuthLabels200 = ResponseResponse & PatchAuthLabels200AllOf;

export type PostAuthLabels200AllOf = {
  data?: ResponseLabelResponse;
};

export type PostAuthLabels200 = ResponseResponse & PostAuthLabels200AllOf;

export type GetAuthLabelsTemplates200AllOfDataItem = { [key: string]: string };

export type GetAuthLabelsTemplates200AllOf = {
  data?: GetAuthLabelsTemplates200AllOfDataItem[];
};

export type GetAuthLabelsTemplates200 = ResponseResponse & GetAuthLabelsTemplates200AllOf;

export type GetAuthOrganizationsParams = {
  /**
   * Số trang
   */
  page?: number;
  /**
   * Kích thước trang
   */
  page_size?: number;
};

export type GetAuthOrganizations200AllOf = {
  data?: ResponseGetUserOrgsResponse;
};

export type GetAuthOrganizations200 = ResponseResponse & GetAuthOrganizations200AllOf;

export type PatchAuthOrganizations200AllOf = {
  data?: ResponseOrganizationResponse;
};

export type PatchAuthOrganizations200 = ResponseResponse & PatchAuthOrganizations200AllOf;

export type PostAuthOrganizations201AllOf = {
  data?: ResponseOrganizationResponse;
};

export type PostAuthOrganizations201 = ResponseResponse & PostAuthOrganizations201AllOf;

export type GetAuthOrganizationsOrgId200AllOf = {
  data?: ResponseOrganizationResponse;
};

export type GetAuthOrganizationsOrgId200 = ResponseResponse & GetAuthOrganizationsOrgId200AllOf;

export type GetAuthOrganizationsOrgIdMembersParams = {
  /**
   * Số trang
   */
  page?: number;
  /**
   * Kích thước trang
   */
  page_size?: number;
  /**
   * Tên thành viên
   */
  name?: string;
  /**
   * Số điện thoại
   */
  phone_number?: string;
  /**
   * Email
   */
  email?: string;
};

export type GetAuthOrganizationsOrgIdMembers200AllOf = {
  data?: ResponseGetMembersInOrgResponse;
};

export type GetAuthOrganizationsOrgIdMembers200 = ResponseResponse &
  GetAuthOrganizationsOrgIdMembers200AllOf;

export type PostAuthOrganizationsInvite201AllOf = {
  data?: ResponseOrganizationInvitationResponse;
};

export type PostAuthOrganizationsInvite201 = ResponseResponse & PostAuthOrganizationsInvite201AllOf;

export type PostAuthOrganizationsJoin200AllOf = {
  data?: ResponseOrganizationMemberResponse;
};

export type PostAuthOrganizationsJoin200 = ResponseResponse & PostAuthOrganizationsJoin200AllOf;

export type PostAuthOrganizationsLaunch200AllOf = {
  data?: ModelsBasicOrganization;
};

export type PostAuthOrganizationsLaunch200 = ResponseResponse & PostAuthOrganizationsLaunch200AllOf;

export type PostAuthProjects200AllOf = {
  data?: ResponseProjectResponse;
};

export type PostAuthProjects200 = ResponseResponse & PostAuthProjects200AllOf;

export type GetAuthProjectsProjectId200AllOf = {
  data?: ResponseProjectWithColLabelAndSprint;
};

export type GetAuthProjectsProjectId200 = ResponseResponse & GetAuthProjectsProjectId200AllOf;

export type PatchAuthProjectsProjectId200AllOf = {
  data?: ResponseProjectResponse;
};

export type PatchAuthProjectsProjectId200 = ResponseResponse & PatchAuthProjectsProjectId200AllOf;

export type GetAuthProjectsProjectIdDashboard200AllOf = {
  data?: ResponseProjectDashboardResponse;
};

export type GetAuthProjectsProjectIdDashboard200 = ResponseResponse &
  GetAuthProjectsProjectIdDashboard200AllOf;

export type GetAuthProjectsProjectIdKanban200AllOf = {
  data?: ResponseKanbanBoardResponse;
};

export type GetAuthProjectsProjectIdKanban200 = ResponseResponse &
  GetAuthProjectsProjectIdKanban200AllOf;

export type GetAuthProjectsProjectIdLabels200AllOf = {
  data?: ResponseLabelResponse[];
};

export type GetAuthProjectsProjectIdLabels200 = ResponseResponse &
  GetAuthProjectsProjectIdLabels200AllOf;

export type GetAuthProjectsProjectIdMembersParams = {
  email?: string;
  name?: string;
  /**
   * @minimum 1
   */
  page?: number;
  /**
   * @minimum 1
   * @maximum 100
   */
  page_size?: number;
  phone_number?: string;
  role?: GetAuthProjectsProjectIdMembersRole;
};

export type GetAuthProjectsProjectIdMembersRole =
  (typeof GetAuthProjectsProjectIdMembersRole)[keyof typeof GetAuthProjectsProjectIdMembersRole];

export const GetAuthProjectsProjectIdMembersRole = {
  admin: 'admin',
  sub_admin: 'sub_admin',
  member: 'member',
  viewer: 'viewer',
} as const;

export type GetAuthProjectsProjectIdMembers200AllOf = {
  data?: ResponseGetProjectMembersResponse;
};

export type GetAuthProjectsProjectIdMembers200 = ResponseResponse &
  GetAuthProjectsProjectIdMembers200AllOf;

export type GetAuthProjectsProjectIdTasksParams = {
  /**
   * Sprint ID
   */
  sprint_id?: string;
  /**
   * Danh sách List ID
   */
  list_id?: string[];
  /**
   * Tiêu đề task
   */
  title?: string;
  /**
   * Danh sách Assignee ID
   */
  assignee?: string[];
  /**
   * Danh sách Priority
   */
  priority?: string[];
  /**
   * Reporter ID
   */
  reporter?: string;
  /**
   * Danh sách Label ID
   */
  label?: string[];
  /**
   * Ngày bắt đầu (dd/MM/yyyy)
   */
  start_date?: string;
  /**
   * Ngày hết hạn (dd/MM/yyyy)
   */
  due_date?: string;
  /**
   * Người tạo
   */
  created_by?: string;
  /**
   * Page number
   */
  page?: number;
  /**
   * Page size
   */
  page_size?: number;
};

export type GetAuthProjectsProjectIdTasks200AllOf = {
  data?: ResponseTaskSearchResponse;
};

export type GetAuthProjectsProjectIdTasks200 = ResponseResponse &
  GetAuthProjectsProjectIdTasks200AllOf;

export type PostAuthProjectsLaunch200AllOf = {
  data?: ResponseProjectResponse;
};

export type PostAuthProjectsLaunch200 = ResponseResponse & PostAuthProjectsLaunch200AllOf;

export type PostAuthProjectsMembers200AllOf = {
  data?: ResponseProjectMemberResponse;
};

export type PostAuthProjectsMembers200 = ResponseResponse & PostAuthProjectsMembers200AllOf;

export type GetAuthProjectsMyProjectsOrgIdParams = {
  is_team?: boolean;
  name?: string;
  /**
   * @minimum 1
   */
  page?: number;
  /**
   * @minimum 1
   * @maximum 100
   */
  page_size?: number;
  project_type?: GetAuthProjectsMyProjectsOrgIdProjectType;
  role?: GetAuthProjectsMyProjectsOrgIdRole;
  status?: GetAuthProjectsMyProjectsOrgIdStatus;
};

export type GetAuthProjectsMyProjectsOrgIdProjectType =
  (typeof GetAuthProjectsMyProjectsOrgIdProjectType)[keyof typeof GetAuthProjectsMyProjectsOrgIdProjectType];

export const GetAuthProjectsMyProjectsOrgIdProjectType = {
  internal: 'internal',
  external: 'external',
} as const;

export type GetAuthProjectsMyProjectsOrgIdRole =
  (typeof GetAuthProjectsMyProjectsOrgIdRole)[keyof typeof GetAuthProjectsMyProjectsOrgIdRole];

export const GetAuthProjectsMyProjectsOrgIdRole = {
  admin: 'admin',
  sub_admin: 'sub_admin',
  member: 'member',
  viewer: 'viewer',
} as const;

export type GetAuthProjectsMyProjectsOrgIdStatus =
  (typeof GetAuthProjectsMyProjectsOrgIdStatus)[keyof typeof GetAuthProjectsMyProjectsOrgIdStatus];

export const GetAuthProjectsMyProjectsOrgIdStatus = {
  active: 'active',
  inactive: 'inactive',
  archived: 'archived',
} as const;

export type GetAuthProjectsMyProjectsOrgId200AllOf = {
  data?: ResponseGetUserProjectsResponse;
};

export type GetAuthProjectsMyProjectsOrgId200 = ResponseResponse &
  GetAuthProjectsMyProjectsOrgId200AllOf;

export type PostAuthRegister200AllOfData = { [key: string]: string };

export type PostAuthRegister200AllOf = {
  data?: PostAuthRegister200AllOfData;
};

export type PostAuthRegister200 = ResponseResponse & PostAuthRegister200AllOf;

export type PostAuthRoom200AllOf = {
  data?: ResponseRoomResponse;
};

export type PostAuthRoom200 = ResponseResponse & PostAuthRoom200AllOf;

export type PostAuthRoom201AllOf = {
  data?: ResponseRoomResponse;
};

export type PostAuthRoom201 = ResponseResponse & PostAuthRoom201AllOf;

export type GetAuthRoomCircleIdParams = {
  /**
   * Page
   */
  page: number;
  /**
   * PageSize
   */
  page_size: number;
};

export type GetAuthRoomCircleId200AllOf = {
  data?: ResponseRoomResponse[];
};

export type GetAuthRoomCircleId200 = ResponseResponse & GetAuthRoomCircleId200AllOf;

export type PatchAuthRoomRoomId200AllOf = {
  data?: ResponseRoomResponse[];
};

export type PatchAuthRoomRoomId200 = ResponseResponse & PatchAuthRoomRoomId200AllOf;

export type PatchAuthTaskLists200AllOf = {
  data?: ResponseTaskListResponse;
};

export type PatchAuthTaskLists200 = ResponseResponse & PatchAuthTaskLists200AllOf;

export type PostAuthTaskLists200AllOf = {
  data?: ResponseTaskListResponse;
};

export type PostAuthTaskLists200 = ResponseResponse & PostAuthTaskLists200AllOf;

export type GetAuthTaskListsProjectId200AllOf = {
  data?: ResponseTaskListResponse[];
};

export type GetAuthTaskListsProjectId200 = ResponseResponse & GetAuthTaskListsProjectId200AllOf;

export type PostAuthTasks200AllOf = {
  data?: ModelsTask;
};

export type PostAuthTasks200 = ResponseResponse & PostAuthTasks200AllOf;

export type GetAuthTasksTaskId200AllOf = {
  data?: ResponseTaskAndSubTasks;
};

export type GetAuthTasksTaskId200 = ResponseResponse & GetAuthTasksTaskId200AllOf;

export type PutAuthTasksTaskId200AllOf = {
  data?: ModelsTask;
};

export type PutAuthTasksTaskId200 = ResponseResponse & PutAuthTasksTaskId200AllOf;

export type PutAuthTasksTaskIdMove200AllOf = {
  data?: ResponseTaskResponse;
};

export type PutAuthTasksTaskIdMove200 = ResponseResponse & PutAuthTasksTaskIdMove200AllOf;

export type DeleteAuthTasksBatchDelete200AllOf = {
  data?: ResponseDeleteMultipleTasksResponse;
};

export type DeleteAuthTasksBatchDelete200 = ResponseResponse & DeleteAuthTasksBatchDelete200AllOf;

export type GetAuthTasksCommentsParams = {
  /**
   * @minimum 1
   */
  page?: number;
  /**
   * @minimum 1
   * @maximum 100
   */
  page_size?: number;
  parentID?: string;
  taskID: string;
};

export type GetAuthTasksComments200AllOf = {
  data?: ResponseTaskCommentResponse[];
};

export type GetAuthTasksComments200 = ResponseResponse & GetAuthTasksComments200AllOf;

export type PostAuthTasksComments200AllOf = {
  data?: ResponseTaskCommentResponse;
};

export type PostAuthTasksComments200 = ResponseResponse & PostAuthTasksComments200AllOf;

export type GetAuthUserProfile200AllOf = {
  data?: ResponseGetUserInfoResponse;
};

export type GetAuthUserProfile200 = ResponseResponse & GetAuthUserProfile200AllOf;

export type PatchAuthUserProfile200AllOf = {
  data?: ModelsUser;
};

export type PatchAuthUserProfile200 = ResponseResponse & PatchAuthUserProfile200AllOf;

export type GetChatRoomIdParams = {
  /**
   * Page
   */
  page: number;
  /**
   * PageSize
   */
  page_size: number;
};

export type GetChatRoomId200AllOf = {
  data?: ResponseDirectMessageAndRoomResponse;
};

export type GetChatRoomId200 = ResponseResponse & GetChatRoomId200AllOf;

export type PostLogin200AllOfData = { [key: string]: string };

export type PostLogin200AllOf = {
  data?: PostLogin200AllOfData;
};

export type PostLogin200 = ResponseResponse & PostLogin200AllOf;

export type GetNotificationsParams = {
  /**
   * Số trang
   */
  page?: number;
  /**
   * Kích thước trang
   */
  page_size?: number;
  /**
   * Tiêu đề thông báo (tìm kiếm gần đúng, không phân biệt hoa thường)
   */
  title?: string;
  /**
   * Trạng thái đã đọc (true: đã đọc, false: chưa đọc)
   */
  is_read?: boolean;
  /**
   * ID người gửi
   */
  sender?: string;
  /**
   * Ngày bắt đầu (định dạng: YYYY-MM-DD)
   */
  from_date?: string;
  /**
   * Ngày kết thúc (định dạng: YYYY-MM-DD)
   */
  to_date?: string;
};

export type PostSprints200AllOf = {
  data?: ModelsSprint;
};

export type PostSprints200 = ResponseResponse & PostSprints200AllOf;

export type GetSprintsProjectIdParams = {
  /**
   * Page number
   */
  page?: number;
  /**
   * Number of items per page
   */
  page_size?: number;
};

export type GetSprintsProjectId200AllOf = {
  data?: ModelsSprint[];
};

export type GetSprintsProjectId200 = ResponseResponse & GetSprintsProjectId200AllOf;
