/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Beta Workspace API
 * API documentation for Beta - an integrated workspace platform that helps teams work more efficiently through a unified ecosystem: team chat, collaborative documents, email, task management, and workflow automation.
 * OpenAPI spec version: 1.0.0
 */
export interface ModelsAppLinks {
  apps?: string[];
  details?: ModelsDetail[];
}

export interface ModelsAssetLinks {
  relation?: string[];
  target?: ModelsTarget;
}

export interface ModelsComponent {
  '#'?: string;
  comment?: string;
  exclude?: boolean;
}

export interface ModelsConfig {
  applinks?: ModelsAppLinks;
  webcredentials?: ModelsWebCredentials;
}

export interface ModelsDetail {
  appID?: string;
  components?: ModelsComponent[];
  paths?: string[];
}

export interface ModelsMessage {
  content?: string;
  created_at?: string;
  id?: string;
  image_url?: string;
  room_id?: string;
  type_content?: number;
  updated_at?: string;
  user_id?: string;
}

export type ModelsOrganizationInvitationStatus =
  (typeof ModelsOrganizationInvitationStatus)[keyof typeof ModelsOrganizationInvitationStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ModelsOrganizationInvitationStatus = {
  OrgInvitationStatusPending: 'pending',
  OrgInvitationStatusAccepted: 'accepted',
  OrgInvitationStatusExpired: 'expired',
  OrgInvitationStatusCancelled: 'cancelled',
} as const;

export type ModelsOrganizationRole =
  (typeof ModelsOrganizationRole)[keyof typeof ModelsOrganizationRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ModelsOrganizationRole = {
  OrgRoleAdmin: 'admin',
  OrgRoleSubAdmin: 'sub_admin',
  OrgRoleMember: 'member',
} as const;

export type ModelsProjectMemberRole =
  (typeof ModelsProjectMemberRole)[keyof typeof ModelsProjectMemberRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ModelsProjectMemberRole = {
  ProjectMemberRoleAdmin: 'admin',
  ProjectMemberRoleSubAdmin: 'sub_admin',
  ProjectMemberRoleMember: 'member',
  ProjectMemberRoleViewer: 'viewer',
} as const;

export interface ModelsS3Object {
  created_at?: string;
  id?: string;
  key: string;
  mime: string;
  updated_at?: string;
  url: string;
  user_id: string;
}

export interface ModelsTarget {
  namespace?: string;
  package_name?: string;
  sha256_cert_fingerprints?: string[];
}

export type ModelsTaskPriority = (typeof ModelsTaskPriority)[keyof typeof ModelsTaskPriority];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ModelsTaskPriority = {
  TaskPriorityHigh: 'high',
  TaskPriorityMedium: 'medium',
  TaskPriorityLow: 'low',
} as const;

export interface ModelsUser {
  address?: string;
  colour?: string;
  created_at?: string;
  date_of_birth?: string;
  email: string;
  email_verified?: string;
  full_name?: string;
  gender?: number;
  id?: string;
  is_online?: boolean;
  password: string;
  phone_number: string;
  profile_image?: string;
  role?: ModelsUserRole;
  token_device?: string;
  updated_at?: string;
}

export type ModelsUserRole = (typeof ModelsUserRole)[keyof typeof ModelsUserRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ModelsUserRole = {
  UserRoleUser: 'user',
  UserRoleAdmin: 'admin',
} as const;

export interface ModelsWebCredentials {
  apps?: string[];
}

export interface RequestAddLabelToTaskRequest {
  label_id: string;
}

export interface RequestAddProjectMemberRequest {
  project_id: string;
  role: ModelsProjectMemberRole;
  user_id: string;
}

export interface RequestChangePasswordRequest {
  new_password?: string;
  old_password?: string;
}

export interface RequestCreateLabelRequest {
  color?: string;
  description?: string;
  name: string;
  project_id: string;
}

export interface RequestCreateMessageRequest {
  /** Maximum 2000 characters */
  content: number[];
  image_url?: string;
  type_content: number;
}

export interface RequestCreateOrganizationRequest {
  avatar?: string;
  description?: string;
  industry?: string;
  name: string;
  region?: string;
  size?: number;
}

export interface RequestCreateProjectRequest {
  avatar?: string;
  description?: string;
  key: string;
  lead?: string;
  name: string;
  organization_id: string;
  project_type?: string;
  settings?: RequestProjectSettingsRequest;
  template_id?: string;
}

export interface RequestCreateTaskCommentRequest {
  content: string;
  mentions?: string[];
  parent_id?: string;
  task_id: string;
}

export interface RequestCreateTaskListRequest {
  color?: string;
  description?: string;
  is_default?: boolean;
  name: string;
  position?: number;
  project_id: string;
}

export interface RequestCreateTaskRequest {
  assignee?: string;
  description?: string;
  /** ISO date string */
  due_date?: string;
  due_reminder?: RequestDueReminderRequest;
  labels?: string[];
  list_id: string;
  parent_task_id?: string;
  priority?: ModelsTaskPriority;
  project_id: string;
  title: string;
}

export interface RequestDeleteMultipleTasksRequest {
  task_ids: string[];
}

export interface RequestDueReminderRequest {
  custom_days?: number;
  enabled?: boolean;
  /** "1day", "3days", "1week", "custom" */
  reminder_type?: string;
}

export interface RequestForgotPasswordRequest {
  email?: string;
  new_password?: string;
  step?: number;
  verify_code?: string;
}

export interface RequestInviteMemberRequest {
  email?: string;
  role: ModelsOrganizationRole;
}

export interface RequestJoinOrganizationRequest {
  invite_code: string;
}

export interface RequestLoginRequest {
  email?: string;
  password?: string;
}

export interface RequestMoveTaskRequest {
  target_list_id: string;
  target_position: number;
}

export interface RequestNotificationRequest {
  circle_id?: string;
  data?: string;
  notify_type?: string;
}

export interface RequestProjectSettingsRequest {
  allow_guests?: boolean;
  enable_due_dates?: boolean;
  enable_notifications?: boolean;
  enable_time_tracking?: boolean;
}

export interface RequestRegisterDeviceRequest {
  token_device?: string;
}

export interface RequestRegisterRequest {
  email: string;
  full_name?: string;
  password?: string;
  /**
   * @minimum 1
   * @maximum 3
   */
  step: number;
  verify_code?: string;
}

export interface RequestRoomRequest {
  members?: string[];
  name?: string;
  organization_id?: string;
  type_of_room?: number;
}

export interface RequestUpdateLabelRequest {
  color?: string;
  description?: string;
  name?: string;
}

export interface RequestUpdateMemberRoleRequest {
  role: ModelsOrganizationRole;
  user_id: string;
}

export interface RequestUpdateOrganizationRequest {
  avatar?: string;
  description?: string;
  industry?: string;
  name?: string;
  region?: string;
  size?: number;
}

export interface RequestUpdateProfileRequest {
  address?: number[];
  colour?: string;
  date_of_birth?: string;
  email?: number[];
  full_name?: number[];
  gender?: number;
  phone_number?: number[];
  profile_image?: string;
}

export interface RequestUpdateProjectRequest {
  avatar?: string;
  description?: string;
  lead?: string;
  name?: string;
  project_type?: string;
  settings?: RequestProjectSettingsRequest;
  status?: string;
}

export interface RequestUpdateTaskLabelsRequest {
  label_ids?: string[];
}

export interface RequestUpdateTaskRequest {
  assignee?: string;
  completed?: boolean;
  description?: string;
  due_date?: string;
  due_reminder?: RequestDueReminderRequest;
  labels?: string[];
  priority?: ModelsTaskPriority;
  status?: string;
  title?: string;
}

export type ResponseActivityLogResponseDetails = { [key: string]: unknown };

export interface ResponseActivityLogResponse {
  action?: string;
  created_at?: string;
  details?: ResponseActivityLogResponseDetails;
  id?: string;
  project_id?: string;
  target_id?: string;
  target_type?: string;
  user?: ResponseUserBasicInfo;
}

export interface ResponseDeleteMultipleTasksResponse {
  deleted_task_ids?: string[];
  failed_task_ids?: string[];
  total_deleted?: number;
  total_failed?: number;
  total_requested?: number;
}

export interface ResponseDirectMessageAndRoomResponse {
  message?: ResponseMessageResponse[];
  room?: ResponseRoomResponse;
}

export interface ResponseDueReminderResponse {
  custom_days?: number;
  enabled?: boolean;
  reminder_type?: string;
}

export interface ResponseForgotPasswordVerifyCode {
  verify_code?: string;
}

export interface ResponseGetUserInfoResponse {
  colour?: string;
  created_at?: string;
  email?: string;
  full_name?: string;
  phone_number?: string;
  profile_image?: string;
  updated_at?: string;
  user_id?: string;
}

export interface ResponseKanbanBoardResponse {
  labels?: string[];
  lists?: ResponseTaskListWithTasksResponse[];
  members?: ResponseProjectMemberResponse[];
  priorities?: string[];
  project?: ResponseProjectResponse;
}

export interface ResponseLabelResponse {
  color?: string;
  created_at?: string;
  created_by?: ResponseUserBasicInfo;
  description?: string;
  id?: string;
  name?: string;
  project_id?: string;
  updated_at?: string;
}

export interface ResponseLabelWithUsageResponse {
  label?: ResponseLabelResponse;
  last_used?: string;
  task_count?: number;
}

export interface ResponseLoginResponse {
  token?: string;
  user?: ModelsUser;
}

export interface ResponseMessageResponse {
  content?: string;
  created_at?: string;
  id?: string;
  image_url?: string;
  type_content?: number;
  updated_at?: string;
  user?: ResponseUserResponse;
}

export interface ResponseOrganizationInvitationResponse {
  created_at?: string;
  email?: string;
  expires_at?: string;
  id?: string;
  invite_code?: string;
  organization_id?: string;
  status?: ModelsOrganizationInvitationStatus;
}

export interface ResponseOrganizationMemberResponse {
  id?: string;
  invited_by?: string;
  joined_at?: string;
  organization_id?: string;
  role?: ModelsOrganizationRole;
  user_avatar?: string;
  user_email?: string;
  user_id?: string;
  user_name?: string;
}

export interface ResponseOrganizationResponse {
  admin_count?: number;
  avatar?: string;
  created_at?: string;
  description?: string;
  id?: string;
  industry?: string;
  member_count?: number;
  name?: string;
  region?: string;
  size?: number;
  sub_admin_count?: number;
  updated_at?: string;
}

export interface ResponseOrganizationWithRole {
  joined_at?: string;
  organization?: ResponseOrganizationResponse;
  role?: ModelsOrganizationRole;
}

export interface ResponseProjectDashboardResponse {
  project?: ResponseProjectResponse;
  recent_activity?: ResponseActivityLogResponse[];
  tasks_summary?: ResponseTasksSummaryResponse;
  team_activity?: ResponseTeamActivityResponse[];
  upcoming_deadlines?: ResponseTaskResponse[];
}

export interface ResponseProjectMemberResponse {
  created_by?: ResponseUserBasicInfo;
  id?: string;
  joined_at?: string;
  project_id?: string;
  role?: ModelsProjectMemberRole;
  user?: ResponseUserBasicInfo;
}

export interface ResponseProjectResponse {
  avatar?: string;
  created_at?: string;
  created_by?: string;
  description?: string;
  id?: string;
  key?: string;
  lead?: string;
  name?: string;
  organization_id?: string;
  project_type?: string;
  settings?: ResponseProjectSettingsResponse;
  status?: string;
  template_id?: string;
  updated_at?: string;
}

export interface ResponseProjectSettingsResponse {
  allow_guests?: boolean;
  enable_due_dates?: boolean;
  enable_notifications?: boolean;
  enable_time_tracking?: boolean;
}

export interface ResponseResponse {
  code?: string;
  data?: unknown;
  message?: string;
}

export interface ResponseRoomResponse {
  created_at?: string;
  has_notification?: boolean;
  id?: string;
  latest_messages?: ModelsMessage;
  members?: ModelsUser[];
  name?: string;
  type_of_room?: number;
  updated_at?: string;
}

export interface ResponseTaskCommentResponse {
  author?: ResponseUserBasicInfo;
  content?: string;
  created_at?: string;
  id?: string;
  mentions?: ResponseUserBasicInfo[];
  parent_id?: string;
  replies?: ResponseTaskCommentResponse[];
  task_id?: string;
  updated_at?: string;
}

export interface ResponseTaskListResponse {
  color?: string;
  created_at?: string;
  created_by?: string;
  description?: string;
  id?: string;
  is_default?: boolean;
  name?: string;
  position?: number;
  project_id?: string;
  tasks_count?: number;
  updated_at?: string;
}

export interface ResponseTaskListWithTasksResponse {
  list?: ResponseTaskListResponse;
  tasks?: ResponseTaskResponse[];
}

export interface ResponseTaskResponse {
  assignee?: ResponseUserBasicInfo;
  attachments_count?: number;
  board_position?: number;
  comments_count?: number;
  completed?: boolean;
  completed_at?: string;
  created_at?: string;
  created_by?: ResponseUserBasicInfo;
  cycle_time?: number;
  description?: string;
  due_date?: string;
  due_reminder?: ResponseDueReminderResponse;
  id?: string;
  labels?: string[];
  lead_time?: number;
  list_id?: string;
  parent_task_id?: string;
  position?: number;
  priority?: string;
  project_id?: string;
  reporter?: ResponseUserBasicInfo;
  start_date?: string;
  started_at?: string;
  status?: string;
  subscribers_count?: number;
  swimlane_priority?: number;
  title?: string;
  updated_at?: string;
}

export interface ResponseTaskSearchResponse {
  page?: number;
  page_size?: number;
  tasks?: ResponseTaskResponse[];
  total?: number;
  total_pages?: number;
}

export interface ResponseTasksSummaryResponse {
  completed?: number;
  in_progress?: number;
  overdue?: number;
  pending?: number;
  total?: number;
}

export interface ResponseTeamActivityResponse {
  last_activity?: string;
  tasks_completed?: number;
  tasks_created?: number;
  user?: ResponseUserBasicInfo;
}

export interface ResponseUserBasicInfo {
  colour?: string;
  email?: string;
  full_name?: string;
  id?: string;
  profile_image?: string;
}

export interface ResponseUserOrganizationsResponse {
  organizations?: ResponseOrganizationWithRole[];
  total?: number;
}

export interface ResponseUserResponse {
  colour?: string;
  email?: string;
  full_name?: string;
  id?: string;
  profile_image?: string;
}

export type GetAuthDownloadParams = {
  /**
   * Object S3 ID
   */
  object_id?: string;
  /**
   * Object S3 key
   */
  object_key?: string;
};

export type PostAuthFileUploadBody = {
  /**  File data  */
  file: Blob;
};

export type PostAuthFileUpload201AllOf = {
  data?: ModelsS3Object;
};

export type PostAuthFileUpload201 = ResponseResponse & PostAuthFileUpload201AllOf;

export type GetAuthGoogleCallbackParams = {
  /**
   * OAuth authorization code
   */
  code: string;
  /**
   * OAuth state parameter
   */
  state?: string;
};

export type GetAuthGoogleCallback200AllOf = {
  data?: ResponseLoginResponse;
};

export type GetAuthGoogleCallback200 = ResponseResponse & GetAuthGoogleCallback200AllOf;

export type PostAuthLabels200AllOf = {
  data?: ResponseLabelResponse;
};

export type PostAuthLabels200 = ResponseResponse & PostAuthLabels200AllOf;

export type PutAuthLabelsLabelId200AllOf = {
  data?: ResponseLabelResponse;
};

export type PutAuthLabelsLabelId200 = ResponseResponse & PutAuthLabelsLabelId200AllOf;

export type GetAuthLabelsLabelIdUsage200AllOf = {
  data?: ResponseLabelWithUsageResponse;
};

export type GetAuthLabelsLabelIdUsage200 = ResponseResponse & GetAuthLabelsLabelIdUsage200AllOf;

export type GetAuthLabelsTemplates200AllOfDataItem = { [key: string]: string };

export type GetAuthLabelsTemplates200AllOf = {
  data?: GetAuthLabelsTemplates200AllOfDataItem[];
};

export type GetAuthLabelsTemplates200 = ResponseResponse & GetAuthLabelsTemplates200AllOf;

export type GetAuthOrganizationsParams = {
  /**
   * Page
   */
  page: number;
  /**
   * PageSize
   */
  page_size: number;
};

export type GetAuthOrganizations200AllOf = {
  data?: ResponseUserOrganizationsResponse;
};

export type GetAuthOrganizations200 = ResponseResponse & GetAuthOrganizations200AllOf;

export type PostAuthOrganizations201AllOf = {
  data?: ResponseOrganizationResponse;
};

export type PostAuthOrganizations201 = ResponseResponse & PostAuthOrganizations201AllOf;

export type GetAuthOrganizationsId200AllOf = {
  data?: ResponseOrganizationResponse;
};

export type GetAuthOrganizationsId200 = ResponseResponse & GetAuthOrganizationsId200AllOf;

export type PutAuthOrganizationsId200AllOf = {
  data?: ResponseOrganizationResponse;
};

export type PutAuthOrganizationsId200 = ResponseResponse & PutAuthOrganizationsId200AllOf;

export type PostAuthOrganizationsIdInvite201AllOf = {
  data?: ResponseOrganizationInvitationResponse;
};

export type PostAuthOrganizationsIdInvite201 = ResponseResponse &
  PostAuthOrganizationsIdInvite201AllOf;

export type GetAuthOrganizationsIdMembers200AllOf = {
  data?: ResponseOrganizationMemberResponse[];
};

export type GetAuthOrganizationsIdMembers200 = ResponseResponse &
  GetAuthOrganizationsIdMembers200AllOf;

export type PostAuthOrganizationsJoin200AllOf = {
  data?: ResponseOrganizationMemberResponse;
};

export type PostAuthOrganizationsJoin200 = ResponseResponse & PostAuthOrganizationsJoin200AllOf;

export type PostAuthProjects200AllOf = {
  data?: ResponseProjectResponse;
};

export type PostAuthProjects200 = ResponseResponse & PostAuthProjects200AllOf;

export type GetAuthProjectsProjectId200AllOf = {
  data?: ResponseProjectResponse;
};

export type GetAuthProjectsProjectId200 = ResponseResponse & GetAuthProjectsProjectId200AllOf;

export type PutAuthProjectsProjectId200AllOf = {
  data?: ResponseProjectResponse;
};

export type PutAuthProjectsProjectId200 = ResponseResponse & PutAuthProjectsProjectId200AllOf;

export type GetAuthProjectsProjectIdDashboard200AllOf = {
  data?: ResponseProjectDashboardResponse;
};

export type GetAuthProjectsProjectIdDashboard200 = ResponseResponse &
  GetAuthProjectsProjectIdDashboard200AllOf;

export type GetAuthProjectsProjectIdKanban200AllOf = {
  data?: ResponseKanbanBoardResponse;
};

export type GetAuthProjectsProjectIdKanban200 = ResponseResponse &
  GetAuthProjectsProjectIdKanban200AllOf;

export type GetAuthProjectsProjectIdLabels200AllOf = {
  data?: ResponseLabelResponse[];
};

export type GetAuthProjectsProjectIdLabels200 = ResponseResponse &
  GetAuthProjectsProjectIdLabels200AllOf;

export type GetAuthProjectsProjectIdLabelsSearchParams = {
  /**
   * Search query
   */
  q: string;
};

export type GetAuthProjectsProjectIdLabelsSearch200AllOf = {
  data?: ResponseLabelResponse[];
};

export type GetAuthProjectsProjectIdLabelsSearch200 = ResponseResponse &
  GetAuthProjectsProjectIdLabelsSearch200AllOf;

export type GetAuthProjectsProjectIdMembers200AllOf = {
  data?: ResponseProjectMemberResponse[];
};

export type GetAuthProjectsProjectIdMembers200 = ResponseResponse &
  GetAuthProjectsProjectIdMembers200AllOf;

export type PostAuthProjectsProjectIdMembers200AllOf = {
  data?: ResponseProjectMemberResponse;
};

export type PostAuthProjectsProjectIdMembers200 = ResponseResponse &
  PostAuthProjectsProjectIdMembers200AllOf;

export type GetAuthProjectsProjectIdTasksParams = {
  /**
   * Page number
   */
  page?: number;
  /**
   * Page size
   */
  page_size?: number;
  /**
   * Assignee ID
   */
  assignee?: string;
  /**
   * Task status
   */
  status?: string;
  /**
   * Task priority
   */
  priority?: string;
};

export type GetAuthProjectsProjectIdTasks200AllOf = {
  data?: ResponseTaskSearchResponse;
};

export type GetAuthProjectsProjectIdTasks200 = ResponseResponse &
  GetAuthProjectsProjectIdTasks200AllOf;

export type GetAuthProjectsMyProjects200AllOf = {
  data?: ResponseProjectResponse[];
};

export type GetAuthProjectsMyProjects200 = ResponseResponse & GetAuthProjectsMyProjects200AllOf;

export type PostAuthRegister200AllOf = {
  data?: ResponseLoginResponse;
};

export type PostAuthRegister200 = ResponseResponse & PostAuthRegister200AllOf;

export type PostAuthRoom200AllOf = {
  data?: ResponseRoomResponse;
};

export type PostAuthRoom200 = ResponseResponse & PostAuthRoom200AllOf;

export type PostAuthRoom201AllOf = {
  data?: ResponseRoomResponse;
};

export type PostAuthRoom201 = ResponseResponse & PostAuthRoom201AllOf;

export type GetAuthRoomCircleIdParams = {
  /**
   * Page
   */
  page: number;
  /**
   * PageSize
   */
  page_size: number;
};

export type GetAuthRoomCircleId200AllOf = {
  data?: ResponseRoomResponse[];
};

export type GetAuthRoomCircleId200 = ResponseResponse & GetAuthRoomCircleId200AllOf;

export type PatchAuthRoomRoomId200AllOf = {
  data?: ResponseRoomResponse[];
};

export type PatchAuthRoomRoomId200 = ResponseResponse & PatchAuthRoomRoomId200AllOf;

export type PostAuthTaskLists200AllOf = {
  data?: ResponseTaskListResponse;
};

export type PostAuthTaskLists200 = ResponseResponse & PostAuthTaskLists200AllOf;

export type PostAuthTasks200AllOf = {
  data?: ResponseTaskResponse;
};

export type PostAuthTasks200 = ResponseResponse & PostAuthTasks200AllOf;

export type GetAuthTasksTaskId200AllOf = {
  data?: ResponseTaskResponse;
};

export type GetAuthTasksTaskId200 = ResponseResponse & GetAuthTasksTaskId200AllOf;

export type PutAuthTasksTaskId200AllOf = {
  data?: ResponseTaskResponse;
};

export type PutAuthTasksTaskId200 = ResponseResponse & PutAuthTasksTaskId200AllOf;

export type PostAuthTasksTaskIdComments200AllOf = {
  data?: ResponseTaskCommentResponse;
};

export type PostAuthTasksTaskIdComments200 = ResponseResponse & PostAuthTasksTaskIdComments200AllOf;

export type GetAuthTasksTaskIdLabels200AllOf = {
  data?: ResponseLabelResponse[];
};

export type GetAuthTasksTaskIdLabels200 = ResponseResponse & GetAuthTasksTaskIdLabels200AllOf;

export type PutAuthTasksTaskIdMove200AllOf = {
  data?: ResponseTaskResponse;
};

export type PutAuthTasksTaskIdMove200 = ResponseResponse & PutAuthTasksTaskIdMove200AllOf;

export type DeleteAuthTasksBatchDelete200AllOf = {
  data?: ResponseDeleteMultipleTasksResponse;
};

export type DeleteAuthTasksBatchDelete200 = ResponseResponse & DeleteAuthTasksBatchDelete200AllOf;

export type GetAuthUserProfile200AllOf = {
  data?: ResponseGetUserInfoResponse;
};

export type GetAuthUserProfile200 = ResponseResponse & GetAuthUserProfile200AllOf;

export type PutAuthUserProfile200AllOf = {
  data?: ModelsUser;
};

export type PutAuthUserProfile200 = ResponseResponse & PutAuthUserProfile200AllOf;

export type GetChatRoomIdParams = {
  /**
   * Page
   */
  page: number;
  /**
   * PageSize
   */
  page_size: number;
};

export type GetChatRoomId200AllOf = {
  data?: ResponseDirectMessageAndRoomResponse;
};

export type GetChatRoomId200 = ResponseResponse & GetChatRoomId200AllOf;

export type PostForgotPassword202AllOf = {
  data?: ResponseForgotPasswordVerifyCode;
};

export type PostForgotPassword202 = ResponseResponse & PostForgotPassword202AllOf;

export type PostLogin200AllOf = {
  data?: ResponseLoginResponse;
};

export type PostLogin200 = ResponseResponse & PostLogin200AllOf;
