/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Beta Workspace API
 * API documentation for Beta - an integrated workspace platform that helps teams work more efficiently through a unified ecosystem: team chat, collaborative documents, email, task management, and workflow automation.
 * OpenAPI spec version: 1.0.0
 */
import { useInfiniteQuery, useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  GetSprintsProjectId200,
  GetSprintsProjectIdParams,
  PostSprints200,
  RequestActiveNextSprintRequest,
  RequestCreateSprintRequest,
  RequestDeleteSprintRequest,
  RequestUpdateSprintRequest,
  ResponseResponse,
} from '../generated.schemas';

import deleteSprintsMutator from '../../../config/axios';
import patchSprintsMutator from '../../../config/axios';
import postSprintsMutator from '../../../config/axios';
import getSprintsProjectIdMutator from '../../../config/axios';
import patchSprintsActivateNextMutator from '../../../config/axios';

/**
 * Delete an existing sprint by its ID
 * @summary Delete an existing sprint
 */
export const deleteSprints = (requestDeleteSprintRequest: RequestDeleteSprintRequest) => {
  return deleteSprintsMutator<ResponseResponse>({
    url: `/sprints`,
    method: 'DELETE',
    headers: { 'Content-Type': 'application/json' },
    data: requestDeleteSprintRequest,
  });
};

export const getDeleteSprintsMutationOptions = <
  TError = ResponseResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteSprints>>,
    TError,
    { data: RequestDeleteSprintRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteSprints>>,
  TError,
  { data: RequestDeleteSprintRequest },
  TContext
> => {
  const mutationKey = ['deleteSprints'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteSprints>>,
    { data: RequestDeleteSprintRequest }
  > = (props) => {
    const { data } = props ?? {};

    return deleteSprints(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteSprintsMutationResult = NonNullable<Awaited<ReturnType<typeof deleteSprints>>>;
export type DeleteSprintsMutationBody = RequestDeleteSprintRequest;
export type DeleteSprintsMutationError = ResponseResponse;

/**
 * @summary Delete an existing sprint
 */
export const useDeleteSprints = <TError = ResponseResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteSprints>>,
      TError,
      { data: RequestDeleteSprintRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteSprints>>,
  TError,
  { data: RequestDeleteSprintRequest },
  TContext
> => {
  const mutationOptions = getDeleteSprintsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Update an existing sprint by its ID
 * @summary Update an existing sprint
 */
export const patchSprints = (requestUpdateSprintRequest: RequestUpdateSprintRequest) => {
  return patchSprintsMutator<ResponseResponse>({
    url: `/sprints`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    data: requestUpdateSprintRequest,
  });
};

export const getPatchSprintsMutationOptions = <
  TError = ResponseResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof patchSprints>>,
    TError,
    { data: RequestUpdateSprintRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof patchSprints>>,
  TError,
  { data: RequestUpdateSprintRequest },
  TContext
> => {
  const mutationKey = ['patchSprints'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof patchSprints>>,
    { data: RequestUpdateSprintRequest }
  > = (props) => {
    const { data } = props ?? {};

    return patchSprints(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PatchSprintsMutationResult = NonNullable<Awaited<ReturnType<typeof patchSprints>>>;
export type PatchSprintsMutationBody = RequestUpdateSprintRequest;
export type PatchSprintsMutationError = ResponseResponse;

/**
 * @summary Update an existing sprint
 */
export const usePatchSprints = <TError = ResponseResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof patchSprints>>,
      TError,
      { data: RequestUpdateSprintRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof patchSprints>>,
  TError,
  { data: RequestUpdateSprintRequest },
  TContext
> => {
  const mutationOptions = getPatchSprintsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Create a new sprint for a project
 * @summary Create a new sprint
 */
export const postSprints = (
  requestCreateSprintRequest: RequestCreateSprintRequest,
  signal?: AbortSignal,
) => {
  return postSprintsMutator<PostSprints200>({
    url: `/sprints`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: requestCreateSprintRequest,
    signal,
  });
};

export const getPostSprintsMutationOptions = <
  TError = ResponseResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postSprints>>,
    TError,
    { data: RequestCreateSprintRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postSprints>>,
  TError,
  { data: RequestCreateSprintRequest },
  TContext
> => {
  const mutationKey = ['postSprints'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postSprints>>,
    { data: RequestCreateSprintRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postSprints(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostSprintsMutationResult = NonNullable<Awaited<ReturnType<typeof postSprints>>>;
export type PostSprintsMutationBody = RequestCreateSprintRequest;
export type PostSprintsMutationError = ResponseResponse;

/**
 * @summary Create a new sprint
 */
export const usePostSprints = <TError = ResponseResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postSprints>>,
      TError,
      { data: RequestCreateSprintRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postSprints>>,
  TError,
  { data: RequestCreateSprintRequest },
  TContext
> => {
  const mutationOptions = getPostSprintsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Retrieve a list of sprints for a specific project
 * @summary Get sprints by project ID
 */
export const getSprintsProjectId = (
  projectId: string,
  params?: GetSprintsProjectIdParams,
  signal?: AbortSignal,
) => {
  return getSprintsProjectIdMutator<GetSprintsProjectId200>({
    url: `/sprints/${projectId}`,
    method: 'GET',
    params,
    signal,
  });
};

export const getGetSprintsProjectIdQueryKey = (
  projectId?: string,
  params?: GetSprintsProjectIdParams,
) => {
  return [`/sprints/${projectId}`, ...(params ? [params] : [])] as const;
};

export const getGetSprintsProjectIdInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof getSprintsProjectId>>>,
  TError = ResponseResponse,
>(
  projectId: string,
  params?: GetSprintsProjectIdParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSprintsProjectId>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSprintsProjectIdQueryKey(projectId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSprintsProjectId>>> = ({ signal }) =>
    getSprintsProjectId(projectId, params, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!projectId,
    staleTime: 10000,
    ...queryOptions,
  } as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSprintsProjectId>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetSprintsProjectIdInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSprintsProjectId>>
>;
export type GetSprintsProjectIdInfiniteQueryError = ResponseResponse;

export function useGetSprintsProjectIdInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getSprintsProjectId>>>,
  TError = ResponseResponse,
>(
  projectId: string,
  params: undefined | GetSprintsProjectIdParams,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSprintsProjectId>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSprintsProjectId>>,
          TError,
          Awaited<ReturnType<typeof getSprintsProjectId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSprintsProjectIdInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getSprintsProjectId>>>,
  TError = ResponseResponse,
>(
  projectId: string,
  params?: GetSprintsProjectIdParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSprintsProjectId>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSprintsProjectId>>,
          TError,
          Awaited<ReturnType<typeof getSprintsProjectId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSprintsProjectIdInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getSprintsProjectId>>>,
  TError = ResponseResponse,
>(
  projectId: string,
  params?: GetSprintsProjectIdParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSprintsProjectId>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get sprints by project ID
 */

export function useGetSprintsProjectIdInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getSprintsProjectId>>>,
  TError = ResponseResponse,
>(
  projectId: string,
  params?: GetSprintsProjectIdParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getSprintsProjectId>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetSprintsProjectIdInfiniteQueryOptions(projectId, params, options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetSprintsProjectIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getSprintsProjectId>>,
  TError = ResponseResponse,
>(
  projectId: string,
  params?: GetSprintsProjectIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSprintsProjectId>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSprintsProjectIdQueryKey(projectId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSprintsProjectId>>> = ({ signal }) =>
    getSprintsProjectId(projectId, params, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!projectId,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getSprintsProjectId>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetSprintsProjectIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSprintsProjectId>>
>;
export type GetSprintsProjectIdQueryError = ResponseResponse;

export function useGetSprintsProjectId<
  TData = Awaited<ReturnType<typeof getSprintsProjectId>>,
  TError = ResponseResponse,
>(
  projectId: string,
  params: undefined | GetSprintsProjectIdParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSprintsProjectId>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSprintsProjectId>>,
          TError,
          Awaited<ReturnType<typeof getSprintsProjectId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSprintsProjectId<
  TData = Awaited<ReturnType<typeof getSprintsProjectId>>,
  TError = ResponseResponse,
>(
  projectId: string,
  params?: GetSprintsProjectIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSprintsProjectId>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSprintsProjectId>>,
          TError,
          Awaited<ReturnType<typeof getSprintsProjectId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetSprintsProjectId<
  TData = Awaited<ReturnType<typeof getSprintsProjectId>>,
  TError = ResponseResponse,
>(
  projectId: string,
  params?: GetSprintsProjectIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSprintsProjectId>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Get sprints by project ID
 */

export function useGetSprintsProjectId<
  TData = Awaited<ReturnType<typeof getSprintsProjectId>>,
  TError = ResponseResponse,
>(
  projectId: string,
  params?: GetSprintsProjectIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getSprintsProjectId>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetSprintsProjectIdQueryOptions(projectId, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Activate the next sprint by its ID
 * @summary Activate the next sprint
 */
export const patchSprintsActivateNext = (
  requestActiveNextSprintRequest: RequestActiveNextSprintRequest,
) => {
  return patchSprintsActivateNextMutator<ResponseResponse>({
    url: `/sprints/activate-next`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    data: requestActiveNextSprintRequest,
  });
};

export const getPatchSprintsActivateNextMutationOptions = <
  TError = ResponseResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof patchSprintsActivateNext>>,
    TError,
    { data: RequestActiveNextSprintRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof patchSprintsActivateNext>>,
  TError,
  { data: RequestActiveNextSprintRequest },
  TContext
> => {
  const mutationKey = ['patchSprintsActivateNext'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof patchSprintsActivateNext>>,
    { data: RequestActiveNextSprintRequest }
  > = (props) => {
    const { data } = props ?? {};

    return patchSprintsActivateNext(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PatchSprintsActivateNextMutationResult = NonNullable<
  Awaited<ReturnType<typeof patchSprintsActivateNext>>
>;
export type PatchSprintsActivateNextMutationBody = RequestActiveNextSprintRequest;
export type PatchSprintsActivateNextMutationError = ResponseResponse;

/**
 * @summary Activate the next sprint
 */
export const usePatchSprintsActivateNext = <TError = ResponseResponse, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof patchSprintsActivateNext>>,
      TError,
      { data: RequestActiveNextSprintRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof patchSprintsActivateNext>>,
  TError,
  { data: RequestActiveNextSprintRequest },
  TContext
> => {
  const mutationOptions = getPatchSprintsActivateNextMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
