/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Beta Workspace API
 * API documentation for Beta - an integrated workspace platform that helps teams work more efficiently through a unified ecosystem: team chat, collaborative documents, email, task management, and workflow automation.
 * OpenAPI spec version: 1.0.0
 */
import { useInfiniteQuery, useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  GetAuthDownloadParams,
  PostAuthFileUpload201,
  PostAuthFileUploadBody,
} from '../generated.schemas';

import getAuthDownloadMutator from '../../config/axios';
import postAuthFileUploadMutator from '../../config/axios';

/**
 * API tải file từ server, sử dụng một trong hai tham số là object_id hoặc object_key
 * @summary Tải file từ server
 */
export const getAuthDownload = (params?: GetAuthDownloadParams, signal?: AbortSignal) => {
  return getAuthDownloadMutator<null>({ url: `/auth/download`, method: 'GET', params, signal });
};

export const getGetAuthDownloadQueryKey = (params?: GetAuthDownloadParams) => {
  return [`/auth/download`, ...(params ? [params] : [])] as const;
};

export const getGetAuthDownloadInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthDownload>>>,
  TError = unknown,
>(
  params?: GetAuthDownloadParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAuthDownload>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAuthDownloadQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthDownload>>> = ({ signal }) =>
    getAuthDownload(params, signal);

  return { queryKey, queryFn, staleTime: 10000, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getAuthDownload>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAuthDownloadInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAuthDownload>>
>;
export type GetAuthDownloadInfiniteQueryError = unknown;

export function useGetAuthDownloadInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthDownload>>>,
  TError = unknown,
>(
  params: undefined | GetAuthDownloadParams,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAuthDownload>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthDownload>>,
          TError,
          Awaited<ReturnType<typeof getAuthDownload>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthDownloadInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthDownload>>>,
  TError = unknown,
>(
  params?: GetAuthDownloadParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAuthDownload>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthDownload>>,
          TError,
          Awaited<ReturnType<typeof getAuthDownload>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthDownloadInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthDownload>>>,
  TError = unknown,
>(
  params?: GetAuthDownloadParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAuthDownload>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Tải file từ server
 */

export function useGetAuthDownloadInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthDownload>>>,
  TError = unknown,
>(
  params?: GetAuthDownloadParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAuthDownload>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAuthDownloadInfiniteQueryOptions(params, options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetAuthDownloadQueryOptions = <
  TData = Awaited<ReturnType<typeof getAuthDownload>>,
  TError = unknown,
>(
  params?: GetAuthDownloadParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthDownload>>, TError, TData>>;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAuthDownloadQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthDownload>>> = ({ signal }) =>
    getAuthDownload(params, signal);

  return { queryKey, queryFn, staleTime: 10000, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAuthDownload>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAuthDownloadQueryResult = NonNullable<Awaited<ReturnType<typeof getAuthDownload>>>;
export type GetAuthDownloadQueryError = unknown;

export function useGetAuthDownload<
  TData = Awaited<ReturnType<typeof getAuthDownload>>,
  TError = unknown,
>(
  params: undefined | GetAuthDownloadParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthDownload>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthDownload>>,
          TError,
          Awaited<ReturnType<typeof getAuthDownload>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthDownload<
  TData = Awaited<ReturnType<typeof getAuthDownload>>,
  TError = unknown,
>(
  params?: GetAuthDownloadParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthDownload>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthDownload>>,
          TError,
          Awaited<ReturnType<typeof getAuthDownload>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthDownload<
  TData = Awaited<ReturnType<typeof getAuthDownload>>,
  TError = unknown,
>(
  params?: GetAuthDownloadParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthDownload>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Tải file từ server
 */

export function useGetAuthDownload<
  TData = Awaited<ReturnType<typeof getAuthDownload>>,
  TError = unknown,
>(
  params?: GetAuthDownloadParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthDownload>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAuthDownloadQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * API dùng để upload file
 * @summary Upload file lên server
 */
export const postAuthFileUpload = (
  postAuthFileUploadBody: PostAuthFileUploadBody,
  signal?: AbortSignal,
) => {
  const formData = new FormData();
  formData.append(`file`, postAuthFileUploadBody.file);

  return postAuthFileUploadMutator<PostAuthFileUpload201>({
    url: `/auth/file/upload`,
    method: 'POST',
    headers: { 'Content-Type': 'multipart/form-data' },
    data: formData,
    signal,
  });
};

export const getPostAuthFileUploadMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthFileUpload>>,
    TError,
    { data: PostAuthFileUploadBody },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postAuthFileUpload>>,
  TError,
  { data: PostAuthFileUploadBody },
  TContext
> => {
  const mutationKey = ['postAuthFileUpload'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postAuthFileUpload>>,
    { data: PostAuthFileUploadBody }
  > = (props) => {
    const { data } = props ?? {};

    return postAuthFileUpload(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostAuthFileUploadMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAuthFileUpload>>
>;
export type PostAuthFileUploadMutationBody = PostAuthFileUploadBody;
export type PostAuthFileUploadMutationError = unknown;

/**
 * @summary Upload file lên server
 */
export const usePostAuthFileUpload = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postAuthFileUpload>>,
      TError,
      { data: PostAuthFileUploadBody },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postAuthFileUpload>>,
  TError,
  { data: PostAuthFileUploadBody },
  TContext
> => {
  const mutationOptions = getPostAuthFileUploadMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
