/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Beta Workspace API
 * API documentation for Beta - an integrated workspace platform that helps teams work more efficiently through a unified ecosystem: team chat, collaborative documents, email, task management, and workflow automation.
 * OpenAPI spec version: 1.0.0
 */
import { useInfiniteQuery, useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  GetAuthProjectsMyProjectsOrgId200,
  GetAuthProjectsMyProjectsOrgIdParams,
  GetAuthProjectsProjectId200,
  GetAuthProjectsProjectIdDashboard200,
  GetAuthProjectsProjectIdMembers200,
  GetAuthProjectsProjectIdMembersParams,
  PatchAuthProjectsProjectId200,
  PostAuthProjects200,
  PostAuthProjectsLaunch200,
  PostAuthProjectsMembers200,
  RequestAddProjectMemberRequest,
  RequestCreateProjectRequest,
  RequestLaunchProjectRequest,
  RequestUpdateProjectMemberRoleRequest,
  RequestUpdateProjectRequest,
  ResponseResponse,
} from '../generated.schemas';

import postAuthProjectsMutator from '../../../config/axios';
import getAuthProjectsProjectIdMutator from '../../../config/axios';
import patchAuthProjectsProjectIdMutator from '../../../config/axios';
import getAuthProjectsProjectIdDashboardMutator from '../../../config/axios';
import getAuthProjectsProjectIdMembersMutator from '../../../config/axios';
import postAuthProjectsLaunchMutator from '../../../config/axios';
import patchAuthProjectsMembersMutator from '../../../config/axios';
import postAuthProjectsMembersMutator from '../../../config/axios';
import getAuthProjectsMyProjectsOrgIdMutator from '../../../config/axios';

/**
 * API tạo dự án mới trong organization
 * @summary Tạo dự án mới
 */
export const postAuthProjects = (
  requestCreateProjectRequest: RequestCreateProjectRequest,
  signal?: AbortSignal,
) => {
  return postAuthProjectsMutator<PostAuthProjects200>({
    url: `/auth/projects`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: requestCreateProjectRequest,
    signal,
  });
};

export const getPostAuthProjectsMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthProjects>>,
    TError,
    { data: RequestCreateProjectRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postAuthProjects>>,
  TError,
  { data: RequestCreateProjectRequest },
  TContext
> => {
  const mutationKey = ['postAuthProjects'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postAuthProjects>>,
    { data: RequestCreateProjectRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postAuthProjects(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostAuthProjectsMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAuthProjects>>
>;
export type PostAuthProjectsMutationBody = RequestCreateProjectRequest;
export type PostAuthProjectsMutationError = unknown;

/**
 * @summary Tạo dự án mới
 */
export const usePostAuthProjects = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postAuthProjects>>,
      TError,
      { data: RequestCreateProjectRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postAuthProjects>>,
  TError,
  { data: RequestCreateProjectRequest },
  TContext
> => {
  const mutationOptions = getPostAuthProjectsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * API lấy thông tin chi tiết dự án
 * @summary Lấy thông tin dự án
 */
export const getAuthProjectsProjectId = (projectId: string, signal?: AbortSignal) => {
  return getAuthProjectsProjectIdMutator<GetAuthProjectsProjectId200>({
    url: `/auth/projects/${projectId}`,
    method: 'GET',
    signal,
  });
};

export const getGetAuthProjectsProjectIdQueryKey = (projectId?: string) => {
  return [`/auth/projects/${projectId}`] as const;
};

export const getGetAuthProjectsProjectIdInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthProjectsProjectId>>>,
  TError = unknown,
>(
  projectId: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAuthProjectsProjectId>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAuthProjectsProjectIdQueryKey(projectId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthProjectsProjectId>>> = ({
    signal,
  }) => getAuthProjectsProjectId(projectId, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!projectId,
    staleTime: 10000,
    ...queryOptions,
  } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getAuthProjectsProjectId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAuthProjectsProjectIdInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAuthProjectsProjectId>>
>;
export type GetAuthProjectsProjectIdInfiniteQueryError = unknown;

export function useGetAuthProjectsProjectIdInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthProjectsProjectId>>>,
  TError = unknown,
>(
  projectId: string,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAuthProjectsProjectId>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthProjectsProjectId>>,
          TError,
          Awaited<ReturnType<typeof getAuthProjectsProjectId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthProjectsProjectIdInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthProjectsProjectId>>>,
  TError = unknown,
>(
  projectId: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAuthProjectsProjectId>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthProjectsProjectId>>,
          TError,
          Awaited<ReturnType<typeof getAuthProjectsProjectId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthProjectsProjectIdInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthProjectsProjectId>>>,
  TError = unknown,
>(
  projectId: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAuthProjectsProjectId>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Lấy thông tin dự án
 */

export function useGetAuthProjectsProjectIdInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthProjectsProjectId>>>,
  TError = unknown,
>(
  projectId: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAuthProjectsProjectId>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAuthProjectsProjectIdInfiniteQueryOptions(projectId, options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetAuthProjectsProjectIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getAuthProjectsProjectId>>,
  TError = unknown,
>(
  projectId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthProjectsProjectId>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAuthProjectsProjectIdQueryKey(projectId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthProjectsProjectId>>> = ({
    signal,
  }) => getAuthProjectsProjectId(projectId, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!projectId,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getAuthProjectsProjectId>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetAuthProjectsProjectIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAuthProjectsProjectId>>
>;
export type GetAuthProjectsProjectIdQueryError = unknown;

export function useGetAuthProjectsProjectId<
  TData = Awaited<ReturnType<typeof getAuthProjectsProjectId>>,
  TError = unknown,
>(
  projectId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthProjectsProjectId>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthProjectsProjectId>>,
          TError,
          Awaited<ReturnType<typeof getAuthProjectsProjectId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthProjectsProjectId<
  TData = Awaited<ReturnType<typeof getAuthProjectsProjectId>>,
  TError = unknown,
>(
  projectId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthProjectsProjectId>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthProjectsProjectId>>,
          TError,
          Awaited<ReturnType<typeof getAuthProjectsProjectId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthProjectsProjectId<
  TData = Awaited<ReturnType<typeof getAuthProjectsProjectId>>,
  TError = unknown,
>(
  projectId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthProjectsProjectId>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Lấy thông tin dự án
 */

export function useGetAuthProjectsProjectId<
  TData = Awaited<ReturnType<typeof getAuthProjectsProjectId>>,
  TError = unknown,
>(
  projectId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthProjectsProjectId>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAuthProjectsProjectIdQueryOptions(projectId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * API cập nhật thông tin dự án (chỉ có admin)
 * @summary Cập nhật dự án
 */
export const patchAuthProjectsProjectId = (
  projectId: string,
  requestUpdateProjectRequest: RequestUpdateProjectRequest,
) => {
  return patchAuthProjectsProjectIdMutator<PatchAuthProjectsProjectId200>({
    url: `/auth/projects/${projectId}`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    data: requestUpdateProjectRequest,
  });
};

export const getPatchAuthProjectsProjectIdMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof patchAuthProjectsProjectId>>,
    TError,
    { projectId: string; data: RequestUpdateProjectRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof patchAuthProjectsProjectId>>,
  TError,
  { projectId: string; data: RequestUpdateProjectRequest },
  TContext
> => {
  const mutationKey = ['patchAuthProjectsProjectId'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof patchAuthProjectsProjectId>>,
    { projectId: string; data: RequestUpdateProjectRequest }
  > = (props) => {
    const { projectId, data } = props ?? {};

    return patchAuthProjectsProjectId(projectId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PatchAuthProjectsProjectIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof patchAuthProjectsProjectId>>
>;
export type PatchAuthProjectsProjectIdMutationBody = RequestUpdateProjectRequest;
export type PatchAuthProjectsProjectIdMutationError = unknown;

/**
 * @summary Cập nhật dự án
 */
export const usePatchAuthProjectsProjectId = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof patchAuthProjectsProjectId>>,
      TError,
      { projectId: string; data: RequestUpdateProjectRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof patchAuthProjectsProjectId>>,
  TError,
  { projectId: string; data: RequestUpdateProjectRequest },
  TContext
> => {
  const mutationOptions = getPatchAuthProjectsProjectIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * API lấy dashboard với thống kê và hoạt động gần đây
 * @summary Lấy dashboard dự án
 */
export const getAuthProjectsProjectIdDashboard = (projectId: string, signal?: AbortSignal) => {
  return getAuthProjectsProjectIdDashboardMutator<GetAuthProjectsProjectIdDashboard200>({
    url: `/auth/projects/${projectId}/dashboard`,
    method: 'GET',
    signal,
  });
};

export const getGetAuthProjectsProjectIdDashboardQueryKey = (projectId?: string) => {
  return [`/auth/projects/${projectId}/dashboard`] as const;
};

export const getGetAuthProjectsProjectIdDashboardInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthProjectsProjectIdDashboard>>>,
  TError = unknown,
>(
  projectId: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getAuthProjectsProjectIdDashboard>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetAuthProjectsProjectIdDashboardQueryKey(projectId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthProjectsProjectIdDashboard>>> = ({
    signal,
  }) => getAuthProjectsProjectIdDashboard(projectId, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!projectId,
    staleTime: 10000,
    ...queryOptions,
  } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getAuthProjectsProjectIdDashboard>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAuthProjectsProjectIdDashboardInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAuthProjectsProjectIdDashboard>>
>;
export type GetAuthProjectsProjectIdDashboardInfiniteQueryError = unknown;

export function useGetAuthProjectsProjectIdDashboardInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthProjectsProjectIdDashboard>>>,
  TError = unknown,
>(
  projectId: string,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getAuthProjectsProjectIdDashboard>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthProjectsProjectIdDashboard>>,
          TError,
          Awaited<ReturnType<typeof getAuthProjectsProjectIdDashboard>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthProjectsProjectIdDashboardInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthProjectsProjectIdDashboard>>>,
  TError = unknown,
>(
  projectId: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getAuthProjectsProjectIdDashboard>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthProjectsProjectIdDashboard>>,
          TError,
          Awaited<ReturnType<typeof getAuthProjectsProjectIdDashboard>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthProjectsProjectIdDashboardInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthProjectsProjectIdDashboard>>>,
  TError = unknown,
>(
  projectId: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getAuthProjectsProjectIdDashboard>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Lấy dashboard dự án
 */

export function useGetAuthProjectsProjectIdDashboardInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthProjectsProjectIdDashboard>>>,
  TError = unknown,
>(
  projectId: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getAuthProjectsProjectIdDashboard>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAuthProjectsProjectIdDashboardInfiniteQueryOptions(projectId, options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetAuthProjectsProjectIdDashboardQueryOptions = <
  TData = Awaited<ReturnType<typeof getAuthProjectsProjectIdDashboard>>,
  TError = unknown,
>(
  projectId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthProjectsProjectIdDashboard>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetAuthProjectsProjectIdDashboardQueryKey(projectId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthProjectsProjectIdDashboard>>> = ({
    signal,
  }) => getAuthProjectsProjectIdDashboard(projectId, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!projectId,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getAuthProjectsProjectIdDashboard>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAuthProjectsProjectIdDashboardQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAuthProjectsProjectIdDashboard>>
>;
export type GetAuthProjectsProjectIdDashboardQueryError = unknown;

export function useGetAuthProjectsProjectIdDashboard<
  TData = Awaited<ReturnType<typeof getAuthProjectsProjectIdDashboard>>,
  TError = unknown,
>(
  projectId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthProjectsProjectIdDashboard>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthProjectsProjectIdDashboard>>,
          TError,
          Awaited<ReturnType<typeof getAuthProjectsProjectIdDashboard>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthProjectsProjectIdDashboard<
  TData = Awaited<ReturnType<typeof getAuthProjectsProjectIdDashboard>>,
  TError = unknown,
>(
  projectId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthProjectsProjectIdDashboard>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthProjectsProjectIdDashboard>>,
          TError,
          Awaited<ReturnType<typeof getAuthProjectsProjectIdDashboard>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthProjectsProjectIdDashboard<
  TData = Awaited<ReturnType<typeof getAuthProjectsProjectIdDashboard>>,
  TError = unknown,
>(
  projectId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthProjectsProjectIdDashboard>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Lấy dashboard dự án
 */

export function useGetAuthProjectsProjectIdDashboard<
  TData = Awaited<ReturnType<typeof getAuthProjectsProjectIdDashboard>>,
  TError = unknown,
>(
  projectId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthProjectsProjectIdDashboard>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAuthProjectsProjectIdDashboardQueryOptions(projectId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * API lấy tất cả thành viên trong dự án có thể search theo tên, email, số điện thoại, vai trò và phân trang
 * @summary Lấy danh sách thành viên dự án (là người xem trở lên mới được xem, nếu là viewer thì chỉ khi project allow guest)
 */
export const getAuthProjectsProjectIdMembers = (
  projectId: string,
  params?: GetAuthProjectsProjectIdMembersParams,
  signal?: AbortSignal,
) => {
  return getAuthProjectsProjectIdMembersMutator<GetAuthProjectsProjectIdMembers200>({
    url: `/auth/projects/${projectId}/members`,
    method: 'GET',
    params,
    signal,
  });
};

export const getGetAuthProjectsProjectIdMembersQueryKey = (
  projectId?: string,
  params?: GetAuthProjectsProjectIdMembersParams,
) => {
  return [`/auth/projects/${projectId}/members`, ...(params ? [params] : [])] as const;
};

export const getGetAuthProjectsProjectIdMembersInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthProjectsProjectIdMembers>>>,
  TError = unknown,
>(
  projectId: string,
  params?: GetAuthProjectsProjectIdMembersParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getAuthProjectsProjectIdMembers>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetAuthProjectsProjectIdMembersQueryKey(projectId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthProjectsProjectIdMembers>>> = ({
    signal,
  }) => getAuthProjectsProjectIdMembers(projectId, params, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!projectId,
    staleTime: 10000,
    ...queryOptions,
  } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getAuthProjectsProjectIdMembers>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAuthProjectsProjectIdMembersInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAuthProjectsProjectIdMembers>>
>;
export type GetAuthProjectsProjectIdMembersInfiniteQueryError = unknown;

export function useGetAuthProjectsProjectIdMembersInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthProjectsProjectIdMembers>>>,
  TError = unknown,
>(
  projectId: string,
  params: undefined | GetAuthProjectsProjectIdMembersParams,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getAuthProjectsProjectIdMembers>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthProjectsProjectIdMembers>>,
          TError,
          Awaited<ReturnType<typeof getAuthProjectsProjectIdMembers>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthProjectsProjectIdMembersInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthProjectsProjectIdMembers>>>,
  TError = unknown,
>(
  projectId: string,
  params?: GetAuthProjectsProjectIdMembersParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getAuthProjectsProjectIdMembers>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthProjectsProjectIdMembers>>,
          TError,
          Awaited<ReturnType<typeof getAuthProjectsProjectIdMembers>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthProjectsProjectIdMembersInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthProjectsProjectIdMembers>>>,
  TError = unknown,
>(
  projectId: string,
  params?: GetAuthProjectsProjectIdMembersParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getAuthProjectsProjectIdMembers>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Lấy danh sách thành viên dự án (là người xem trở lên mới được xem, nếu là viewer thì chỉ khi project allow guest)
 */

export function useGetAuthProjectsProjectIdMembersInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthProjectsProjectIdMembers>>>,
  TError = unknown,
>(
  projectId: string,
  params?: GetAuthProjectsProjectIdMembersParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getAuthProjectsProjectIdMembers>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAuthProjectsProjectIdMembersInfiniteQueryOptions(
    projectId,
    params,
    options,
  );

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetAuthProjectsProjectIdMembersQueryOptions = <
  TData = Awaited<ReturnType<typeof getAuthProjectsProjectIdMembers>>,
  TError = unknown,
>(
  projectId: string,
  params?: GetAuthProjectsProjectIdMembersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthProjectsProjectIdMembers>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetAuthProjectsProjectIdMembersQueryKey(projectId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthProjectsProjectIdMembers>>> = ({
    signal,
  }) => getAuthProjectsProjectIdMembers(projectId, params, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!projectId,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getAuthProjectsProjectIdMembers>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAuthProjectsProjectIdMembersQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAuthProjectsProjectIdMembers>>
>;
export type GetAuthProjectsProjectIdMembersQueryError = unknown;

export function useGetAuthProjectsProjectIdMembers<
  TData = Awaited<ReturnType<typeof getAuthProjectsProjectIdMembers>>,
  TError = unknown,
>(
  projectId: string,
  params: undefined | GetAuthProjectsProjectIdMembersParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthProjectsProjectIdMembers>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthProjectsProjectIdMembers>>,
          TError,
          Awaited<ReturnType<typeof getAuthProjectsProjectIdMembers>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthProjectsProjectIdMembers<
  TData = Awaited<ReturnType<typeof getAuthProjectsProjectIdMembers>>,
  TError = unknown,
>(
  projectId: string,
  params?: GetAuthProjectsProjectIdMembersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthProjectsProjectIdMembers>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthProjectsProjectIdMembers>>,
          TError,
          Awaited<ReturnType<typeof getAuthProjectsProjectIdMembers>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthProjectsProjectIdMembers<
  TData = Awaited<ReturnType<typeof getAuthProjectsProjectIdMembers>>,
  TError = unknown,
>(
  projectId: string,
  params?: GetAuthProjectsProjectIdMembersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthProjectsProjectIdMembers>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Lấy danh sách thành viên dự án (là người xem trở lên mới được xem, nếu là viewer thì chỉ khi project allow guest)
 */

export function useGetAuthProjectsProjectIdMembers<
  TData = Awaited<ReturnType<typeof getAuthProjectsProjectIdMembers>>,
  TError = unknown,
>(
  projectId: string,
  params?: GetAuthProjectsProjectIdMembersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthProjectsProjectIdMembers>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAuthProjectsProjectIdMembersQueryOptions(projectId, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * API Launch dự án cho user hiện tại
 * @summary Launch dự án cho user
 */
export const postAuthProjectsLaunch = (
  requestLaunchProjectRequest: RequestLaunchProjectRequest,
  signal?: AbortSignal,
) => {
  return postAuthProjectsLaunchMutator<PostAuthProjectsLaunch200>({
    url: `/auth/projects/launch`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: requestLaunchProjectRequest,
    signal,
  });
};

export const getPostAuthProjectsLaunchMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthProjectsLaunch>>,
    TError,
    { data: RequestLaunchProjectRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postAuthProjectsLaunch>>,
  TError,
  { data: RequestLaunchProjectRequest },
  TContext
> => {
  const mutationKey = ['postAuthProjectsLaunch'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postAuthProjectsLaunch>>,
    { data: RequestLaunchProjectRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postAuthProjectsLaunch(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostAuthProjectsLaunchMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAuthProjectsLaunch>>
>;
export type PostAuthProjectsLaunchMutationBody = RequestLaunchProjectRequest;
export type PostAuthProjectsLaunchMutationError = unknown;

/**
 * @summary Launch dự án cho user
 */
export const usePostAuthProjectsLaunch = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postAuthProjectsLaunch>>,
      TError,
      { data: RequestLaunchProjectRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postAuthProjectsLaunch>>,
  TError,
  { data: RequestLaunchProjectRequest },
  TContext
> => {
  const mutationOptions = getPostAuthProjectsLaunchMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * API cập nhật vai trò thành viên trong dự án
 * @summary Cập nhật vai trò thành viên dự án (chỉ admin và sub-admin)
 */
export const patchAuthProjectsMembers = (
  requestUpdateProjectMemberRoleRequest: RequestUpdateProjectMemberRoleRequest,
) => {
  return patchAuthProjectsMembersMutator<ResponseResponse>({
    url: `/auth/projects/members`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    data: requestUpdateProjectMemberRoleRequest,
  });
};

export const getPatchAuthProjectsMembersMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof patchAuthProjectsMembers>>,
    TError,
    { data: RequestUpdateProjectMemberRoleRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof patchAuthProjectsMembers>>,
  TError,
  { data: RequestUpdateProjectMemberRoleRequest },
  TContext
> => {
  const mutationKey = ['patchAuthProjectsMembers'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof patchAuthProjectsMembers>>,
    { data: RequestUpdateProjectMemberRoleRequest }
  > = (props) => {
    const { data } = props ?? {};

    return patchAuthProjectsMembers(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PatchAuthProjectsMembersMutationResult = NonNullable<
  Awaited<ReturnType<typeof patchAuthProjectsMembers>>
>;
export type PatchAuthProjectsMembersMutationBody = RequestUpdateProjectMemberRoleRequest;
export type PatchAuthProjectsMembersMutationError = unknown;

/**
 * @summary Cập nhật vai trò thành viên dự án (chỉ admin và sub-admin)
 */
export const usePatchAuthProjectsMembers = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof patchAuthProjectsMembers>>,
      TError,
      { data: RequestUpdateProjectMemberRoleRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof patchAuthProjectsMembers>>,
  TError,
  { data: RequestUpdateProjectMemberRoleRequest },
  TContext
> => {
  const mutationOptions = getPatchAuthProjectsMembersMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * API thêm thành viên mới vào dự án (chỉ admin)
 * @summary Thêm thành viên vào dự án
 */
export const postAuthProjectsMembers = (
  requestAddProjectMemberRequest: RequestAddProjectMemberRequest,
  signal?: AbortSignal,
) => {
  return postAuthProjectsMembersMutator<PostAuthProjectsMembers200>({
    url: `/auth/projects/members`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: requestAddProjectMemberRequest,
    signal,
  });
};

export const getPostAuthProjectsMembersMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthProjectsMembers>>,
    TError,
    { data: RequestAddProjectMemberRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postAuthProjectsMembers>>,
  TError,
  { data: RequestAddProjectMemberRequest },
  TContext
> => {
  const mutationKey = ['postAuthProjectsMembers'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postAuthProjectsMembers>>,
    { data: RequestAddProjectMemberRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postAuthProjectsMembers(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostAuthProjectsMembersMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAuthProjectsMembers>>
>;
export type PostAuthProjectsMembersMutationBody = RequestAddProjectMemberRequest;
export type PostAuthProjectsMembersMutationError = unknown;

/**
 * @summary Thêm thành viên vào dự án
 */
export const usePostAuthProjectsMembers = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postAuthProjectsMembers>>,
      TError,
      { data: RequestAddProjectMemberRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postAuthProjectsMembers>>,
  TError,
  { data: RequestAddProjectMemberRequest },
  TContext
> => {
  const mutationOptions = getPostAuthProjectsMembersMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * API lấy tất cả dự án mà user tham gia hoặc có quyền view có thể search theo tên, trạng thái, loại dự án, vai trò, lọc theo tổ chức và phân trang
 * @summary Lấy danh sách dự án của user
 */
export const getAuthProjectsMyProjectsOrgId = (
  orgId: string,
  params?: GetAuthProjectsMyProjectsOrgIdParams,
  signal?: AbortSignal,
) => {
  return getAuthProjectsMyProjectsOrgIdMutator<GetAuthProjectsMyProjectsOrgId200>({
    url: `/auth/projects/my-projects/${orgId}`,
    method: 'GET',
    params,
    signal,
  });
};

export const getGetAuthProjectsMyProjectsOrgIdQueryKey = (
  orgId?: string,
  params?: GetAuthProjectsMyProjectsOrgIdParams,
) => {
  return [`/auth/projects/my-projects/${orgId}`, ...(params ? [params] : [])] as const;
};

export const getGetAuthProjectsMyProjectsOrgIdInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthProjectsMyProjectsOrgId>>>,
  TError = unknown,
>(
  orgId: string,
  params?: GetAuthProjectsMyProjectsOrgIdParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getAuthProjectsMyProjectsOrgId>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetAuthProjectsMyProjectsOrgIdQueryKey(orgId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthProjectsMyProjectsOrgId>>> = ({
    signal,
  }) => getAuthProjectsMyProjectsOrgId(orgId, params, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!orgId,
    staleTime: 10000,
    ...queryOptions,
  } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getAuthProjectsMyProjectsOrgId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAuthProjectsMyProjectsOrgIdInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAuthProjectsMyProjectsOrgId>>
>;
export type GetAuthProjectsMyProjectsOrgIdInfiniteQueryError = unknown;

export function useGetAuthProjectsMyProjectsOrgIdInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthProjectsMyProjectsOrgId>>>,
  TError = unknown,
>(
  orgId: string,
  params: undefined | GetAuthProjectsMyProjectsOrgIdParams,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getAuthProjectsMyProjectsOrgId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthProjectsMyProjectsOrgId>>,
          TError,
          Awaited<ReturnType<typeof getAuthProjectsMyProjectsOrgId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthProjectsMyProjectsOrgIdInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthProjectsMyProjectsOrgId>>>,
  TError = unknown,
>(
  orgId: string,
  params?: GetAuthProjectsMyProjectsOrgIdParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getAuthProjectsMyProjectsOrgId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthProjectsMyProjectsOrgId>>,
          TError,
          Awaited<ReturnType<typeof getAuthProjectsMyProjectsOrgId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthProjectsMyProjectsOrgIdInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthProjectsMyProjectsOrgId>>>,
  TError = unknown,
>(
  orgId: string,
  params?: GetAuthProjectsMyProjectsOrgIdParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getAuthProjectsMyProjectsOrgId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Lấy danh sách dự án của user
 */

export function useGetAuthProjectsMyProjectsOrgIdInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthProjectsMyProjectsOrgId>>>,
  TError = unknown,
>(
  orgId: string,
  params?: GetAuthProjectsMyProjectsOrgIdParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getAuthProjectsMyProjectsOrgId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAuthProjectsMyProjectsOrgIdInfiniteQueryOptions(
    orgId,
    params,
    options,
  );

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetAuthProjectsMyProjectsOrgIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getAuthProjectsMyProjectsOrgId>>,
  TError = unknown,
>(
  orgId: string,
  params?: GetAuthProjectsMyProjectsOrgIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthProjectsMyProjectsOrgId>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetAuthProjectsMyProjectsOrgIdQueryKey(orgId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthProjectsMyProjectsOrgId>>> = ({
    signal,
  }) => getAuthProjectsMyProjectsOrgId(orgId, params, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!orgId,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getAuthProjectsMyProjectsOrgId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAuthProjectsMyProjectsOrgIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAuthProjectsMyProjectsOrgId>>
>;
export type GetAuthProjectsMyProjectsOrgIdQueryError = unknown;

export function useGetAuthProjectsMyProjectsOrgId<
  TData = Awaited<ReturnType<typeof getAuthProjectsMyProjectsOrgId>>,
  TError = unknown,
>(
  orgId: string,
  params: undefined | GetAuthProjectsMyProjectsOrgIdParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthProjectsMyProjectsOrgId>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthProjectsMyProjectsOrgId>>,
          TError,
          Awaited<ReturnType<typeof getAuthProjectsMyProjectsOrgId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthProjectsMyProjectsOrgId<
  TData = Awaited<ReturnType<typeof getAuthProjectsMyProjectsOrgId>>,
  TError = unknown,
>(
  orgId: string,
  params?: GetAuthProjectsMyProjectsOrgIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthProjectsMyProjectsOrgId>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthProjectsMyProjectsOrgId>>,
          TError,
          Awaited<ReturnType<typeof getAuthProjectsMyProjectsOrgId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthProjectsMyProjectsOrgId<
  TData = Awaited<ReturnType<typeof getAuthProjectsMyProjectsOrgId>>,
  TError = unknown,
>(
  orgId: string,
  params?: GetAuthProjectsMyProjectsOrgIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthProjectsMyProjectsOrgId>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Lấy danh sách dự án của user
 */

export function useGetAuthProjectsMyProjectsOrgId<
  TData = Awaited<ReturnType<typeof getAuthProjectsMyProjectsOrgId>>,
  TError = unknown,
>(
  orgId: string,
  params?: GetAuthProjectsMyProjectsOrgIdParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthProjectsMyProjectsOrgId>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAuthProjectsMyProjectsOrgIdQueryOptions(orgId, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
