/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Beta Workspace API
 * API documentation for Beta - an integrated workspace platform that helps teams work more efficiently through a unified ecosystem: team chat, collaborative documents, email, task management, and workflow automation.
 * OpenAPI spec version: 1.0.0
 */
import { useInfiniteQuery, useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  GetAuthGoogleCallback200,
  GetAuthGoogleCallbackParams,
  PostAuthRegister200,
  RequestRegisterRequest,
  ResponseResponse,
} from '../generated.schemas';

import getAuthGoogleCallbackMutator from '../../config/axios';
import getAuthGoogleUrlMutator from '../../config/axios';
import postAuthRegisterMutator from '../../config/axios';

/**
 * API xử lý callback từ Google OAuth (giống NextAuth callback handler)
 * @summary Google OAuth Callback
 */
export const getAuthGoogleCallback = (
  params: GetAuthGoogleCallbackParams,
  signal?: AbortSignal,
) => {
  return getAuthGoogleCallbackMutator<GetAuthGoogleCallback200>({
    url: `/auth/google/callback`,
    method: 'GET',
    params,
    signal,
  });
};

export const getGetAuthGoogleCallbackQueryKey = (params?: GetAuthGoogleCallbackParams) => {
  return [`/auth/google/callback`, ...(params ? [params] : [])] as const;
};

export const getGetAuthGoogleCallbackInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthGoogleCallback>>>,
  TError = unknown,
>(
  params: GetAuthGoogleCallbackParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAuthGoogleCallback>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAuthGoogleCallbackQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthGoogleCallback>>> = ({ signal }) =>
    getAuthGoogleCallback(params, signal);

  return { queryKey, queryFn, staleTime: 10000, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getAuthGoogleCallback>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAuthGoogleCallbackInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAuthGoogleCallback>>
>;
export type GetAuthGoogleCallbackInfiniteQueryError = unknown;

export function useGetAuthGoogleCallbackInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthGoogleCallback>>>,
  TError = unknown,
>(
  params: GetAuthGoogleCallbackParams,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAuthGoogleCallback>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthGoogleCallback>>,
          TError,
          Awaited<ReturnType<typeof getAuthGoogleCallback>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthGoogleCallbackInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthGoogleCallback>>>,
  TError = unknown,
>(
  params: GetAuthGoogleCallbackParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAuthGoogleCallback>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthGoogleCallback>>,
          TError,
          Awaited<ReturnType<typeof getAuthGoogleCallback>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthGoogleCallbackInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthGoogleCallback>>>,
  TError = unknown,
>(
  params: GetAuthGoogleCallbackParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAuthGoogleCallback>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Google OAuth Callback
 */

export function useGetAuthGoogleCallbackInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthGoogleCallback>>>,
  TError = unknown,
>(
  params: GetAuthGoogleCallbackParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAuthGoogleCallback>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAuthGoogleCallbackInfiniteQueryOptions(params, options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetAuthGoogleCallbackQueryOptions = <
  TData = Awaited<ReturnType<typeof getAuthGoogleCallback>>,
  TError = unknown,
>(
  params: GetAuthGoogleCallbackParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthGoogleCallback>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAuthGoogleCallbackQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthGoogleCallback>>> = ({ signal }) =>
    getAuthGoogleCallback(params, signal);

  return { queryKey, queryFn, staleTime: 10000, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAuthGoogleCallback>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAuthGoogleCallbackQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAuthGoogleCallback>>
>;
export type GetAuthGoogleCallbackQueryError = unknown;

export function useGetAuthGoogleCallback<
  TData = Awaited<ReturnType<typeof getAuthGoogleCallback>>,
  TError = unknown,
>(
  params: GetAuthGoogleCallbackParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthGoogleCallback>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthGoogleCallback>>,
          TError,
          Awaited<ReturnType<typeof getAuthGoogleCallback>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthGoogleCallback<
  TData = Awaited<ReturnType<typeof getAuthGoogleCallback>>,
  TError = unknown,
>(
  params: GetAuthGoogleCallbackParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthGoogleCallback>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthGoogleCallback>>,
          TError,
          Awaited<ReturnType<typeof getAuthGoogleCallback>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthGoogleCallback<
  TData = Awaited<ReturnType<typeof getAuthGoogleCallback>>,
  TError = unknown,
>(
  params: GetAuthGoogleCallbackParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthGoogleCallback>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Google OAuth Callback
 */

export function useGetAuthGoogleCallback<
  TData = Awaited<ReturnType<typeof getAuthGoogleCallback>>,
  TError = unknown,
>(
  params: GetAuthGoogleCallbackParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthGoogleCallback>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAuthGoogleCallbackQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * API lấy URL để redirect user đến Google OAuth (giống NextAuth getAuthUrl)
 * @summary Lấy Google OAuth URL
 */
export const getAuthGoogleUrl = (signal?: AbortSignal) => {
  return getAuthGoogleUrlMutator<ResponseResponse>({
    url: `/auth/google/url`,
    method: 'GET',
    signal,
  });
};

export const getGetAuthGoogleUrlQueryKey = () => {
  return [`/auth/google/url`] as const;
};

export const getGetAuthGoogleUrlInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthGoogleUrl>>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAuthGoogleUrl>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAuthGoogleUrlQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthGoogleUrl>>> = ({ signal }) =>
    getAuthGoogleUrl(signal);

  return { queryKey, queryFn, staleTime: 10000, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getAuthGoogleUrl>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAuthGoogleUrlInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAuthGoogleUrl>>
>;
export type GetAuthGoogleUrlInfiniteQueryError = unknown;

export function useGetAuthGoogleUrlInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthGoogleUrl>>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAuthGoogleUrl>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthGoogleUrl>>,
          TError,
          Awaited<ReturnType<typeof getAuthGoogleUrl>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthGoogleUrlInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthGoogleUrl>>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAuthGoogleUrl>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthGoogleUrl>>,
          TError,
          Awaited<ReturnType<typeof getAuthGoogleUrl>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthGoogleUrlInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthGoogleUrl>>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAuthGoogleUrl>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Lấy Google OAuth URL
 */

export function useGetAuthGoogleUrlInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthGoogleUrl>>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAuthGoogleUrl>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAuthGoogleUrlInfiniteQueryOptions(options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetAuthGoogleUrlQueryOptions = <
  TData = Awaited<ReturnType<typeof getAuthGoogleUrl>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthGoogleUrl>>, TError, TData>>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAuthGoogleUrlQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthGoogleUrl>>> = ({ signal }) =>
    getAuthGoogleUrl(signal);

  return { queryKey, queryFn, staleTime: 10000, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAuthGoogleUrl>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAuthGoogleUrlQueryResult = NonNullable<Awaited<ReturnType<typeof getAuthGoogleUrl>>>;
export type GetAuthGoogleUrlQueryError = unknown;

export function useGetAuthGoogleUrl<
  TData = Awaited<ReturnType<typeof getAuthGoogleUrl>>,
  TError = unknown,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthGoogleUrl>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthGoogleUrl>>,
          TError,
          Awaited<ReturnType<typeof getAuthGoogleUrl>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthGoogleUrl<
  TData = Awaited<ReturnType<typeof getAuthGoogleUrl>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthGoogleUrl>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthGoogleUrl>>,
          TError,
          Awaited<ReturnType<typeof getAuthGoogleUrl>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthGoogleUrl<
  TData = Awaited<ReturnType<typeof getAuthGoogleUrl>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthGoogleUrl>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Lấy Google OAuth URL
 */

export function useGetAuthGoogleUrl<
  TData = Awaited<ReturnType<typeof getAuthGoogleUrl>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthGoogleUrl>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAuthGoogleUrlQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * API đăng ký tài khoản với các bước: step=1 gửi mã xác thực, step=2 xác thực email, step=3 hoàn thành đăng ký
 * @summary Đăng ký tài khoản
 */
export const postAuthRegister = (
  requestRegisterRequest: RequestRegisterRequest,
  signal?: AbortSignal,
) => {
  return postAuthRegisterMutator<PostAuthRegister200>({
    url: `/auth/register`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: requestRegisterRequest,
    signal,
  });
};

export const getPostAuthRegisterMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthRegister>>,
    TError,
    { data: RequestRegisterRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postAuthRegister>>,
  TError,
  { data: RequestRegisterRequest },
  TContext
> => {
  const mutationKey = ['postAuthRegister'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postAuthRegister>>,
    { data: RequestRegisterRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postAuthRegister(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostAuthRegisterMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAuthRegister>>
>;
export type PostAuthRegisterMutationBody = RequestRegisterRequest;
export type PostAuthRegisterMutationError = unknown;

/**
 * @summary Đăng ký tài khoản
 */
export const usePostAuthRegister = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postAuthRegister>>,
      TError,
      { data: RequestRegisterRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postAuthRegister>>,
  TError,
  { data: RequestRegisterRequest },
  TContext
> => {
  const mutationOptions = getPostAuthRegisterMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
