/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Beta Workspace API
 * API documentation for Beta - an integrated workspace platform that helps teams work more efficiently through a unified ecosystem: team chat, collaborative documents, email, task management, and workflow automation.
 * OpenAPI spec version: 1.0.0
 */
import { useInfiniteQuery, useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  DeleteAuthTasksBatchDelete200,
  GetAuthProjectsProjectIdKanban200,
  GetAuthProjectsProjectIdTasks200,
  GetAuthProjectsProjectIdTasksParams,
  GetAuthTasksTaskId200,
  PostAuthTasks200,
  PutAuthTasksTaskId200,
  PutAuthTasksTaskIdMove200,
  RequestCreateTaskRequest,
  RequestDeleteMultipleTasksRequest,
  RequestMoveTaskRequest,
  RequestSubscribeTaskRequest,
  RequestUnSubscribeTaskRequest,
  RequestUpdateTaskRequest,
  ResponseResponse,
} from '../generated.schemas';

import getAuthProjectsProjectIdKanbanMutator from '../../../config/axios';
import getAuthProjectsProjectIdTasksMutator from '../../../config/axios';
import deleteAuthTasksMutator from '../../../config/axios';
import postAuthTasksMutator from '../../../config/axios';
import getAuthTasksTaskIdMutator from '../../../config/axios';
import putAuthTasksTaskIdMutator from '../../../config/axios';
import putAuthTasksTaskIdMoveMutator from '../../../config/axios';
import deleteAuthTasksBatchDeleteMutator from '../../../config/axios';
import postAuthTasksSubscribeMutator from '../../../config/axios';
import postAuthTasksUnsubscribeMutator from '../../../config/axios';

/**
 * API lấy toàn bộ Kanban board với task lists và tasks
 * @summary Lấy Kanban board
 */
export const getAuthProjectsProjectIdKanban = (projectId: string, signal?: AbortSignal) => {
  return getAuthProjectsProjectIdKanbanMutator<GetAuthProjectsProjectIdKanban200>({
    url: `/auth/projects/${projectId}/kanban`,
    method: 'GET',
    signal,
  });
};

export const getGetAuthProjectsProjectIdKanbanQueryKey = (projectId?: string) => {
  return [`/auth/projects/${projectId}/kanban`] as const;
};

export const getGetAuthProjectsProjectIdKanbanInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthProjectsProjectIdKanban>>>,
  TError = unknown,
>(
  projectId: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getAuthProjectsProjectIdKanban>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAuthProjectsProjectIdKanbanQueryKey(projectId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthProjectsProjectIdKanban>>> = ({
    signal,
  }) => getAuthProjectsProjectIdKanban(projectId, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!projectId,
    staleTime: 10000,
    ...queryOptions,
  } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getAuthProjectsProjectIdKanban>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAuthProjectsProjectIdKanbanInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAuthProjectsProjectIdKanban>>
>;
export type GetAuthProjectsProjectIdKanbanInfiniteQueryError = unknown;

export function useGetAuthProjectsProjectIdKanbanInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthProjectsProjectIdKanban>>>,
  TError = unknown,
>(
  projectId: string,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getAuthProjectsProjectIdKanban>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthProjectsProjectIdKanban>>,
          TError,
          Awaited<ReturnType<typeof getAuthProjectsProjectIdKanban>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthProjectsProjectIdKanbanInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthProjectsProjectIdKanban>>>,
  TError = unknown,
>(
  projectId: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getAuthProjectsProjectIdKanban>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthProjectsProjectIdKanban>>,
          TError,
          Awaited<ReturnType<typeof getAuthProjectsProjectIdKanban>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthProjectsProjectIdKanbanInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthProjectsProjectIdKanban>>>,
  TError = unknown,
>(
  projectId: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getAuthProjectsProjectIdKanban>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Lấy Kanban board
 */

export function useGetAuthProjectsProjectIdKanbanInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthProjectsProjectIdKanban>>>,
  TError = unknown,
>(
  projectId: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getAuthProjectsProjectIdKanban>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAuthProjectsProjectIdKanbanInfiniteQueryOptions(projectId, options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetAuthProjectsProjectIdKanbanQueryOptions = <
  TData = Awaited<ReturnType<typeof getAuthProjectsProjectIdKanban>>,
  TError = unknown,
>(
  projectId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthProjectsProjectIdKanban>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAuthProjectsProjectIdKanbanQueryKey(projectId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthProjectsProjectIdKanban>>> = ({
    signal,
  }) => getAuthProjectsProjectIdKanban(projectId, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!projectId,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getAuthProjectsProjectIdKanban>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAuthProjectsProjectIdKanbanQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAuthProjectsProjectIdKanban>>
>;
export type GetAuthProjectsProjectIdKanbanQueryError = unknown;

export function useGetAuthProjectsProjectIdKanban<
  TData = Awaited<ReturnType<typeof getAuthProjectsProjectIdKanban>>,
  TError = unknown,
>(
  projectId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthProjectsProjectIdKanban>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthProjectsProjectIdKanban>>,
          TError,
          Awaited<ReturnType<typeof getAuthProjectsProjectIdKanban>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthProjectsProjectIdKanban<
  TData = Awaited<ReturnType<typeof getAuthProjectsProjectIdKanban>>,
  TError = unknown,
>(
  projectId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthProjectsProjectIdKanban>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthProjectsProjectIdKanban>>,
          TError,
          Awaited<ReturnType<typeof getAuthProjectsProjectIdKanban>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthProjectsProjectIdKanban<
  TData = Awaited<ReturnType<typeof getAuthProjectsProjectIdKanban>>,
  TError = unknown,
>(
  projectId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthProjectsProjectIdKanban>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Lấy Kanban board
 */

export function useGetAuthProjectsProjectIdKanban<
  TData = Awaited<ReturnType<typeof getAuthProjectsProjectIdKanban>>,
  TError = unknown,
>(
  projectId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthProjectsProjectIdKanban>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAuthProjectsProjectIdKanbanQueryOptions(projectId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * API lấy tất cả tasks trong dự án với filter và pagination
 * @summary Lấy danh sách tasks trong dự án
 */
export const getAuthProjectsProjectIdTasks = (
  projectId: string,
  params?: GetAuthProjectsProjectIdTasksParams,
  signal?: AbortSignal,
) => {
  return getAuthProjectsProjectIdTasksMutator<GetAuthProjectsProjectIdTasks200>({
    url: `/auth/projects/${projectId}/tasks`,
    method: 'GET',
    params,
    signal,
  });
};

export const getGetAuthProjectsProjectIdTasksQueryKey = (
  projectId?: string,
  params?: GetAuthProjectsProjectIdTasksParams,
) => {
  return [`/auth/projects/${projectId}/tasks`, ...(params ? [params] : [])] as const;
};

export const getGetAuthProjectsProjectIdTasksInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthProjectsProjectIdTasks>>>,
  TError = unknown,
>(
  projectId: string,
  params?: GetAuthProjectsProjectIdTasksParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getAuthProjectsProjectIdTasks>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetAuthProjectsProjectIdTasksQueryKey(projectId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthProjectsProjectIdTasks>>> = ({
    signal,
  }) => getAuthProjectsProjectIdTasks(projectId, params, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!projectId,
    staleTime: 10000,
    ...queryOptions,
  } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getAuthProjectsProjectIdTasks>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAuthProjectsProjectIdTasksInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAuthProjectsProjectIdTasks>>
>;
export type GetAuthProjectsProjectIdTasksInfiniteQueryError = unknown;

export function useGetAuthProjectsProjectIdTasksInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthProjectsProjectIdTasks>>>,
  TError = unknown,
>(
  projectId: string,
  params: undefined | GetAuthProjectsProjectIdTasksParams,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getAuthProjectsProjectIdTasks>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthProjectsProjectIdTasks>>,
          TError,
          Awaited<ReturnType<typeof getAuthProjectsProjectIdTasks>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthProjectsProjectIdTasksInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthProjectsProjectIdTasks>>>,
  TError = unknown,
>(
  projectId: string,
  params?: GetAuthProjectsProjectIdTasksParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getAuthProjectsProjectIdTasks>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthProjectsProjectIdTasks>>,
          TError,
          Awaited<ReturnType<typeof getAuthProjectsProjectIdTasks>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthProjectsProjectIdTasksInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthProjectsProjectIdTasks>>>,
  TError = unknown,
>(
  projectId: string,
  params?: GetAuthProjectsProjectIdTasksParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getAuthProjectsProjectIdTasks>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Lấy danh sách tasks trong dự án
 */

export function useGetAuthProjectsProjectIdTasksInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthProjectsProjectIdTasks>>>,
  TError = unknown,
>(
  projectId: string,
  params?: GetAuthProjectsProjectIdTasksParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getAuthProjectsProjectIdTasks>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAuthProjectsProjectIdTasksInfiniteQueryOptions(
    projectId,
    params,
    options,
  );

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetAuthProjectsProjectIdTasksQueryOptions = <
  TData = Awaited<ReturnType<typeof getAuthProjectsProjectIdTasks>>,
  TError = unknown,
>(
  projectId: string,
  params?: GetAuthProjectsProjectIdTasksParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthProjectsProjectIdTasks>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetAuthProjectsProjectIdTasksQueryKey(projectId, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthProjectsProjectIdTasks>>> = ({
    signal,
  }) => getAuthProjectsProjectIdTasks(projectId, params, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!projectId,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getAuthProjectsProjectIdTasks>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetAuthProjectsProjectIdTasksQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAuthProjectsProjectIdTasks>>
>;
export type GetAuthProjectsProjectIdTasksQueryError = unknown;

export function useGetAuthProjectsProjectIdTasks<
  TData = Awaited<ReturnType<typeof getAuthProjectsProjectIdTasks>>,
  TError = unknown,
>(
  projectId: string,
  params: undefined | GetAuthProjectsProjectIdTasksParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthProjectsProjectIdTasks>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthProjectsProjectIdTasks>>,
          TError,
          Awaited<ReturnType<typeof getAuthProjectsProjectIdTasks>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthProjectsProjectIdTasks<
  TData = Awaited<ReturnType<typeof getAuthProjectsProjectIdTasks>>,
  TError = unknown,
>(
  projectId: string,
  params?: GetAuthProjectsProjectIdTasksParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthProjectsProjectIdTasks>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthProjectsProjectIdTasks>>,
          TError,
          Awaited<ReturnType<typeof getAuthProjectsProjectIdTasks>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthProjectsProjectIdTasks<
  TData = Awaited<ReturnType<typeof getAuthProjectsProjectIdTasks>>,
  TError = unknown,
>(
  projectId: string,
  params?: GetAuthProjectsProjectIdTasksParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthProjectsProjectIdTasks>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Lấy danh sách tasks trong dự án
 */

export function useGetAuthProjectsProjectIdTasks<
  TData = Awaited<ReturnType<typeof getAuthProjectsProjectIdTasks>>,
  TError = unknown,
>(
  projectId: string,
  params?: GetAuthProjectsProjectIdTasksParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthProjectsProjectIdTasks>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAuthProjectsProjectIdTasksQueryOptions(projectId, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * API xóa task khỏi dự án
 * @summary Xóa task
 */
export const deleteAuthTasks = () => {
  return deleteAuthTasksMutator<ResponseResponse>({ url: `/auth/tasks`, method: 'DELETE' });
};

export const getDeleteAuthTasksMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteAuthTasks>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<Awaited<ReturnType<typeof deleteAuthTasks>>, TError, void, TContext> => {
  const mutationKey = ['deleteAuthTasks'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteAuthTasks>>, void> = () => {
    return deleteAuthTasks();
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteAuthTasksMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteAuthTasks>>
>;

export type DeleteAuthTasksMutationError = unknown;

/**
 * @summary Xóa task
 */
export const useDeleteAuthTasks = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteAuthTasks>>,
      TError,
      void,
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof deleteAuthTasks>>, TError, void, TContext> => {
  const mutationOptions = getDeleteAuthTasksMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * API tạo task mới trong danh sách
 * @summary Tạo task mới
 */
export const postAuthTasks = (
  requestCreateTaskRequest: RequestCreateTaskRequest,
  signal?: AbortSignal,
) => {
  return postAuthTasksMutator<PostAuthTasks200>({
    url: `/auth/tasks`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: requestCreateTaskRequest,
    signal,
  });
};

export const getPostAuthTasksMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthTasks>>,
    TError,
    { data: RequestCreateTaskRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postAuthTasks>>,
  TError,
  { data: RequestCreateTaskRequest },
  TContext
> => {
  const mutationKey = ['postAuthTasks'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postAuthTasks>>,
    { data: RequestCreateTaskRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postAuthTasks(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostAuthTasksMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthTasks>>>;
export type PostAuthTasksMutationBody = RequestCreateTaskRequest;
export type PostAuthTasksMutationError = unknown;

/**
 * @summary Tạo task mới
 */
export const usePostAuthTasks = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postAuthTasks>>,
      TError,
      { data: RequestCreateTaskRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postAuthTasks>>,
  TError,
  { data: RequestCreateTaskRequest },
  TContext
> => {
  const mutationOptions = getPostAuthTasksMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * API lấy thông tin chi tiết task
 * @summary Lấy thông tin task
 */
export const getAuthTasksTaskId = (taskId: string, signal?: AbortSignal) => {
  return getAuthTasksTaskIdMutator<GetAuthTasksTaskId200>({
    url: `/auth/tasks/${taskId}`,
    method: 'GET',
    signal,
  });
};

export const getGetAuthTasksTaskIdQueryKey = (taskId?: string) => {
  return [`/auth/tasks/${taskId}`] as const;
};

export const getGetAuthTasksTaskIdInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthTasksTaskId>>>,
  TError = unknown,
>(
  taskId: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAuthTasksTaskId>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAuthTasksTaskIdQueryKey(taskId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthTasksTaskId>>> = ({ signal }) =>
    getAuthTasksTaskId(taskId, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!taskId,
    staleTime: 10000,
    ...queryOptions,
  } as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAuthTasksTaskId>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetAuthTasksTaskIdInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAuthTasksTaskId>>
>;
export type GetAuthTasksTaskIdInfiniteQueryError = unknown;

export function useGetAuthTasksTaskIdInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthTasksTaskId>>>,
  TError = unknown,
>(
  taskId: string,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAuthTasksTaskId>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthTasksTaskId>>,
          TError,
          Awaited<ReturnType<typeof getAuthTasksTaskId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthTasksTaskIdInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthTasksTaskId>>>,
  TError = unknown,
>(
  taskId: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAuthTasksTaskId>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthTasksTaskId>>,
          TError,
          Awaited<ReturnType<typeof getAuthTasksTaskId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthTasksTaskIdInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthTasksTaskId>>>,
  TError = unknown,
>(
  taskId: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAuthTasksTaskId>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Lấy thông tin task
 */

export function useGetAuthTasksTaskIdInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthTasksTaskId>>>,
  TError = unknown,
>(
  taskId: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAuthTasksTaskId>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAuthTasksTaskIdInfiniteQueryOptions(taskId, options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetAuthTasksTaskIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getAuthTasksTaskId>>,
  TError = unknown,
>(
  taskId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthTasksTaskId>>, TError, TData>>;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAuthTasksTaskIdQueryKey(taskId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthTasksTaskId>>> = ({ signal }) =>
    getAuthTasksTaskId(taskId, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!taskId,
    staleTime: 10000,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getAuthTasksTaskId>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetAuthTasksTaskIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAuthTasksTaskId>>
>;
export type GetAuthTasksTaskIdQueryError = unknown;

export function useGetAuthTasksTaskId<
  TData = Awaited<ReturnType<typeof getAuthTasksTaskId>>,
  TError = unknown,
>(
  taskId: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthTasksTaskId>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthTasksTaskId>>,
          TError,
          Awaited<ReturnType<typeof getAuthTasksTaskId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthTasksTaskId<
  TData = Awaited<ReturnType<typeof getAuthTasksTaskId>>,
  TError = unknown,
>(
  taskId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthTasksTaskId>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthTasksTaskId>>,
          TError,
          Awaited<ReturnType<typeof getAuthTasksTaskId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthTasksTaskId<
  TData = Awaited<ReturnType<typeof getAuthTasksTaskId>>,
  TError = unknown,
>(
  taskId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthTasksTaskId>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Lấy thông tin task
 */

export function useGetAuthTasksTaskId<
  TData = Awaited<ReturnType<typeof getAuthTasksTaskId>>,
  TError = unknown,
>(
  taskId: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthTasksTaskId>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAuthTasksTaskIdQueryOptions(taskId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * API cập nhật thông tin task
 * @summary Cập nhật task
 */
export const putAuthTasksTaskId = (
  taskId: string,
  requestUpdateTaskRequest: RequestUpdateTaskRequest,
) => {
  return putAuthTasksTaskIdMutator<PutAuthTasksTaskId200>({
    url: `/auth/tasks/${taskId}`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: requestUpdateTaskRequest,
  });
};

export const getPutAuthTasksTaskIdMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putAuthTasksTaskId>>,
    TError,
    { taskId: string; data: RequestUpdateTaskRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putAuthTasksTaskId>>,
  TError,
  { taskId: string; data: RequestUpdateTaskRequest },
  TContext
> => {
  const mutationKey = ['putAuthTasksTaskId'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putAuthTasksTaskId>>,
    { taskId: string; data: RequestUpdateTaskRequest }
  > = (props) => {
    const { taskId, data } = props ?? {};

    return putAuthTasksTaskId(taskId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutAuthTasksTaskIdMutationResult = NonNullable<
  Awaited<ReturnType<typeof putAuthTasksTaskId>>
>;
export type PutAuthTasksTaskIdMutationBody = RequestUpdateTaskRequest;
export type PutAuthTasksTaskIdMutationError = unknown;

/**
 * @summary Cập nhật task
 */
export const usePutAuthTasksTaskId = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putAuthTasksTaskId>>,
      TError,
      { taskId: string; data: RequestUpdateTaskRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putAuthTasksTaskId>>,
  TError,
  { taskId: string; data: RequestUpdateTaskRequest },
  TContext
> => {
  const mutationOptions = getPutAuthTasksTaskIdMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * API di chuyển task sang list khác hoặc thay đổi vị trí
 * @summary Di chuyển task
 */
export const putAuthTasksTaskIdMove = (
  taskId: string,
  requestMoveTaskRequest: RequestMoveTaskRequest,
) => {
  return putAuthTasksTaskIdMoveMutator<PutAuthTasksTaskIdMove200>({
    url: `/auth/tasks/${taskId}/move`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: requestMoveTaskRequest,
  });
};

export const getPutAuthTasksTaskIdMoveMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putAuthTasksTaskIdMove>>,
    TError,
    { taskId: string; data: RequestMoveTaskRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putAuthTasksTaskIdMove>>,
  TError,
  { taskId: string; data: RequestMoveTaskRequest },
  TContext
> => {
  const mutationKey = ['putAuthTasksTaskIdMove'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putAuthTasksTaskIdMove>>,
    { taskId: string; data: RequestMoveTaskRequest }
  > = (props) => {
    const { taskId, data } = props ?? {};

    return putAuthTasksTaskIdMove(taskId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutAuthTasksTaskIdMoveMutationResult = NonNullable<
  Awaited<ReturnType<typeof putAuthTasksTaskIdMove>>
>;
export type PutAuthTasksTaskIdMoveMutationBody = RequestMoveTaskRequest;
export type PutAuthTasksTaskIdMoveMutationError = unknown;

/**
 * @summary Di chuyển task
 */
export const usePutAuthTasksTaskIdMove = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putAuthTasksTaskIdMove>>,
      TError,
      { taskId: string; data: RequestMoveTaskRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putAuthTasksTaskIdMove>>,
  TError,
  { taskId: string; data: RequestMoveTaskRequest },
  TContext
> => {
  const mutationOptions = getPutAuthTasksTaskIdMoveMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * API xóa nhiều tasks cùng lúc trong dự án
 * @summary Xóa nhiều tasks cùng lúc
 */
export const deleteAuthTasksBatchDelete = (
  requestDeleteMultipleTasksRequest: RequestDeleteMultipleTasksRequest,
) => {
  return deleteAuthTasksBatchDeleteMutator<DeleteAuthTasksBatchDelete200>({
    url: `/auth/tasks/batch-delete`,
    method: 'DELETE',
    headers: { 'Content-Type': 'application/json' },
    data: requestDeleteMultipleTasksRequest,
  });
};

export const getDeleteAuthTasksBatchDeleteMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteAuthTasksBatchDelete>>,
    TError,
    { data: RequestDeleteMultipleTasksRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteAuthTasksBatchDelete>>,
  TError,
  { data: RequestDeleteMultipleTasksRequest },
  TContext
> => {
  const mutationKey = ['deleteAuthTasksBatchDelete'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteAuthTasksBatchDelete>>,
    { data: RequestDeleteMultipleTasksRequest }
  > = (props) => {
    const { data } = props ?? {};

    return deleteAuthTasksBatchDelete(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteAuthTasksBatchDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteAuthTasksBatchDelete>>
>;
export type DeleteAuthTasksBatchDeleteMutationBody = RequestDeleteMultipleTasksRequest;
export type DeleteAuthTasksBatchDeleteMutationError = unknown;

/**
 * @summary Xóa nhiều tasks cùng lúc
 */
export const useDeleteAuthTasksBatchDelete = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteAuthTasksBatchDelete>>,
      TError,
      { data: RequestDeleteMultipleTasksRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteAuthTasksBatchDelete>>,
  TError,
  { data: RequestDeleteMultipleTasksRequest },
  TContext
> => {
  const mutationOptions = getDeleteAuthTasksBatchDeleteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * API đăng ký nhận thông báo từ một task
 * @summary Đăng ký nhận thông báo task
 */
export const postAuthTasksSubscribe = (
  requestSubscribeTaskRequest: RequestSubscribeTaskRequest,
  signal?: AbortSignal,
) => {
  return postAuthTasksSubscribeMutator<ResponseResponse>({
    url: `/auth/tasks/subscribe`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: requestSubscribeTaskRequest,
    signal,
  });
};

export const getPostAuthTasksSubscribeMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthTasksSubscribe>>,
    TError,
    { data: RequestSubscribeTaskRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postAuthTasksSubscribe>>,
  TError,
  { data: RequestSubscribeTaskRequest },
  TContext
> => {
  const mutationKey = ['postAuthTasksSubscribe'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postAuthTasksSubscribe>>,
    { data: RequestSubscribeTaskRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postAuthTasksSubscribe(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostAuthTasksSubscribeMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAuthTasksSubscribe>>
>;
export type PostAuthTasksSubscribeMutationBody = RequestSubscribeTaskRequest;
export type PostAuthTasksSubscribeMutationError = unknown;

/**
 * @summary Đăng ký nhận thông báo task
 */
export const usePostAuthTasksSubscribe = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postAuthTasksSubscribe>>,
      TError,
      { data: RequestSubscribeTaskRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postAuthTasksSubscribe>>,
  TError,
  { data: RequestSubscribeTaskRequest },
  TContext
> => {
  const mutationOptions = getPostAuthTasksSubscribeMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * API hủy đăng ký nhận thông báo từ một task
 * @summary Hủy đăng ký nhận thông báo task
 */
export const postAuthTasksUnsubscribe = (
  requestUnSubscribeTaskRequest: RequestUnSubscribeTaskRequest,
  signal?: AbortSignal,
) => {
  return postAuthTasksUnsubscribeMutator<ResponseResponse>({
    url: `/auth/tasks/unsubscribe`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: requestUnSubscribeTaskRequest,
    signal,
  });
};

export const getPostAuthTasksUnsubscribeMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthTasksUnsubscribe>>,
    TError,
    { data: RequestUnSubscribeTaskRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postAuthTasksUnsubscribe>>,
  TError,
  { data: RequestUnSubscribeTaskRequest },
  TContext
> => {
  const mutationKey = ['postAuthTasksUnsubscribe'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postAuthTasksUnsubscribe>>,
    { data: RequestUnSubscribeTaskRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postAuthTasksUnsubscribe(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostAuthTasksUnsubscribeMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAuthTasksUnsubscribe>>
>;
export type PostAuthTasksUnsubscribeMutationBody = RequestUnSubscribeTaskRequest;
export type PostAuthTasksUnsubscribeMutationError = unknown;

/**
 * @summary Hủy đăng ký nhận thông báo task
 */
export const usePostAuthTasksUnsubscribe = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postAuthTasksUnsubscribe>>,
      TError,
      { data: RequestUnSubscribeTaskRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postAuthTasksUnsubscribe>>,
  TError,
  { data: RequestUnSubscribeTaskRequest },
  TContext
> => {
  const mutationOptions = getPostAuthTasksUnsubscribeMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
