/**
 * Generated by orval v7.13.0 🍺
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Beta Workspace API
 * API documentation for Beta - an integrated workspace platform that helps teams work more efficiently through a unified ecosystem: team chat, collaborative documents, email, task management, and workflow automation.
 * OpenAPI spec version: 1.0.0
 */
import { useInfiniteQuery, useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  GetAuthOrganizations200,
  GetAuthOrganizationsId200,
  GetAuthOrganizationsIdMembers200,
  GetAuthOrganizationsParams,
  PatchAuthOrganizations200,
  PostAuthOrganizations201,
  PostAuthOrganizationsInvite201,
  PostAuthOrganizationsJoin200,
  PostAuthOrganizationsLaunch200,
  RequestCreateOrganizationRequest,
  RequestDeleteMemberInOrgRequest,
  RequestInviteMemberRequest,
  RequestJoinOrganizationRequest,
  RequestLaunchOrganizationRequest,
  RequestLaunchOrganizationRequest,
  RequestUpdateMemberRoleRequest,
  RequestUpdateOrganizationRequest,
  ResponseResponse,
} from '../generated.schemas';

import getAuthOrganizationsMutator from '../../config/axios';
import patchAuthOrganizationsMutator from '../../config/axios';
import postAuthOrganizationsMutator from '../../config/axios';
import getAuthOrganizationsIdMutator from '../../config/axios';
import getAuthOrganizationsIdMembersMutator from '../../config/axios';
import postAuthOrganizationsInviteMutator from '../../config/axios';
import postAuthOrganizationsJoinMutator from '../../config/axios';
import postAuthOrganizationsLaunchMutator from '../../config/axios';
import deleteAuthOrganizationsMemberMutator from '../../config/axios';
import putAuthOrganizationsMembersRoleMutator from '../../config/axios';

/**
 * API lấy tất cả tổ chức mà user tham gia
 * @summary Lấy danh sách tổ chức của user
 */
export const getAuthOrganizations = (params: GetAuthOrganizationsParams, signal?: AbortSignal) => {
  return getAuthOrganizationsMutator<GetAuthOrganizations200>({
    url: `/auth/organizations`,
    method: 'GET',
    params,
    signal,
  });
};

export const getGetAuthOrganizationsQueryKey = (params?: GetAuthOrganizationsParams) => {
  return [`/auth/organizations`, ...(params ? [params] : [])] as const;
};

export const getGetAuthOrganizationsInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthOrganizations>>>,
  TError = unknown,
>(
  params: GetAuthOrganizationsParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAuthOrganizations>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAuthOrganizationsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthOrganizations>>> = ({ signal }) =>
    getAuthOrganizations(params, signal);

  return { queryKey, queryFn, staleTime: 10000, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getAuthOrganizations>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAuthOrganizationsInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAuthOrganizations>>
>;
export type GetAuthOrganizationsInfiniteQueryError = unknown;

export function useGetAuthOrganizationsInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthOrganizations>>>,
  TError = unknown,
>(
  params: GetAuthOrganizationsParams,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAuthOrganizations>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthOrganizations>>,
          TError,
          Awaited<ReturnType<typeof getAuthOrganizations>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthOrganizationsInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthOrganizations>>>,
  TError = unknown,
>(
  params: GetAuthOrganizationsParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAuthOrganizations>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthOrganizations>>,
          TError,
          Awaited<ReturnType<typeof getAuthOrganizations>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthOrganizationsInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthOrganizations>>>,
  TError = unknown,
>(
  params: GetAuthOrganizationsParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAuthOrganizations>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Lấy danh sách tổ chức của user
 */

export function useGetAuthOrganizationsInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthOrganizations>>>,
  TError = unknown,
>(
  params: GetAuthOrganizationsParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAuthOrganizations>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAuthOrganizationsInfiniteQueryOptions(params, options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetAuthOrganizationsQueryOptions = <
  TData = Awaited<ReturnType<typeof getAuthOrganizations>>,
  TError = unknown,
>(
  params: GetAuthOrganizationsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthOrganizations>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAuthOrganizationsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthOrganizations>>> = ({ signal }) =>
    getAuthOrganizations(params, signal);

  return { queryKey, queryFn, staleTime: 10000, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAuthOrganizations>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAuthOrganizationsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAuthOrganizations>>
>;
export type GetAuthOrganizationsQueryError = unknown;

export function useGetAuthOrganizations<
  TData = Awaited<ReturnType<typeof getAuthOrganizations>>,
  TError = unknown,
>(
  params: GetAuthOrganizationsParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthOrganizations>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthOrganizations>>,
          TError,
          Awaited<ReturnType<typeof getAuthOrganizations>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthOrganizations<
  TData = Awaited<ReturnType<typeof getAuthOrganizations>>,
  TError = unknown,
>(
  params: GetAuthOrganizationsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthOrganizations>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthOrganizations>>,
          TError,
          Awaited<ReturnType<typeof getAuthOrganizations>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthOrganizations<
  TData = Awaited<ReturnType<typeof getAuthOrganizations>>,
  TError = unknown,
>(
  params: GetAuthOrganizationsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthOrganizations>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Lấy danh sách tổ chức của user
 */

export function useGetAuthOrganizations<
  TData = Awaited<ReturnType<typeof getAuthOrganizations>>,
  TError = unknown,
>(
  params: GetAuthOrganizationsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthOrganizations>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAuthOrganizationsQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * API cập nhật thông tin tổ chức (chỉ admin)
 * @summary Cập nhật thông tin tổ chức
 */
export const patchAuthOrganizations = (
  requestUpdateOrganizationRequest: RequestUpdateOrganizationRequest,
) => {
  return patchAuthOrganizationsMutator<PatchAuthOrganizations200>({
    url: `/auth/organizations`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    data: requestUpdateOrganizationRequest,
  });
};

export const getPatchAuthOrganizationsMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof patchAuthOrganizations>>,
    TError,
    { data: RequestUpdateOrganizationRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof patchAuthOrganizations>>,
  TError,
  { data: RequestUpdateOrganizationRequest },
  TContext
> => {
  const mutationKey = ['patchAuthOrganizations'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof patchAuthOrganizations>>,
    { data: RequestUpdateOrganizationRequest }
  > = (props) => {
    const { data } = props ?? {};

    return patchAuthOrganizations(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PatchAuthOrganizationsMutationResult = NonNullable<
  Awaited<ReturnType<typeof patchAuthOrganizations>>
>;
export type PatchAuthOrganizationsMutationBody = RequestUpdateOrganizationRequest;
export type PatchAuthOrganizationsMutationError = unknown;

/**
 * @summary Cập nhật thông tin tổ chức
 */
export const usePatchAuthOrganizations = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof patchAuthOrganizations>>,
      TError,
      { data: RequestUpdateOrganizationRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof patchAuthOrganizations>>,
  TError,
  { data: RequestUpdateOrganizationRequest },
  TContext
> => {
  const mutationOptions = getPatchAuthOrganizationsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * API tạo tổ chức mới với user hiện tại làm admin
 * @summary Tạo tổ chức mới
 */
export const postAuthOrganizations = (
  requestCreateOrganizationRequest: RequestCreateOrganizationRequest,
  signal?: AbortSignal,
) => {
  return postAuthOrganizationsMutator<PostAuthOrganizations201>({
    url: `/auth/organizations`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: requestCreateOrganizationRequest,
    signal,
  });
};

export const getPostAuthOrganizationsMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthOrganizations>>,
    TError,
    { data: RequestCreateOrganizationRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postAuthOrganizations>>,
  TError,
  { data: RequestCreateOrganizationRequest },
  TContext
> => {
  const mutationKey = ['postAuthOrganizations'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postAuthOrganizations>>,
    { data: RequestCreateOrganizationRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postAuthOrganizations(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostAuthOrganizationsMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAuthOrganizations>>
>;
export type PostAuthOrganizationsMutationBody = RequestCreateOrganizationRequest;
export type PostAuthOrganizationsMutationError = unknown;

/**
 * @summary Tạo tổ chức mới
 */
export const usePostAuthOrganizations = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postAuthOrganizations>>,
      TError,
      { data: RequestCreateOrganizationRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postAuthOrganizations>>,
  TError,
  { data: RequestCreateOrganizationRequest },
  TContext
> => {
  const mutationOptions = getPostAuthOrganizationsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * API lấy thông tin chi tiết của một tổ chức (chỉ thành viên tổ chức mới xem được)
 * @summary Lấy thông tin tổ chức
 */
export const getAuthOrganizationsId = (id: string, signal?: AbortSignal) => {
  return getAuthOrganizationsIdMutator<GetAuthOrganizationsId200>({
    url: `/auth/organizations/${id}`,
    method: 'GET',
    signal,
  });
};

export const getGetAuthOrganizationsIdQueryKey = (id?: string) => {
  return [`/auth/organizations/${id}`] as const;
};

export const getGetAuthOrganizationsIdInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthOrganizationsId>>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAuthOrganizationsId>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAuthOrganizationsIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthOrganizationsId>>> = ({ signal }) =>
    getAuthOrganizationsId(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    staleTime: 10000,
    ...queryOptions,
  } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getAuthOrganizationsId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAuthOrganizationsIdInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAuthOrganizationsId>>
>;
export type GetAuthOrganizationsIdInfiniteQueryError = unknown;

export function useGetAuthOrganizationsIdInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthOrganizationsId>>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAuthOrganizationsId>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthOrganizationsId>>,
          TError,
          Awaited<ReturnType<typeof getAuthOrganizationsId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthOrganizationsIdInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthOrganizationsId>>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAuthOrganizationsId>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthOrganizationsId>>,
          TError,
          Awaited<ReturnType<typeof getAuthOrganizationsId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthOrganizationsIdInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthOrganizationsId>>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAuthOrganizationsId>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Lấy thông tin tổ chức
 */

export function useGetAuthOrganizationsIdInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthOrganizationsId>>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAuthOrganizationsId>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAuthOrganizationsIdInfiniteQueryOptions(id, options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetAuthOrganizationsIdQueryOptions = <
  TData = Awaited<ReturnType<typeof getAuthOrganizationsId>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthOrganizationsId>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAuthOrganizationsIdQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthOrganizationsId>>> = ({ signal }) =>
    getAuthOrganizationsId(id, signal);

  return { queryKey, queryFn, enabled: !!id, staleTime: 10000, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAuthOrganizationsId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAuthOrganizationsIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAuthOrganizationsId>>
>;
export type GetAuthOrganizationsIdQueryError = unknown;

export function useGetAuthOrganizationsId<
  TData = Awaited<ReturnType<typeof getAuthOrganizationsId>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthOrganizationsId>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthOrganizationsId>>,
          TError,
          Awaited<ReturnType<typeof getAuthOrganizationsId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthOrganizationsId<
  TData = Awaited<ReturnType<typeof getAuthOrganizationsId>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthOrganizationsId>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthOrganizationsId>>,
          TError,
          Awaited<ReturnType<typeof getAuthOrganizationsId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthOrganizationsId<
  TData = Awaited<ReturnType<typeof getAuthOrganizationsId>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthOrganizationsId>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Lấy thông tin tổ chức
 */

export function useGetAuthOrganizationsId<
  TData = Awaited<ReturnType<typeof getAuthOrganizationsId>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthOrganizationsId>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAuthOrganizationsIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * API lấy tất cả thành viên của tổ chức only member
 * @summary Lấy danh sách thành viên tổ chức
 */
export const getAuthOrganizationsIdMembers = (id: string, signal?: AbortSignal) => {
  return getAuthOrganizationsIdMembersMutator<GetAuthOrganizationsIdMembers200>({
    url: `/auth/organizations/${id}/members`,
    method: 'GET',
    signal,
  });
};

export const getGetAuthOrganizationsIdMembersQueryKey = (id?: string) => {
  return [`/auth/organizations/${id}/members`] as const;
};

export const getGetAuthOrganizationsIdMembersInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthOrganizationsIdMembers>>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getAuthOrganizationsIdMembers>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAuthOrganizationsIdMembersQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthOrganizationsIdMembers>>> = ({
    signal,
  }) => getAuthOrganizationsIdMembers(id, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    staleTime: 10000,
    ...queryOptions,
  } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getAuthOrganizationsIdMembers>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAuthOrganizationsIdMembersInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAuthOrganizationsIdMembers>>
>;
export type GetAuthOrganizationsIdMembersInfiniteQueryError = unknown;

export function useGetAuthOrganizationsIdMembersInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthOrganizationsIdMembers>>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getAuthOrganizationsIdMembers>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthOrganizationsIdMembers>>,
          TError,
          Awaited<ReturnType<typeof getAuthOrganizationsIdMembers>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthOrganizationsIdMembersInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthOrganizationsIdMembers>>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getAuthOrganizationsIdMembers>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthOrganizationsIdMembers>>,
          TError,
          Awaited<ReturnType<typeof getAuthOrganizationsIdMembers>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthOrganizationsIdMembersInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthOrganizationsIdMembers>>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getAuthOrganizationsIdMembers>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Lấy danh sách thành viên tổ chức
 */

export function useGetAuthOrganizationsIdMembersInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthOrganizationsIdMembers>>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof getAuthOrganizationsIdMembers>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAuthOrganizationsIdMembersInfiniteQueryOptions(id, options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetAuthOrganizationsIdMembersQueryOptions = <
  TData = Awaited<ReturnType<typeof getAuthOrganizationsIdMembers>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthOrganizationsIdMembers>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAuthOrganizationsIdMembersQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthOrganizationsIdMembers>>> = ({
    signal,
  }) => getAuthOrganizationsIdMembers(id, signal);

  return { queryKey, queryFn, enabled: !!id, staleTime: 10000, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAuthOrganizationsIdMembers>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAuthOrganizationsIdMembersQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAuthOrganizationsIdMembers>>
>;
export type GetAuthOrganizationsIdMembersQueryError = unknown;

export function useGetAuthOrganizationsIdMembers<
  TData = Awaited<ReturnType<typeof getAuthOrganizationsIdMembers>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthOrganizationsIdMembers>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthOrganizationsIdMembers>>,
          TError,
          Awaited<ReturnType<typeof getAuthOrganizationsIdMembers>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthOrganizationsIdMembers<
  TData = Awaited<ReturnType<typeof getAuthOrganizationsIdMembers>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthOrganizationsIdMembers>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthOrganizationsIdMembers>>,
          TError,
          Awaited<ReturnType<typeof getAuthOrganizationsIdMembers>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthOrganizationsIdMembers<
  TData = Awaited<ReturnType<typeof getAuthOrganizationsIdMembers>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthOrganizationsIdMembers>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Lấy danh sách thành viên tổ chức
 */

export function useGetAuthOrganizationsIdMembers<
  TData = Awaited<ReturnType<typeof getAuthOrganizationsIdMembers>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthOrganizationsIdMembers>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAuthOrganizationsIdMembersQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * API tạo lời mời cho thành viên mới (là member của tổ chức)
 * @summary Mời thành viên vào tổ chức
 */
export const postAuthOrganizationsInvite = (
  requestInviteMemberRequest: RequestInviteMemberRequest,
  signal?: AbortSignal,
) => {
  return postAuthOrganizationsInviteMutator<PostAuthOrganizationsInvite201>({
    url: `/auth/organizations/invite`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: requestInviteMemberRequest,
    signal,
  });
};

export const getPostAuthOrganizationsInviteMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthOrganizationsInvite>>,
    TError,
    { data: RequestInviteMemberRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postAuthOrganizationsInvite>>,
  TError,
  { data: RequestInviteMemberRequest },
  TContext
> => {
  const mutationKey = ['postAuthOrganizationsInvite'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postAuthOrganizationsInvite>>,
    { data: RequestInviteMemberRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postAuthOrganizationsInvite(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostAuthOrganizationsInviteMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAuthOrganizationsInvite>>
>;
export type PostAuthOrganizationsInviteMutationBody = RequestInviteMemberRequest;
export type PostAuthOrganizationsInviteMutationError = unknown;

/**
 * @summary Mời thành viên vào tổ chức
 */
export const usePostAuthOrganizationsInvite = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postAuthOrganizationsInvite>>,
      TError,
      { data: RequestInviteMemberRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postAuthOrganizationsInvite>>,
  TError,
  { data: RequestInviteMemberRequest },
  TContext
> => {
  const mutationOptions = getPostAuthOrganizationsInviteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * API tham gia tổ chức bằng mã mời
 * @summary Tham gia tổ chức
 */
export const postAuthOrganizationsJoin = (
  requestJoinOrganizationRequest: RequestJoinOrganizationRequest,
  signal?: AbortSignal,
) => {
  return postAuthOrganizationsJoinMutator<PostAuthOrganizationsJoin200>({
    url: `/auth/organizations/join`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: requestJoinOrganizationRequest,
    signal,
  });
};

export const getPostAuthOrganizationsJoinMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthOrganizationsJoin>>,
    TError,
    { data: RequestJoinOrganizationRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postAuthOrganizationsJoin>>,
  TError,
  { data: RequestJoinOrganizationRequest },
  TContext
> => {
  const mutationKey = ['postAuthOrganizationsJoin'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postAuthOrganizationsJoin>>,
    { data: RequestJoinOrganizationRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postAuthOrganizationsJoin(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostAuthOrganizationsJoinMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAuthOrganizationsJoin>>
>;
export type PostAuthOrganizationsJoinMutationBody = RequestJoinOrganizationRequest;
export type PostAuthOrganizationsJoinMutationError = unknown;

/**
 * @summary Tham gia tổ chức
 */
export const usePostAuthOrganizationsJoin = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postAuthOrganizationsJoin>>,
      TError,
      { data: RequestJoinOrganizationRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postAuthOrganizationsJoin>>,
  TError,
  { data: RequestJoinOrganizationRequest },
  TContext
> => {
  const mutationOptions = getPostAuthOrganizationsJoinMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * API Launch tổ chức cho user hiện tại
 * @summary Launch tổ chức cho user
 */
export const postAuthOrganizationsLaunch = (
  requestLaunchOrganizationRequest: RequestLaunchOrganizationRequest,
  signal?: AbortSignal,
) => {
  return postAuthOrganizationsLaunchMutator<PostAuthOrganizationsLaunch200>({
    url: `/auth/organizations/launch`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: requestLaunchOrganizationRequest,
    signal,
  });
};

export const getPostAuthOrganizationsLaunchMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthOrganizationsLaunch>>,
    TError,
    { data: RequestLaunchOrganizationRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postAuthOrganizationsLaunch>>,
  TError,
  { data: RequestLaunchOrganizationRequest },
  TContext
> => {
  const mutationKey = ['postAuthOrganizationsLaunch'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postAuthOrganizationsLaunch>>,
    { data: RequestLaunchOrganizationRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postAuthOrganizationsLaunch(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostAuthOrganizationsLaunchMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAuthOrganizationsLaunch>>
>;
export type PostAuthOrganizationsLaunchMutationBody = RequestLaunchOrganizationRequest;
export type PostAuthOrganizationsLaunchMutationError = unknown;

/**
 * @summary Launch tổ chức cho user
 */
export const usePostAuthOrganizationsLaunch = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postAuthOrganizationsLaunch>>,
      TError,
      { data: RequestLaunchOrganizationRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postAuthOrganizationsLaunch>>,
  TError,
  { data: RequestLaunchOrganizationRequest },
  TContext
> => {
  const mutationOptions = getPostAuthOrganizationsLaunchMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * API tạo lời mời cho thành viên mới (là member của tổ chức)
 * @summary Mời thành viên vào tổ chức
 */
export const postAuthOrganizationsInvite = (
  requestInviteMemberRequest: RequestInviteMemberRequest,
  signal?: AbortSignal,
) => {
  return postAuthOrganizationsInviteMutator<PostAuthOrganizationsInvite201>({
    url: `/auth/organizations/invite`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: requestInviteMemberRequest,
    signal,
  });
};

export const getPostAuthOrganizationsInviteMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthOrganizationsInvite>>,
    TError,
    { data: RequestInviteMemberRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postAuthOrganizationsInvite>>,
  TError,
  { data: RequestInviteMemberRequest },
  TContext
> => {
  const mutationKey = ['postAuthOrganizationsInvite'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postAuthOrganizationsInvite>>,
    { data: RequestInviteMemberRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postAuthOrganizationsInvite(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostAuthOrganizationsInviteMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAuthOrganizationsInvite>>
>;
export type PostAuthOrganizationsInviteMutationBody = RequestInviteMemberRequest;
export type PostAuthOrganizationsInviteMutationError = unknown;

/**
 * @summary Mời thành viên vào tổ chức
 */
export const usePostAuthOrganizationsInvite = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postAuthOrganizationsInvite>>,
      TError,
      { data: RequestInviteMemberRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postAuthOrganizationsInvite>>,
  TError,
  { data: RequestInviteMemberRequest },
  TContext
> => {
  const mutationOptions = getPostAuthOrganizationsInviteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * API tham gia tổ chức bằng mã mời
 * @summary Tham gia tổ chức
 */
export const postAuthOrganizationsJoin = (
  requestJoinOrganizationRequest: RequestJoinOrganizationRequest,
  signal?: AbortSignal,
) => {
  return postAuthOrganizationsJoinMutator<PostAuthOrganizationsJoin200>({
    url: `/auth/organizations/join`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: requestJoinOrganizationRequest,
    signal,
  });
};

export const getPostAuthOrganizationsJoinMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthOrganizationsJoin>>,
    TError,
    { data: RequestJoinOrganizationRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postAuthOrganizationsJoin>>,
  TError,
  { data: RequestJoinOrganizationRequest },
  TContext
> => {
  const mutationKey = ['postAuthOrganizationsJoin'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postAuthOrganizationsJoin>>,
    { data: RequestJoinOrganizationRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postAuthOrganizationsJoin(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostAuthOrganizationsJoinMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAuthOrganizationsJoin>>
>;
export type PostAuthOrganizationsJoinMutationBody = RequestJoinOrganizationRequest;
export type PostAuthOrganizationsJoinMutationError = unknown;

/**
 * @summary Tham gia tổ chức
 */
export const usePostAuthOrganizationsJoin = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postAuthOrganizationsJoin>>,
      TError,
      { data: RequestJoinOrganizationRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postAuthOrganizationsJoin>>,
  TError,
  { data: RequestJoinOrganizationRequest },
  TContext
> => {
  const mutationOptions = getPostAuthOrganizationsJoinMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * API Launch tổ chức cho user hiện tại
 * @summary Launch tổ chức cho user
 */
export const postAuthOrganizationsLaunch = (
  requestLaunchOrganizationRequest: RequestLaunchOrganizationRequest,
  signal?: AbortSignal,
) => {
  return postAuthOrganizationsLaunchMutator<PostAuthOrganizationsLaunch200>({
    url: `/auth/organizations/launch`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: requestLaunchOrganizationRequest,
    signal,
  });
};

export const getPostAuthOrganizationsLaunchMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthOrganizationsLaunch>>,
    TError,
    { data: RequestLaunchOrganizationRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postAuthOrganizationsLaunch>>,
  TError,
  { data: RequestLaunchOrganizationRequest },
  TContext
> => {
  const mutationKey = ['postAuthOrganizationsLaunch'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postAuthOrganizationsLaunch>>,
    { data: RequestLaunchOrganizationRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postAuthOrganizationsLaunch(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostAuthOrganizationsLaunchMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAuthOrganizationsLaunch>>
>;
export type PostAuthOrganizationsLaunchMutationBody = RequestLaunchOrganizationRequest;
export type PostAuthOrganizationsLaunchMutationError = unknown;

/**
 * @summary Launch tổ chức cho user
 */
export const usePostAuthOrganizationsLaunch = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postAuthOrganizationsLaunch>>,
      TError,
      { data: RequestLaunchOrganizationRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postAuthOrganizationsLaunch>>,
  TError,
  { data: RequestLaunchOrganizationRequest },
  TContext
> => {
  const mutationOptions = getPostAuthOrganizationsLaunchMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * API xóa thành viên khỏi tổ chức (chỉ admin)
 * @summary Xóa thành viên khỏi tổ chức
 */
export const deleteAuthOrganizationsMember = (
  requestDeleteMemberInOrgRequest: RequestDeleteMemberInOrgRequest,
) => {
  return deleteAuthOrganizationsMemberMutator<ResponseResponse>({
    url: `/auth/organizations/member`,
    method: 'DELETE',
    headers: { 'Content-Type': 'application/json' },
    data: requestDeleteMemberInOrgRequest,
  });
};

export const getDeleteAuthOrganizationsMemberMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteAuthOrganizationsMember>>,
    TError,
    { data: RequestDeleteMemberInOrgRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteAuthOrganizationsMember>>,
  TError,
  { data: RequestDeleteMemberInOrgRequest },
  TContext
> => {
  const mutationKey = ['deleteAuthOrganizationsMember'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteAuthOrganizationsMember>>,
    { data: RequestDeleteMemberInOrgRequest }
  > = (props) => {
    const { data } = props ?? {};

    return deleteAuthOrganizationsMember(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteAuthOrganizationsMemberMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteAuthOrganizationsMember>>
>;
export type DeleteAuthOrganizationsMemberMutationBody = RequestDeleteMemberInOrgRequest;
export type DeleteAuthOrganizationsMemberMutationError = unknown;

/**
 * @summary Xóa thành viên khỏi tổ chức
 */
export const useDeleteAuthOrganizationsMember = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteAuthOrganizationsMember>>,
      TError,
      { data: RequestDeleteMemberInOrgRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteAuthOrganizationsMember>>,
  TError,
  { data: RequestDeleteMemberInOrgRequest },
  TContext
> => {
  const mutationOptions = getDeleteAuthOrganizationsMemberMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * API cập nhật vai trò của thành viên trong tổ chức (chỉ admin)
 * @summary Cập nhật vai trò thành viên
 */
export const putAuthOrganizationsMembersRole = (
  requestUpdateMemberRoleRequest: RequestUpdateMemberRoleRequest,
) => {
  return putAuthOrganizationsMembersRoleMutator<ResponseResponse>({
    url: `/auth/organizations/members/role`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: requestUpdateMemberRoleRequest,
  });
};

export const getPutAuthOrganizationsMembersRoleMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putAuthOrganizationsMembersRole>>,
    TError,
    { data: RequestUpdateMemberRoleRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putAuthOrganizationsMembersRole>>,
  TError,
  { data: RequestUpdateMemberRoleRequest },
  TContext
> => {
  const mutationKey = ['putAuthOrganizationsMembersRole'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putAuthOrganizationsMembersRole>>,
    { data: RequestUpdateMemberRoleRequest }
  > = (props) => {
    const { data } = props ?? {};

    return putAuthOrganizationsMembersRole(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutAuthOrganizationsMembersRoleMutationResult = NonNullable<
  Awaited<ReturnType<typeof putAuthOrganizationsMembersRole>>
>;
export type PutAuthOrganizationsMembersRoleMutationBody = RequestUpdateMemberRoleRequest;
export type PutAuthOrganizationsMembersRoleMutationError = unknown;

/**
 * @summary Cập nhật vai trò thành viên
 */
export const usePutAuthOrganizationsMembersRole = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putAuthOrganizationsMembersRole>>,
      TError,
      { data: RequestUpdateMemberRoleRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putAuthOrganizationsMembersRole>>,
  TError,
  { data: RequestUpdateMemberRoleRequest },
  TContext
> => {
  const mutationOptions = getPutAuthOrganizationsMembersRoleMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
