/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Beta Workspace API
 * API documentation for Beta - an integrated workspace platform that helps teams work more efficiently through a unified ecosystem: team chat, collaborative documents, email, task management, and workflow automation.
 * OpenAPI spec version: 1.0.0
 */
import { useInfiniteQuery, useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  GetAuthUserProfile200,
  PostForgotPassword202,
  PostLogin200,
  PutAuthUserProfile200,
  RequestChangePasswordRequest,
  RequestForgotPasswordRequest,
  RequestLoginRequest,
  RequestUpdateProfileRequest,
  ResponseResponse,
} from '../generated.schemas';

import postAuthLogoutMutator from '../../config/axios';
import deleteAuthUserAccountMutator from '../../config/axios';
import patchAuthUserPasswordMutator from '../../config/axios';
import getAuthUserProfileMutator from '../../config/axios';
import putAuthUserProfileMutator from '../../config/axios';
import postForgotPasswordMutator from '../../config/axios';
import postLoginMutator from '../../config/axios';

/**
 * API đăng xuất khỏi workspace platform
 * @summary Đăng xuất
 */
export const postAuthLogout = (signal?: AbortSignal) => {
  return postAuthLogoutMutator<ResponseResponse>({ url: `/auth/logout`, method: 'POST', signal });
};

export const getPostAuthLogoutMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<Awaited<ReturnType<typeof postAuthLogout>>, TError, void, TContext>;
}): UseMutationOptions<Awaited<ReturnType<typeof postAuthLogout>>, TError, void, TContext> => {
  const mutationKey = ['postAuthLogout'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthLogout>>, void> = () => {
    return postAuthLogout();
  };

  return { mutationFn, ...mutationOptions };
};

export type PostAuthLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthLogout>>>;

export type PostAuthLogoutMutationError = unknown;

/**
 * @summary Đăng xuất
 */
export const usePostAuthLogout = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postAuthLogout>>,
      TError,
      void,
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof postAuthLogout>>, TError, void, TContext> => {
  const mutationOptions = getPostAuthLogoutMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * API xóa user và tất cả những thông tin liên quan trong workspace
 * @summary Xóa Account
 */
export const deleteAuthUserAccount = () => {
  return deleteAuthUserAccountMutator<ResponseResponse>({
    url: `/auth/user/account`,
    method: 'DELETE',
  });
};

export const getDeleteAuthUserAccountMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteAuthUserAccount>>,
    TError,
    void,
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteAuthUserAccount>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ['deleteAuthUserAccount'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteAuthUserAccount>>,
    void
  > = () => {
    return deleteAuthUserAccount();
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteAuthUserAccountMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteAuthUserAccount>>
>;

export type DeleteAuthUserAccountMutationError = unknown;

/**
 * @summary Xóa Account
 */
export const useDeleteAuthUserAccount = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteAuthUserAccount>>,
      TError,
      void,
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<Awaited<ReturnType<typeof deleteAuthUserAccount>>, TError, void, TContext> => {
  const mutationOptions = getDeleteAuthUserAccountMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * API thay đổi mật khẩu
 * @summary Thay đổi mật khẩu
 */
export const patchAuthUserPassword = (
  requestChangePasswordRequest: RequestChangePasswordRequest,
) => {
  return patchAuthUserPasswordMutator<ResponseResponse>({
    url: `/auth/user/password`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    data: requestChangePasswordRequest,
  });
};

export const getPatchAuthUserPasswordMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof patchAuthUserPassword>>,
    TError,
    { data: RequestChangePasswordRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof patchAuthUserPassword>>,
  TError,
  { data: RequestChangePasswordRequest },
  TContext
> => {
  const mutationKey = ['patchAuthUserPassword'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof patchAuthUserPassword>>,
    { data: RequestChangePasswordRequest }
  > = (props) => {
    const { data } = props ?? {};

    return patchAuthUserPassword(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PatchAuthUserPasswordMutationResult = NonNullable<
  Awaited<ReturnType<typeof patchAuthUserPassword>>
>;
export type PatchAuthUserPasswordMutationBody = RequestChangePasswordRequest;
export type PatchAuthUserPasswordMutationError = unknown;

/**
 * @summary Thay đổi mật khẩu
 */
export const usePatchAuthUserPassword = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof patchAuthUserPassword>>,
      TError,
      { data: RequestChangePasswordRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof patchAuthUserPassword>>,
  TError,
  { data: RequestChangePasswordRequest },
  TContext
> => {
  const mutationOptions = getPatchAuthUserPasswordMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * API lấy thông tin người dùng cho workspace
 * @summary Lấy thông tin người dùng
 */
export const getAuthUserProfile = (signal?: AbortSignal) => {
  return getAuthUserProfileMutator<GetAuthUserProfile200>({
    url: `/auth/user/profile`,
    method: 'GET',
    signal,
  });
};

export const getGetAuthUserProfileQueryKey = () => {
  return [`/auth/user/profile`] as const;
};

export const getGetAuthUserProfileInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthUserProfile>>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAuthUserProfile>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAuthUserProfileQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthUserProfile>>> = ({ signal }) =>
    getAuthUserProfile(signal);

  return { queryKey, queryFn, staleTime: 10000, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getAuthUserProfile>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAuthUserProfileInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAuthUserProfile>>
>;
export type GetAuthUserProfileInfiniteQueryError = unknown;

export function useGetAuthUserProfileInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthUserProfile>>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAuthUserProfile>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthUserProfile>>,
          TError,
          Awaited<ReturnType<typeof getAuthUserProfile>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthUserProfileInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthUserProfile>>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAuthUserProfile>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthUserProfile>>,
          TError,
          Awaited<ReturnType<typeof getAuthUserProfile>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthUserProfileInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthUserProfile>>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAuthUserProfile>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Lấy thông tin người dùng
 */

export function useGetAuthUserProfileInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthUserProfile>>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAuthUserProfile>>, TError, TData>
    >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAuthUserProfileInfiniteQueryOptions(options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetAuthUserProfileQueryOptions = <
  TData = Awaited<ReturnType<typeof getAuthUserProfile>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthUserProfile>>, TError, TData>>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAuthUserProfileQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthUserProfile>>> = ({ signal }) =>
    getAuthUserProfile(signal);

  return { queryKey, queryFn, staleTime: 10000, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAuthUserProfile>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAuthUserProfileQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAuthUserProfile>>
>;
export type GetAuthUserProfileQueryError = unknown;

export function useGetAuthUserProfile<
  TData = Awaited<ReturnType<typeof getAuthUserProfile>>,
  TError = unknown,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthUserProfile>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthUserProfile>>,
          TError,
          Awaited<ReturnType<typeof getAuthUserProfile>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthUserProfile<
  TData = Awaited<ReturnType<typeof getAuthUserProfile>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getAuthUserProfile>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthUserProfile>>,
          TError,
          Awaited<ReturnType<typeof getAuthUserProfile>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthUserProfile<
  TData = Awaited<ReturnType<typeof getAuthUserProfile>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthUserProfile>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Lấy thông tin người dùng
 */

export function useGetAuthUserProfile<
  TData = Awaited<ReturnType<typeof getAuthUserProfile>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthUserProfile>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAuthUserProfileQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * API cập nhật thông tin cá nhân cho workspace
 * @summary Cập nhật thông tin cá nhân
 */
export const putAuthUserProfile = (requestUpdateProfileRequest: RequestUpdateProfileRequest) => {
  return putAuthUserProfileMutator<PutAuthUserProfile200>({
    url: `/auth/user/profile`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: requestUpdateProfileRequest,
  });
};

export const getPutAuthUserProfileMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof putAuthUserProfile>>,
    TError,
    { data: RequestUpdateProfileRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof putAuthUserProfile>>,
  TError,
  { data: RequestUpdateProfileRequest },
  TContext
> => {
  const mutationKey = ['putAuthUserProfile'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof putAuthUserProfile>>,
    { data: RequestUpdateProfileRequest }
  > = (props) => {
    const { data } = props ?? {};

    return putAuthUserProfile(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PutAuthUserProfileMutationResult = NonNullable<
  Awaited<ReturnType<typeof putAuthUserProfile>>
>;
export type PutAuthUserProfileMutationBody = RequestUpdateProfileRequest;
export type PutAuthUserProfileMutationError = unknown;

/**
 * @summary Cập nhật thông tin cá nhân
 */
export const usePutAuthUserProfile = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof putAuthUserProfile>>,
      TError,
      { data: RequestUpdateProfileRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof putAuthUserProfile>>,
  TError,
  { data: RequestUpdateProfileRequest },
  TContext
> => {
  const mutationOptions = getPutAuthUserProfileMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * API quên mật khẩu, step = 1 gửi mail đến địa chỉ mail được nhập, step = 2 thực hiện nhập mật khẩu mới
 * @summary Quên mật khẩu
 */
export const postForgotPassword = (
  requestForgotPasswordRequest: RequestForgotPasswordRequest,
  signal?: AbortSignal,
) => {
  return postForgotPasswordMutator<ResponseResponse | PostForgotPassword202>({
    url: `/forgot_password`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: requestForgotPasswordRequest,
    signal,
  });
};

export const getPostForgotPasswordMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postForgotPassword>>,
    TError,
    { data: RequestForgotPasswordRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postForgotPassword>>,
  TError,
  { data: RequestForgotPasswordRequest },
  TContext
> => {
  const mutationKey = ['postForgotPassword'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postForgotPassword>>,
    { data: RequestForgotPasswordRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postForgotPassword(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostForgotPasswordMutationResult = NonNullable<
  Awaited<ReturnType<typeof postForgotPassword>>
>;
export type PostForgotPasswordMutationBody = RequestForgotPasswordRequest;
export type PostForgotPasswordMutationError = unknown;

/**
 * @summary Quên mật khẩu
 */
export const usePostForgotPassword = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postForgotPassword>>,
      TError,
      { data: RequestForgotPasswordRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postForgotPassword>>,
  TError,
  { data: RequestForgotPasswordRequest },
  TContext
> => {
  const mutationOptions = getPostForgotPasswordMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * API đăng nhập vào workspace platform với email và mật khẩu
 * @summary Đăng nhập
 */
export const postLogin = (requestLoginRequest: RequestLoginRequest, signal?: AbortSignal) => {
  return postLoginMutator<PostLogin200>({
    url: `/login`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: requestLoginRequest,
    signal,
  });
};

export const getPostLoginMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postLogin>>,
    TError,
    { data: RequestLoginRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postLogin>>,
  TError,
  { data: RequestLoginRequest },
  TContext
> => {
  const mutationKey = ['postLogin'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postLogin>>,
    { data: RequestLoginRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postLogin(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostLoginMutationResult = NonNullable<Awaited<ReturnType<typeof postLogin>>>;
export type PostLoginMutationBody = RequestLoginRequest;
export type PostLoginMutationError = unknown;

/**
 * @summary Đăng nhập
 */
export const usePostLogin = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postLogin>>,
      TError,
      { data: RequestLoginRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postLogin>>,
  TError,
  { data: RequestLoginRequest },
  TContext
> => {
  const mutationOptions = getPostLoginMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
