/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Beta Workspace API
 * API documentation for Beta - an integrated workspace platform that helps teams work more efficiently through a unified ecosystem: team chat, collaborative documents, email, task management, and workflow automation.
 * OpenAPI spec version: 1.0.0
 */
import { useMutation } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query';

import type {
  RequestNotificationRequest,
  RequestRegisterDeviceRequest,
  ResponseResponse,
} from '../generated.schemas';

import postAuthNotificationRegisterDeviceMutator from '../../../config/axios';
import postAuthNotificationSendMutator from '../../../config/axios';

/**
 * API đăng ký token device để nhận thông báo
 * @summary Đăng ký token device
 */
export const postAuthNotificationRegisterDevice = (
  requestRegisterDeviceRequest: RequestRegisterDeviceRequest,
  signal?: AbortSignal,
) => {
  return postAuthNotificationRegisterDeviceMutator<ResponseResponse>({
    url: `/auth/notification/register_device`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: requestRegisterDeviceRequest,
    signal,
  });
};

export const getPostAuthNotificationRegisterDeviceMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthNotificationRegisterDevice>>,
    TError,
    { data: RequestRegisterDeviceRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postAuthNotificationRegisterDevice>>,
  TError,
  { data: RequestRegisterDeviceRequest },
  TContext
> => {
  const mutationKey = ['postAuthNotificationRegisterDevice'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postAuthNotificationRegisterDevice>>,
    { data: RequestRegisterDeviceRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postAuthNotificationRegisterDevice(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostAuthNotificationRegisterDeviceMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAuthNotificationRegisterDevice>>
>;
export type PostAuthNotificationRegisterDeviceMutationBody = RequestRegisterDeviceRequest;
export type PostAuthNotificationRegisterDeviceMutationError = unknown;

/**
 * @summary Đăng ký token device
 */
export const usePostAuthNotificationRegisterDevice = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postAuthNotificationRegisterDevice>>,
      TError,
      { data: RequestRegisterDeviceRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postAuthNotificationRegisterDevice>>,
  TError,
  { data: RequestRegisterDeviceRequest },
  TContext
> => {
  const mutationOptions = getPostAuthNotificationRegisterDeviceMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * API gửi thông báo cho workspace
 * @summary Gửi thông báo
 */
export const postAuthNotificationSend = (
  requestNotificationRequest: RequestNotificationRequest,
  signal?: AbortSignal,
) => {
  return postAuthNotificationSendMutator<ResponseResponse>({
    url: `/auth/notification/send`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: requestNotificationRequest,
    signal,
  });
};

export const getPostAuthNotificationSendMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postAuthNotificationSend>>,
    TError,
    { data: RequestNotificationRequest },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postAuthNotificationSend>>,
  TError,
  { data: RequestNotificationRequest },
  TContext
> => {
  const mutationKey = ['postAuthNotificationSend'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postAuthNotificationSend>>,
    { data: RequestNotificationRequest }
  > = (props) => {
    const { data } = props ?? {};

    return postAuthNotificationSend(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostAuthNotificationSendMutationResult = NonNullable<
  Awaited<ReturnType<typeof postAuthNotificationSend>>
>;
export type PostAuthNotificationSendMutationBody = RequestNotificationRequest;
export type PostAuthNotificationSendMutationError = unknown;

/**
 * @summary Gửi thông báo
 */
export const usePostAuthNotificationSend = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postAuthNotificationSend>>,
      TError,
      { data: RequestNotificationRequest },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postAuthNotificationSend>>,
  TError,
  { data: RequestNotificationRequest },
  TContext
> => {
  const mutationOptions = getPostAuthNotificationSendMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
