/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * Beta Workspace API
 * API documentation for Beta - an integrated workspace platform that helps teams work more efficiently through a unified ecosystem: team chat, collaborative documents, email, task management, and workflow automation.
 * OpenAPI spec version: 1.0.0
 */
import { useInfiniteQuery, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { ResponseResponse } from '../generated.schemas';

import getAuthWsMutator from '../../../config/axios';

/**
 * Websocket endpoint dùng để nhắn tin và gửi thông báo realtime
 * @summary Kết nối Websocket
 */
export const getAuthWs = (signal?: AbortSignal) => {
  return getAuthWsMutator<ResponseResponse>({ url: `/auth/ws`, method: 'GET', signal });
};

export const getGetAuthWsQueryKey = () => {
  return [`/auth/ws`] as const;
};

export const getGetAuthWsInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthWs>>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAuthWs>>, TError, TData>>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAuthWsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthWs>>> = ({ signal }) =>
    getAuthWs(signal);

  return { queryKey, queryFn, staleTime: 10000, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof getAuthWs>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAuthWsInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getAuthWs>>>;
export type GetAuthWsInfiniteQueryError = unknown;

export function useGetAuthWsInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthWs>>>,
  TError = unknown,
>(
  options: {
    query: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAuthWs>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthWs>>,
          TError,
          Awaited<ReturnType<typeof getAuthWs>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthWsInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthWs>>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAuthWs>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthWs>>,
          TError,
          Awaited<ReturnType<typeof getAuthWs>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthWsInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthWs>>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAuthWs>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Kết nối Websocket
 */

export function useGetAuthWsInfinite<
  TData = InfiniteData<Awaited<ReturnType<typeof getAuthWs>>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getAuthWs>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseInfiniteQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAuthWsInfiniteQueryOptions(options);

  const query = useInfiniteQuery(queryOptions, queryClient) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetAuthWsQueryOptions = <
  TData = Awaited<ReturnType<typeof getAuthWs>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthWs>>, TError, TData>>;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAuthWsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAuthWs>>> = ({ signal }) =>
    getAuthWs(signal);

  return { queryKey, queryFn, staleTime: 10000, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAuthWs>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAuthWsQueryResult = NonNullable<Awaited<ReturnType<typeof getAuthWs>>>;
export type GetAuthWsQueryError = unknown;

export function useGetAuthWs<TData = Awaited<ReturnType<typeof getAuthWs>>, TError = unknown>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthWs>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthWs>>,
          TError,
          Awaited<ReturnType<typeof getAuthWs>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthWs<TData = Awaited<ReturnType<typeof getAuthWs>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthWs>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAuthWs>>,
          TError,
          Awaited<ReturnType<typeof getAuthWs>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetAuthWs<TData = Awaited<ReturnType<typeof getAuthWs>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthWs>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary Kết nối Websocket
 */

export function useGetAuthWs<TData = Awaited<ReturnType<typeof getAuthWs>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getAuthWs>>, TError, TData>>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetAuthWsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
